[functions.orion-chat]
verify_jwt = false

[functions.check_buk_candidate]
verify_jwt = false

[functions.orion-document-processor]
verify_jwt = true

[functions.hiring-transactional-email]
verify_jwt = false

[functions.purge-candidate-documents]
verify_jwt = false

[functions.remove-candidate-document]
verify_jwt = true

[functions.sync-buk-candidates]
verify_jwt = false

[functions.sync-buk-job-positions]
verify_jwt = true

[functions.upload-buk-accreditation-document]
verify_jwt = true

[functions.verify-competency-certificate]
verify_jwt = true

[functions.verify-hiring-document]
verify_jwt = true

[functions.generate-competency-certificate]
enabled = true
verify_jwt = false
import_map = "./functions/generate-competency-certificate/deno.json"
static_files = ["./functions/generate-competency-certificate/assets/guillermo-zanartu-apara.png"]
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-competency-certificate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-competency-certificate/*.html" ]

[functions.request-password-reset]
verify_jwt = false

[functions.psycholaboral-assessment]
verify_jwt = false

[functions.generate-psycholaboral-certificate]
verify_jwt = false
