begin;

insert into public.app_roles (code, name, description)
values (
  'aprobador_folios',
  'Aprobador de Folios',
  'Aprueba o rechaza solicitudes de contratacion en la cadena secuencial.'
)
on conflict (code) do update
set
  name = excluded.name,
  description = excluded.description,
  is_active = true;

create table if not exists public.cost_center_approvers (
  id bigint generated by default as identity primary key,
  cost_center_code text not null unique,
  cost_center_name text not null,
  approver_user_id uuid references public.profiles (id) on delete restrict,
  approver_name text not null,
  approver_email text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workflow_approvers (
  step_code text primary key
    check (step_code in ('contracts_control')),
  approver_user_id uuid references public.profiles (id) on delete restrict,
  approver_name text not null,
  approver_email text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.hiring_request_snapshots (
  id bigint generated by default as identity primary key,
  hiring_request_id uuid not null references public.hiring_requests (id) on delete cascade,
  snapshot_type text not null
    check (snapshot_type in ('submitted')),
  payload jsonb not null,
  created_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.hiring_request_audit_log (
  id bigint generated by default as identity primary key,
  hiring_request_id uuid not null references public.hiring_requests (id) on delete cascade,
  approval_id bigint references public.hiring_request_approvals (id) on delete set null,
  actor_user_id uuid not null references public.profiles (id) on delete restrict,
  action_type text not null
    check (action_type in ('submitted', 'approval_created', 'approved', 'rejected')),
  old_values jsonb,
  new_values jsonb,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_cost_center_approvers_user_id
  on public.cost_center_approvers (approver_user_id);
create index if not exists idx_hiring_request_snapshots_request_id
  on public.hiring_request_snapshots (hiring_request_id);
create index if not exists idx_hiring_request_audit_log_request_id
  on public.hiring_request_audit_log (hiring_request_id);
create index if not exists idx_hiring_request_audit_log_actor_id
  on public.hiring_request_audit_log (actor_user_id);
create index if not exists idx_hiring_request_approvals_approver_pending
  on public.hiring_request_approvals (approver_user_id, status);

drop trigger if exists trg_cost_center_approvers_set_updated_at on public.cost_center_approvers;
create trigger trg_cost_center_approvers_set_updated_at
before update on public.cost_center_approvers
for each row execute function public.set_updated_at();

drop trigger if exists trg_workflow_approvers_set_updated_at on public.workflow_approvers;
create trigger trg_workflow_approvers_set_updated_at
before update on public.workflow_approvers
for each row execute function public.set_updated_at();

alter table public.hiring_requests
  add column if not exists current_step_code text,
  add column if not exists submitted_at timestamptz,
  add column if not exists submitted_by uuid references public.profiles (id) on delete restrict,
  add column if not exists approved_at timestamptz,
  add column if not exists rejected_at timestamptz,
  add column if not exists final_decided_by uuid references public.profiles (id) on delete set null;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'hiring_request_approvals'
      and column_name = 'comments'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'hiring_request_approvals'
      and column_name = 'decision_comment'
  ) then
    alter table public.hiring_request_approvals
      rename column comments to decision_comment;
  end if;
end $$;

alter table public.hiring_request_approvals
  add column if not exists decision_by uuid references public.profiles (id) on delete set null,
  add column if not exists locked_at timestamptz;

update public.hiring_requests
set submitted_at = coalesce(submitted_at, created_at, timezone('utc', now())),
    submitted_by = coalesce(submitted_by, requester_id)
where submitted_at is null
   or submitted_by is null;

alter table public.hiring_requests
  alter column submitted_at set not null;

alter table public.hiring_requests
  alter column submitted_by set not null;

alter table public.hiring_requests
  alter column status drop default;

alter table public.hiring_requests
  drop constraint if exists hiring_requests_status_check;

alter table public.hiring_requests
  drop constraint if exists hiring_requests_current_step_code_check;

delete from public.hiring_request_approvals contracts_pending
where contracts_pending.step_code = 'contracts_control'
  and contracts_pending.status = 'pending'
  and exists (
    select 1
    from public.hiring_request_approvals area_pending
    where area_pending.hiring_request_id = contracts_pending.hiring_request_id
      and area_pending.step_code = 'area_manager'
      and area_pending.status = 'pending'
  );

update public.hiring_requests hr
set
  status = 'rejected',
  current_step_code = null,
  rejected_at = coalesce(hr.rejected_at, hr.updated_at, timezone('utc', now())),
  approved_at = null
where exists (
  select 1
  from public.hiring_request_approvals hra
  where hra.hiring_request_id = hr.id
    and hra.status = 'rejected'
);

update public.hiring_requests hr
set
  status = 'approved',
  current_step_code = null,
  approved_at = coalesce(hr.approved_at, hr.updated_at, timezone('utc', now())),
  rejected_at = null
where hr.status is distinct from 'rejected'
  and exists (
    select 1
    from public.hiring_request_approvals hra
    where hra.hiring_request_id = hr.id
      and hra.step_code = 'contracts_control'
      and hra.status = 'approved'
  );

update public.hiring_requests hr
set
  status = 'pending_contracts_control',
  current_step_code = 'contracts_control',
  approved_at = null,
  rejected_at = null
where hr.status not in ('approved', 'rejected')
  and exists (
    select 1
    from public.hiring_request_approvals hra
    where hra.hiring_request_id = hr.id
      and hra.step_code = 'area_manager'
      and hra.status = 'approved'
  )
  and exists (
    select 1
    from public.hiring_request_approvals hra
    where hra.hiring_request_id = hr.id
      and hra.step_code = 'contracts_control'
      and hra.status = 'pending'
  );

update public.hiring_requests hr
set
  status = 'pending_area_manager',
  current_step_code = 'area_manager',
  approved_at = null,
  rejected_at = null
where hr.status not in ('approved', 'rejected', 'pending_contracts_control')
  and exists (
    select 1
    from public.hiring_request_approvals hra
    where hra.hiring_request_id = hr.id
      and hra.step_code = 'area_manager'
      and hra.status = 'pending'
  );

update public.hiring_requests
set
  status = 'pending_area_manager',
  current_step_code = 'area_manager',
  approved_at = null,
  rejected_at = null
where status not in ('approved', 'rejected', 'pending_contracts_control', 'pending_area_manager');

alter table public.hiring_requests
  add constraint hiring_requests_status_check
  check (status in ('pending_area_manager', 'pending_contracts_control', 'approved', 'rejected'));

alter table public.hiring_requests
  add constraint hiring_requests_current_step_code_check
  check (current_step_code in ('area_manager', 'contracts_control') or current_step_code is null);

alter table public.hiring_requests
  alter column status set default 'pending_area_manager';

drop trigger if exists trg_hiring_request_approvals_refresh_status on public.hiring_request_approvals;

alter table public.cost_center_approvers enable row level security;
alter table public.workflow_approvers enable row level security;
alter table public.hiring_request_snapshots enable row level security;
alter table public.hiring_request_audit_log enable row level security;

drop policy if exists "cost_center_approvers_admin_only" on public.cost_center_approvers;
create policy "cost_center_approvers_admin_only"
on public.cost_center_approvers
for select
to authenticated
using (public.user_is_admin(auth.uid()));

drop policy if exists "workflow_approvers_admin_only" on public.workflow_approvers;
create policy "workflow_approvers_admin_only"
on public.workflow_approvers
for select
to authenticated
using (public.user_is_admin(auth.uid()));

drop policy if exists "hiring_requests_select_owned_or_operational" on public.hiring_requests;
create policy "hiring_requests_select_scoped"
on public.hiring_requests
for select
to authenticated
using (
  requester_id = auth.uid()
  or public.user_is_admin(auth.uid())
  or exists (
    select 1
    from public.hiring_request_approvals hra
    where hra.hiring_request_id = public.hiring_requests.id
      and hra.approver_user_id = auth.uid()
      and hra.status = 'pending'
      and hra.step_code = public.hiring_requests.current_step_code
  )
);

drop policy if exists "hiring_requests_insert_requester" on public.hiring_requests;
drop policy if exists "hiring_requests_update_operational" on public.hiring_requests;

drop policy if exists "hiring_request_approvals_select_visible" on public.hiring_request_approvals;
create policy "hiring_request_approvals_select_scoped"
on public.hiring_request_approvals
for select
to authenticated
using (
  approver_user_id = auth.uid()
  or public.user_is_admin(auth.uid())
  or exists (
    select 1
    from public.hiring_requests hr
    where hr.id = hiring_request_id
      and hr.requester_id = auth.uid()
  )
);

drop policy if exists "hiring_request_snapshots_select_scoped" on public.hiring_request_snapshots;
create policy "hiring_request_snapshots_select_scoped"
on public.hiring_request_snapshots
for select
to authenticated
using (
  public.user_is_admin(auth.uid())
  or exists (
    select 1
    from public.hiring_requests hr
    where hr.id = hiring_request_id
      and (
        hr.requester_id = auth.uid()
        or exists (
          select 1
          from public.hiring_request_approvals hra
          where hra.hiring_request_id = hr.id
            and hra.approver_user_id = auth.uid()
            and hra.status = 'pending'
            and hra.step_code = hr.current_step_code
        )
      )
  )
);

drop policy if exists "hiring_request_audit_log_select_scoped" on public.hiring_request_audit_log;
create policy "hiring_request_audit_log_select_scoped"
on public.hiring_request_audit_log
for select
to authenticated
using (
  public.user_is_admin(auth.uid())
  or exists (
    select 1
    from public.hiring_requests hr
    where hr.id = hiring_request_id
      and (
        hr.requester_id = auth.uid()
        or exists (
          select 1
          from public.hiring_request_approvals hra
          where hra.hiring_request_id = hr.id
            and hra.approver_user_id = auth.uid()
            and hra.status = 'pending'
            and hra.step_code = hr.current_step_code
        )
      )
  )
);

revoke insert, update, delete on public.hiring_requests from authenticated;
grant select on public.hiring_requests to authenticated;

revoke insert, update, delete on public.hiring_request_approvals from authenticated;
grant select on public.hiring_request_approvals to authenticated;

revoke all on public.hiring_request_snapshots from authenticated;
grant select on public.hiring_request_snapshots to authenticated;

revoke all on public.hiring_request_audit_log from authenticated;
grant select on public.hiring_request_audit_log to authenticated;

revoke all on public.cost_center_approvers from authenticated;
revoke all on public.workflow_approvers from authenticated;

create or replace function public.submit_hiring_request(
  p_contract_id bigint,
  p_job_position_id bigint,
  p_vacancies integer,
  p_requested_entry_date date,
  p_start_date date,
  p_end_date date,
  p_campamento boolean,
  p_pasajes boolean,
  p_other_benefits text,
  p_salary_offer numeric,
  p_shift_id bigint,
  p_requester_signed boolean
)
returns table (request_id uuid, folio text)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  requester_profile public.profiles%rowtype;
  contract_record public.contracts%rowtype;
  job_position_record public.job_positions%rowtype;
  shift_record public.shifts%rowtype;
  area_manager_record public.cost_center_approvers%rowtype;
  area_manager_profile public.profiles%rowtype;
  contracts_control_record public.workflow_approvers%rowtype;
  request_snapshot jsonb;
  created_request_id uuid;
  next_folio text;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_can_access_module(current_user_id, 'solicitud_contrataciones') then
    raise exception 'Sin permisos para crear solicitudes';
  end if;

  if not coalesce(p_requester_signed, false) then
    raise exception 'La solicitud debe enviarse con firma del solicitante';
  end if;

  if p_vacancies is null or p_vacancies <= 0 then
    raise exception 'La cantidad de vacantes debe ser mayor a 0';
  end if;

  if p_salary_offer is null or p_salary_offer < 0 then
    raise exception 'La renta liquida ofrecida es invalida';
  end if;

  if p_requested_entry_date is null or p_start_date is null or p_end_date is null then
    raise exception 'Faltan fechas obligatorias en la solicitud';
  end if;

  if p_end_date < p_start_date then
    raise exception 'La fecha de termino no puede ser anterior a la fecha de inicio';
  end if;

  select *
    into requester_profile
    from public.profiles
   where id = current_user_id
   for share;

  if requester_profile.id is null then
    raise exception 'No existe perfil para el usuario autenticado';
  end if;

  select *
    into contract_record
    from public.contracts
   where id = p_contract_id
     and is_active = true
   for share;

  if contract_record.id is null then
    raise exception 'Contrato invalido o inactivo';
  end if;

  select *
    into job_position_record
    from public.job_positions
   where id = p_job_position_id
     and is_active = true
   for share;

  if job_position_record.id is null then
    raise exception 'Cargo invalido o inactivo';
  end if;

  select *
    into shift_record
    from public.shifts
   where id = p_shift_id
     and is_active = true
   for share;

  if shift_record.id is null then
    raise exception 'Turno invalido o inactivo';
  end if;

  select *
    into area_manager_record
    from public.cost_center_approvers
   where cost_center_code = contract_record.cost_center_code
     and is_active = true
   for share;

  if area_manager_record.id is null then
    raise exception 'No existe gerente configurado para el centro de costo del contrato';
  end if;

  if area_manager_record.approver_user_id is null then
    raise exception 'El gerente del centro de costo aun no tiene usuario vinculado en la plataforma';
  end if;

  select *
    into area_manager_profile
    from public.profiles
   where id = area_manager_record.approver_user_id
     and status = 'active'
   for share;

  if area_manager_profile.id is null then
    raise exception 'El gerente del centro de costo no tiene una cuenta activa';
  end if;

  select *
    into contracts_control_record
    from public.workflow_approvers
   where step_code = 'contracts_control'
     and is_active = true
   for share;

  if contracts_control_record.step_code is null then
    raise exception 'No existe aprobador configurado para Control de Contratos';
  end if;

  if contracts_control_record.approver_user_id is null then
    raise exception 'Control de Contratos aun no tiene usuario vinculado en la plataforma';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = contracts_control_record.approver_user_id
      and p.status = 'active'
  ) then
    raise exception 'El usuario configurado para Control de Contratos no tiene una cuenta activa';
  end if;

  next_folio := lpad(nextval('public.hiring_folio_seq')::text, 4, '0');

  insert into public.hiring_requests (
    folio,
    requester_id,
    requester_name,
    requester_job_title,
    requester_email,
    requested_entry_date,
    job_position_id,
    job_position_name,
    vacancies,
    contract_id,
    contract_name,
    contract_number,
    cost_unit,
    cost_unit_name,
    cost_center_code,
    cost_center_name,
    start_date,
    end_date,
    campamento,
    pasajes,
    other_benefits,
    salary_offer,
    shift_id,
    shift_name,
    requester_signed,
    status,
    current_step_code,
    submitted_at,
    submitted_by,
    created_at,
    updated_at
  )
  values (
    next_folio,
    current_user_id,
    coalesce(requester_profile.full_name, requester_profile.email),
    requester_profile.job_title,
    requester_profile.email,
    p_requested_entry_date,
    job_position_record.id,
    job_position_record.name,
    p_vacancies,
    contract_record.id,
    contract_record.contract_name,
    contract_record.contract_number,
    contract_record.cost_unit,
    contract_record.cost_unit_name,
    contract_record.cost_center_code,
    contract_record.cost_center_name,
    p_start_date,
    p_end_date,
    coalesce(p_campamento, false),
    coalesce(p_pasajes, false),
    nullif(trim(coalesce(p_other_benefits, '')), ''),
    p_salary_offer,
    shift_record.id,
    shift_record.name,
    true,
    'pending_area_manager',
    'area_manager',
    timezone('utc', now()),
    current_user_id,
    timezone('utc', now()),
    timezone('utc', now())
  )
  returning id into created_request_id;

  request_snapshot := jsonb_build_object(
    'folio', next_folio,
    'requester_id', current_user_id,
    'requester_name', coalesce(requester_profile.full_name, requester_profile.email),
    'requester_job_title', requester_profile.job_title,
    'requester_email', requester_profile.email,
    'requested_entry_date', p_requested_entry_date,
    'job_position_id', job_position_record.id,
    'job_position_name', job_position_record.name,
    'vacancies', p_vacancies,
    'contract_id', contract_record.id,
    'contract_name', contract_record.contract_name,
    'contract_number', contract_record.contract_number,
    'cost_unit', contract_record.cost_unit,
    'cost_unit_name', contract_record.cost_unit_name,
    'cost_center_code', contract_record.cost_center_code,
    'cost_center_name', contract_record.cost_center_name,
    'start_date', p_start_date,
    'end_date', p_end_date,
    'campamento', coalesce(p_campamento, false),
    'pasajes', coalesce(p_pasajes, false),
    'other_benefits', nullif(trim(coalesce(p_other_benefits, '')), ''),
    'salary_offer', p_salary_offer,
    'shift_id', shift_record.id,
    'shift_name', shift_record.name,
    'requester_signed', true
  );

  insert into public.hiring_request_snapshots (
    hiring_request_id,
    snapshot_type,
    payload,
    created_by
  )
  values (
    created_request_id,
    'submitted',
    request_snapshot,
    current_user_id
  );

  insert into public.hiring_request_approvals (
    hiring_request_id,
    step_code,
    step_name,
    step_order,
    approver_user_id,
    approver_name,
    approver_email,
    status,
    decision_by,
    decision_comment,
    decided_at,
    locked_at,
    created_at,
    updated_at
  )
  values (
    created_request_id,
    'requester_signature',
    'Firma solicitante',
    1,
    current_user_id,
    coalesce(requester_profile.full_name, requester_profile.email),
    requester_profile.email,
    'approved',
    current_user_id,
    null,
    timezone('utc', now()),
    timezone('utc', now()),
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (hiring_request_id, step_code) do nothing;

  insert into public.hiring_request_approvals (
    hiring_request_id,
    step_code,
    step_name,
    step_order,
    approver_user_id,
    approver_name,
    approver_email,
    status,
    created_at,
    updated_at
  )
  values (
    created_request_id,
    'area_manager',
    'Gerente de area',
    2,
    area_manager_record.approver_user_id,
    area_manager_record.approver_name,
    coalesce(area_manager_record.approver_email, area_manager_profile.email),
    'pending',
    timezone('utc', now()),
    timezone('utc', now())
  );

  insert into public.hiring_request_audit_log (
    hiring_request_id,
    actor_user_id,
    action_type,
    new_values,
    metadata
  )
  values (
    created_request_id,
    current_user_id,
    'submitted',
    request_snapshot,
    jsonb_build_object(
      'current_step_code', 'area_manager',
      'status', 'pending_area_manager'
    )
  );

  insert into public.hiring_request_audit_log (
    hiring_request_id,
    approval_id,
    actor_user_id,
    action_type,
    new_values,
    metadata
  )
  select
    created_request_id,
    hra.id,
    current_user_id,
    'approval_created',
    jsonb_build_object(
      'step_code', hra.step_code,
      'step_name', hra.step_name,
      'approver_user_id', hra.approver_user_id,
      'approver_name', hra.approver_name,
      'approver_email', hra.approver_email,
      'status', hra.status
    ),
    jsonb_build_object('created_by_flow', 'submit_hiring_request')
  from public.hiring_request_approvals hra
  where hra.hiring_request_id = created_request_id
    and hra.step_code = 'area_manager';

  return query
  select created_request_id, next_folio;
end;
$$;

create or replace function public.decide_hiring_request_approval_v2(
  p_approval_id bigint,
  p_decision text,
  p_comment text default null
)
returns table (
  hiring_request_id uuid,
  request_status text,
  decided_step text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  approval_record public.hiring_request_approvals%rowtype;
  request_record public.hiring_requests%rowtype;
  contracts_control_record public.workflow_approvers%rowtype;
  next_approval_id bigint;
  normalized_comment text := nullif(trim(coalesce(p_comment, '')), '');
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if p_decision not in ('approved', 'rejected') then
    raise exception 'Decision invalida';
  end if;

  select *
    into approval_record
    from public.hiring_request_approvals
   where id = p_approval_id
   for update;

  if approval_record.id is null then
    raise exception 'No existe la aprobacion solicitada';
  end if;

  if approval_record.status <> 'pending' then
    raise exception 'La aprobacion ya fue resuelta y no puede volver a decidirse';
  end if;

  if approval_record.step_code not in ('area_manager', 'contracts_control') then
    raise exception 'La etapa indicada no admite decision por esta via';
  end if;

  if approval_record.approver_user_id is null or approval_record.approver_user_id <> current_user_id then
    raise exception 'El usuario no esta autorizado para decidir esta aprobacion';
  end if;

  select *
    into request_record
    from public.hiring_requests
   where id = approval_record.hiring_request_id
   for update;

  if request_record.id is null then
    raise exception 'No existe la solicitud asociada a la aprobacion';
  end if;

  if request_record.current_step_code is distinct from approval_record.step_code then
    raise exception 'La solicitud no se encuentra en la etapa actual de esta aprobacion';
  end if;

  if approval_record.step_code = 'area_manager'
     and request_record.status <> 'pending_area_manager' then
    raise exception 'La solicitud no esta pendiente de Gerente de Area';
  end if;

  if approval_record.step_code = 'contracts_control'
     and request_record.status <> 'pending_contracts_control' then
    raise exception 'La solicitud no esta pendiente de Control de Contratos';
  end if;

  update public.hiring_request_approvals
     set status = p_decision,
         decision_by = current_user_id,
         decision_comment = normalized_comment,
         decided_at = timezone('utc', now()),
         locked_at = timezone('utc', now()),
         updated_at = timezone('utc', now())
   where id = approval_record.id
     and status = 'pending';

  if p_decision = 'rejected' then
    update public.hiring_requests
       set status = 'rejected',
           current_step_code = null,
           rejected_at = timezone('utc', now()),
           final_decided_by = current_user_id,
           updated_at = timezone('utc', now())
     where id = request_record.id;

    insert into public.hiring_request_audit_log (
      hiring_request_id,
      approval_id,
      actor_user_id,
      action_type,
      old_values,
      new_values,
      metadata
    )
    values (
      request_record.id,
      approval_record.id,
      current_user_id,
      'rejected',
      jsonb_build_object(
        'request_status', request_record.status,
        'current_step_code', request_record.current_step_code,
        'approval_status', approval_record.status
      ),
      jsonb_build_object(
        'request_status', 'rejected',
        'current_step_code', null,
        'approval_status', 'rejected'
      ),
      jsonb_build_object(
        'step_code', approval_record.step_code,
        'comment', normalized_comment
      )
    );

    return query
    select request_record.id, 'rejected'::text, approval_record.step_code;
    return;
  end if;

  if approval_record.step_code = 'area_manager' then
    select *
      into contracts_control_record
      from public.workflow_approvers
     where step_code = 'contracts_control'
       and is_active = true
     for share;

    if contracts_control_record.step_code is null then
      raise exception 'No existe aprobador configurado para Control de Contratos';
    end if;

    if contracts_control_record.approver_user_id is null then
      raise exception 'Control de Contratos aun no tiene usuario vinculado en la plataforma';
    end if;

    if exists (
      select 1
      from public.hiring_request_approvals
      where hiring_request_id = request_record.id
        and step_code = 'contracts_control'
    ) then
      raise exception 'La aprobacion de Control de Contratos ya existe para esta solicitud';
    end if;

    insert into public.hiring_request_approvals (
      hiring_request_id,
      step_code,
      step_name,
      step_order,
      approver_user_id,
      approver_name,
      approver_email,
      status,
      created_at,
      updated_at
    )
    values (
      request_record.id,
      'contracts_control',
      'Control de contratos',
      3,
      contracts_control_record.approver_user_id,
      contracts_control_record.approver_name,
      contracts_control_record.approver_email,
      'pending',
      timezone('utc', now()),
      timezone('utc', now())
    )
    returning id into next_approval_id;

    update public.hiring_requests
       set status = 'pending_contracts_control',
           current_step_code = 'contracts_control',
           updated_at = timezone('utc', now())
     where id = request_record.id;

    insert into public.hiring_request_audit_log (
      hiring_request_id,
      approval_id,
      actor_user_id,
      action_type,
      old_values,
      new_values,
      metadata
    )
    values (
      request_record.id,
      approval_record.id,
      current_user_id,
      'approved',
      jsonb_build_object(
        'request_status', request_record.status,
        'current_step_code', request_record.current_step_code,
        'approval_status', approval_record.status
      ),
      jsonb_build_object(
        'request_status', 'pending_contracts_control',
        'current_step_code', 'contracts_control',
        'approval_status', 'approved'
      ),
      jsonb_build_object(
        'step_code', approval_record.step_code,
        'comment', normalized_comment
      )
    );

    insert into public.hiring_request_audit_log (
      hiring_request_id,
      approval_id,
      actor_user_id,
      action_type,
      new_values,
      metadata
    )
    values (
      request_record.id,
      next_approval_id,
      current_user_id,
      'approval_created',
      jsonb_build_object(
        'step_code', 'contracts_control',
        'step_name', 'Control de contratos',
        'approver_user_id', contracts_control_record.approver_user_id,
        'approver_name', contracts_control_record.approver_name,
        'approver_email', contracts_control_record.approver_email,
        'status', 'pending'
      ),
      jsonb_build_object('created_by_flow', 'decide_hiring_request_approval_v2')
    );

    return query
    select request_record.id, 'pending_contracts_control'::text, approval_record.step_code;
    return;
  end if;

  update public.hiring_requests
     set status = 'approved',
         current_step_code = null,
         approved_at = timezone('utc', now()),
         final_decided_by = current_user_id,
         updated_at = timezone('utc', now())
   where id = request_record.id;

  insert into public.hiring_request_audit_log (
    hiring_request_id,
    approval_id,
    actor_user_id,
    action_type,
    old_values,
    new_values,
    metadata
  )
  values (
    request_record.id,
    approval_record.id,
    current_user_id,
    'approved',
    jsonb_build_object(
      'request_status', request_record.status,
      'current_step_code', request_record.current_step_code,
      'approval_status', approval_record.status
    ),
    jsonb_build_object(
      'request_status', 'approved',
      'current_step_code', null,
      'approval_status', 'approved'
    ),
    jsonb_build_object(
      'step_code', approval_record.step_code,
      'comment', normalized_comment
    )
  );

  return query
  select request_record.id, 'approved'::text, approval_record.step_code;
end;
$$;

revoke execute on function public.create_hiring_request(
  date,
  bigint,
  text,
  integer,
  bigint,
  text,
  text,
  text,
  text,
  text,
  text,
  date,
  date,
  boolean,
  boolean,
  text,
  numeric,
  bigint,
  text,
  boolean
) from authenticated;

revoke execute on function public.create_hiring_request_v2(
  boolean,
  bigint,
  text,
  text,
  text,
  text,
  text,
  text,
  date,
  bigint,
  text,
  text,
  boolean,
  date,
  boolean,
  numeric,
  bigint,
  text,
  date,
  integer
) from authenticated;

revoke execute on function public.decide_hiring_request_approval(
  bigint,
  text,
  text
) from authenticated;

grant execute on function public.submit_hiring_request(
  bigint,
  bigint,
  integer,
  date,
  date,
  date,
  boolean,
  boolean,
  text,
  numeric,
  bigint,
  boolean
) to authenticated;

grant execute on function public.decide_hiring_request_approval_v2(
  bigint,
  text,
  text
) to authenticated;

insert into public.cost_center_approvers (
  cost_center_code,
  cost_center_name,
  approver_user_id,
  approver_name,
  approver_email,
  is_active
)
values
  (
    '10115',
    'CONTROL FLOTA',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Juan Carlos Navea') order by p.updated_at desc limit 1),
    'Juan Carlos Navea',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Juan Carlos Navea') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10102',
    'GERENCIA COMERCIAL',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Alan Brain Biggemann') order by p.updated_at desc limit 1),
    'Alan Brain Biggemann',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Alan Brain Biggemann') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10104',
    'GERENCIA FINANZAS',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Raul Lopez Guerra') order by p.updated_at desc limit 1),
    'Raul Lopez Guerra',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Raul Lopez Guerra') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10100',
    'GERENCIA GENERAL',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Guillermo Zanartu Apara') order by p.updated_at desc limit 1),
    'Guillermo Zanartu Apara',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Guillermo Zanartu Apara') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10106',
    'GERENCIA MANTENIMIENTO',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Rodrigo Galdames') order by p.updated_at desc limit 1),
    'Rodrigo Galdames',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Rodrigo Galdames') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10113',
    'GERENCIA OPERACIONES ZONA I (CENTRO)',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Cristian Jimenez Jimenez') order by p.updated_at desc limit 1),
    'Cristian Jimenez Jimenez',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Cristian Jimenez Jimenez') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10114',
    'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Maximiliano Contreras Rey') order by p.updated_at desc limit 1),
    'Maximiliano Contreras Rey',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Maximiliano Contreras Rey') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10116',
    'GERENCIA OPERACIONES ZONA III (NORTE COSTA)',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Luciano Fischer Ballerini') order by p.updated_at desc limit 1),
    'Luciano Fischer Ballerini',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Luciano Fischer Ballerini') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10110',
    'GERENCIA PREVENCION DE RIESGOS',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Manuel Parra Soto') order by p.updated_at desc limit 1),
    'Manuel Parra Soto',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Manuel Parra Soto') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10111',
    'GERENCIA RECURSOS HUMANOS',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Andres Madrid Maureira') order by p.updated_at desc limit 1),
    'Andres Madrid Maureira',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Andres Madrid Maureira') order by p.updated_at desc limit 1),
    true
  ),
  (
    '10112',
    'SOCIOS',
    (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Gerardo Casanova Minardi') order by p.updated_at desc limit 1),
    'Gerardo Casanova Minardi',
    (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Gerardo Casanova Minardi') order by p.updated_at desc limit 1),
    true
  )
on conflict (cost_center_code) do update
set
  cost_center_name = excluded.cost_center_name,
  approver_user_id = excluded.approver_user_id,
  approver_name = excluded.approver_name,
  approver_email = excluded.approver_email,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

insert into public.workflow_approvers (
  step_code,
  approver_user_id,
  approver_name,
  approver_email,
  is_active
)
values (
  'contracts_control',
  (select p.id from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Maria Jesus Lagos Minardi') order by p.updated_at desc limit 1),
  'Maria Jesus Lagos Minardi',
  (select p.email from public.profiles p where lower(trim(coalesce(p.full_name, ''))) = lower('Maria Jesus Lagos Minardi') order by p.updated_at desc limit 1),
  true
)
on conflict (step_code) do update
set
  approver_user_id = excluded.approver_user_id,
  approver_name = excluded.approver_name,
  approver_email = excluded.approver_email,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());

commit;
