begin;

create table if not exists public.candidate_stage_approvals (
  id bigint generated by default as identity primary key,
  recruitment_case_candidate_id uuid not null references public.recruitment_case_candidates (id) on delete cascade,
  stage_code text not null,
  status text not null,
  requested_by uuid not null references public.profiles (id) on delete restrict,
  requested_at timestamptz not null default timezone('utc', now()),
  approved_by uuid references public.profiles (id) on delete set null,
  approved_at timestamptz,
  comment text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint candidate_stage_approvals_stage_code_check check (stage_code in ('who_pending')),
  constraint candidate_stage_approvals_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

create index if not exists idx_candidate_stage_approvals_candidate_stage
  on public.candidate_stage_approvals (recruitment_case_candidate_id, stage_code, requested_at desc);

create unique index if not exists idx_candidate_stage_approvals_one_pending_who
  on public.candidate_stage_approvals (recruitment_case_candidate_id, stage_code)
  where status = 'pending';

drop trigger if exists trg_candidate_stage_approvals_set_updated_at on public.candidate_stage_approvals;
create trigger trg_candidate_stage_approvals_set_updated_at
before update on public.candidate_stage_approvals
for each row execute function public.set_updated_at();

alter table public.candidate_stage_approvals enable row level security;

drop policy if exists "candidate_stage_approvals_select_scoped" on public.candidate_stage_approvals;
create policy "candidate_stage_approvals_select_scoped"
on public.candidate_stage_approvals
for select
to authenticated
using (
  public.user_has_capability(auth.uid(), 'can_approve_who_stage')
  or exists (
    select 1
    from public.recruitment_case_candidates rcc
    where rcc.id = candidate_stage_approvals.recruitment_case_candidate_id
      and public.user_can_view_recruitment_case(auth.uid(), rcc.recruitment_case_id)
  )
);

revoke insert, update, delete on public.candidate_stage_approvals from authenticated;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'recruitment_case_candidates_stage_code_check'
      and conrelid = 'public.recruitment_case_candidates'::regclass
  ) then
    alter table public.recruitment_case_candidates
      drop constraint recruitment_case_candidates_stage_code_check;
  end if;

  if exists (
    select 1
    from pg_constraint
    where conname = 'recruitment_case_candidates_stage_check'
      and conrelid = 'public.recruitment_case_candidates'::regclass
  ) then
    alter table public.recruitment_case_candidates
      drop constraint recruitment_case_candidates_stage_check;
  end if;
end $$;

update public.recruitment_case_candidates
   set stage_code = case
     when stage_code = 'contacted' then 'lead'
     when stage_code = 'screening' then 'who_pending'
     when stage_code = 'shortlisted' then 'who_approved'
     when stage_code = 'documents_pending' then 'document_review'
     else stage_code
   end,
       updated_at = timezone('utc', now())
 where stage_code in ('contacted', 'screening', 'shortlisted', 'documents_pending');

update public.recruitment_case_candidate_stage_history
   set from_stage = case
         when from_stage = 'contacted' then 'lead'
         when from_stage = 'screening' then 'who_pending'
         when from_stage = 'shortlisted' then 'who_approved'
         when from_stage = 'documents_pending' then 'document_review'
         else from_stage
       end,
       to_stage = case
         when to_stage = 'contacted' then 'lead'
         when to_stage = 'screening' then 'who_pending'
         when to_stage = 'shortlisted' then 'who_approved'
         when to_stage = 'documents_pending' then 'document_review'
         else to_stage
       end
 where from_stage in ('contacted', 'screening', 'shortlisted', 'documents_pending')
    or to_stage in ('contacted', 'screening', 'shortlisted', 'documents_pending');

insert into public.candidate_stage_approvals (
  recruitment_case_candidate_id,
  stage_code,
  status,
  requested_by,
  requested_at,
  comment,
  created_at,
  updated_at
)
select
  rcc.id,
  'who_pending',
  'pending',
  coalesce(rcc.created_by, rc.opened_by),
  coalesce(rcc.stage_entered_at, rcc.updated_at, rcc.created_at, timezone('utc', now())),
  null,
  timezone('utc', now()),
  timezone('utc', now())
from public.recruitment_case_candidates rcc
join public.recruitment_cases rc
  on rc.id = rcc.recruitment_case_id
left join public.candidate_stage_approvals csa
  on csa.recruitment_case_candidate_id = rcc.id
 and csa.stage_code = 'who_pending'
 and csa.status = 'pending'
where rcc.stage_code = 'who_pending'
  and csa.id is null;

alter table public.recruitment_case_candidates
  add constraint recruitment_case_candidates_stage_code_check
  check (
    stage_code in (
      'lead',
      'who_pending',
      'who_approved',
      'medical_exams',
      'document_review',
      'ready_for_hire',
      'hired',
      'rejected',
      'withdrawn'
    )
  );

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'recruitment_case_audit_log_action_type_check'
      and conrelid = 'public.recruitment_case_audit_log'::regclass
  ) then
    alter table public.recruitment_case_audit_log
      drop constraint recruitment_case_audit_log_action_type_check;
  end if;

  alter table public.recruitment_case_audit_log
    add constraint recruitment_case_audit_log_action_type_check
    check (
      action_type in (
        'case_opened',
        'owner_assigned',
        'candidate_added',
        'candidate_stage_changed',
        'candidate_hired',
        'case_status_synced',
        'candidate_stage_approval_requested',
        'candidate_stage_approval_approved'
      )
    );
end $$;

create or replace function public.advance_recruitment_candidate_stage(
  p_case_candidate_id uuid,
  p_to_stage text,
  p_comment text default null
)
returns table (
  recruitment_case_id uuid,
  stage_code text,
  case_status text
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  candidate_record public.recruitment_case_candidates%rowtype;
  normalized_comment text := nullif(trim(coalesce(p_comment, '')), '');
  next_case_status text;
  conflicting_contract_lock record;
  who_approval_id bigint;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if p_to_stage not in (
    'lead',
    'who_pending',
    'who_approved',
    'medical_exams',
    'document_review',
    'ready_for_hire',
    'hired',
    'rejected',
    'withdrawn'
  ) then
    raise exception 'Etapa invalida';
  end if;

  select *
    into candidate_record
    from public.recruitment_case_candidates rcc
   where rcc.id = p_case_candidate_id
   for update;

  if candidate_record.id is null then
    raise exception 'No existe el candidato del caso';
  end if;

  if not public.user_can_manage_recruitment_case(current_user_id, candidate_record.recruitment_case_id) then
    raise exception 'Sin permisos para actualizar este candidato';
  end if;

  if candidate_record.stage_code in ('hired', 'rejected', 'withdrawn') then
    raise exception 'El candidato ya se encuentra en una etapa terminal';
  end if;

  if candidate_record.stage_code = p_to_stage then
    raise exception 'El candidato ya se encuentra en esa etapa';
  end if;

  if candidate_record.stage_code = 'lead'
     and p_to_stage not in ('who_pending', 'rejected', 'withdrawn') then
    raise exception 'Desde Lead solo se puede avanzar a Who Pendiente, Rechazado o Retirado';
  end if;

  if p_to_stage = 'who_approved' then
    raise exception 'La etapa Who Aprobado solo puede resolverse mediante la aprobación formal de antecedentes';
  end if;

  if candidate_record.stage_code = 'who_pending'
     and p_to_stage not in ('rejected', 'withdrawn') then
    raise exception 'El candidato requiere aprobación Who antes de avanzar';
  end if;

  if candidate_record.stage_code = 'who_approved'
     and p_to_stage not in ('medical_exams', 'rejected', 'withdrawn') then
    raise exception 'Desde Who Aprobado solo se puede avanzar a Exámenes Médicos, Rechazado o Retirado';
  end if;

  if candidate_record.stage_code = 'medical_exams'
     and p_to_stage not in ('document_review', 'rejected', 'withdrawn') then
    raise exception 'Desde Exámenes Médicos solo se puede avanzar a Revisión Documental, Rechazado o Retirado';
  end if;

  if candidate_record.stage_code = 'document_review'
     and p_to_stage not in ('ready_for_hire', 'rejected', 'withdrawn') then
    raise exception 'Desde Revisión Documental solo se puede avanzar a Listo para Contratar, Rechazado o Retirado';
  end if;

  if candidate_record.stage_code = 'ready_for_hire'
     and p_to_stage not in ('hired', 'rejected', 'withdrawn') then
    raise exception 'Desde Listo para Contratar solo se puede avanzar a Contratado, Rechazado o Retirado';
  end if;

  if p_to_stage = 'medical_exams' then
    if candidate_record.stage_code <> 'who_approved' then
      raise exception 'El candidato debe pasar por Who Aprobado antes de Exámenes Médicos';
    end if;

    if not exists (
      select 1
      from public.candidate_stage_approvals csa
      where csa.recruitment_case_candidate_id = candidate_record.id
        and csa.stage_code = 'who_pending'
        and csa.status = 'approved'
    ) then
      raise exception 'No existe aprobación Who registrada para este candidato';
    end if;
  end if;

  if p_to_stage in ('ready_for_hire', 'hired') then
    select *
      into conflicting_contract_lock
      from public.find_active_candidate_contract_lock(
        candidate_record.candidate_profile_id,
        candidate_record.id
      );

    if conflicting_contract_lock.case_candidate_id is not null then
      raise exception
        'El candidato ya avanza a contrato en % (%)',
        coalesce(conflicting_contract_lock.case_code, 'otro folio'),
        coalesce(conflicting_contract_lock.folio, 'sin folio');
    end if;
  end if;

  update public.recruitment_case_candidates rcc
     set stage_code = p_to_stage,
         stage_entered_at = timezone('utc', now()),
         is_selected = case
           when p_to_stage in ('ready_for_hire', 'hired') then true
           when p_to_stage in ('rejected', 'withdrawn') then false
           else rcc.is_selected
         end,
         hired_at = case
           when p_to_stage = 'hired' then timezone('utc', now())
           else rcc.hired_at
         end,
         rejection_reason = case when p_to_stage = 'rejected' then normalized_comment else rcc.rejection_reason end,
         withdrawal_reason = case when p_to_stage = 'withdrawn' then normalized_comment else rcc.withdrawal_reason end,
         suitability_status = case
           when p_to_stage in ('ready_for_hire', 'hired') then 'fit'
           when p_to_stage in ('rejected', 'withdrawn') then 'blocked'
           else rcc.suitability_status
         end,
         updated_at = timezone('utc', now())
   where rcc.id = p_case_candidate_id;

  if p_to_stage = 'who_pending' then
    update public.candidate_stage_approvals csa
       set status = 'cancelled',
           updated_at = timezone('utc', now())
     where csa.recruitment_case_candidate_id = candidate_record.id
       and csa.stage_code = 'who_pending'
       and csa.status = 'pending';

    insert into public.candidate_stage_approvals (
      recruitment_case_candidate_id,
      stage_code,
      status,
      requested_by,
      requested_at,
      comment,
      created_at,
      updated_at
    )
    values (
      candidate_record.id,
      'who_pending',
      'pending',
      current_user_id,
      timezone('utc', now()),
      normalized_comment,
      timezone('utc', now()),
      timezone('utc', now())
    )
    returning id into who_approval_id;

    insert into public.recruitment_case_audit_log (
      recruitment_case_id,
      recruitment_case_candidate_id,
      actor_user_id,
      action_type,
      old_values,
      new_values,
      metadata
    )
    values (
      candidate_record.recruitment_case_id,
      candidate_record.id,
      current_user_id,
      'candidate_stage_approval_requested',
      null,
      jsonb_build_object(
        'approval_id', who_approval_id,
        'stage_code', 'who_pending',
        'status', 'pending'
      ),
      jsonb_build_object('comment', normalized_comment)
    );
  end if;

  insert into public.recruitment_case_candidate_stage_history (
    recruitment_case_candidate_id,
    from_stage,
    to_stage,
    changed_by,
    reason_code,
    comment
  )
  values (
    p_case_candidate_id,
    candidate_record.stage_code,
    p_to_stage,
    current_user_id,
    case when p_to_stage = 'who_pending' then 'who_requested' else 'manual_transition' end,
    normalized_comment
  );

  insert into public.recruitment_case_audit_log (
    recruitment_case_id,
    recruitment_case_candidate_id,
    actor_user_id,
    action_type,
    old_values,
    new_values,
    metadata
  )
  values (
    candidate_record.recruitment_case_id,
    candidate_record.id,
    current_user_id,
    case when p_to_stage = 'hired' then 'candidate_hired' else 'candidate_stage_changed' end,
    jsonb_build_object(
      'stage_code', candidate_record.stage_code,
      'is_selected', candidate_record.is_selected,
      'hired_at', candidate_record.hired_at
    ),
    jsonb_build_object(
      'stage_code', p_to_stage,
      'is_selected', case
        when p_to_stage in ('ready_for_hire', 'hired') then true
        when p_to_stage in ('rejected', 'withdrawn') then false
        else candidate_record.is_selected
      end,
      'hired_at', case
        when p_to_stage = 'hired' then timezone('utc', now())
        else candidate_record.hired_at
      end
    ),
    jsonb_build_object('comment', normalized_comment)
  );

  next_case_status := public.sync_recruitment_case_status(candidate_record.recruitment_case_id, current_user_id);

  return query
  select candidate_record.recruitment_case_id, p_to_stage, next_case_status;
end;
$function$;

create or replace function public.approve_candidate_stage_who(
  p_case_candidate_id uuid,
  p_comment text default null
)
returns table (
  recruitment_case_id uuid,
  stage_code text,
  case_status text
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  candidate_record public.recruitment_case_candidates%rowtype;
  approval_record public.candidate_stage_approvals%rowtype;
  normalized_comment text := nullif(trim(coalesce(p_comment, '')), '');
  next_case_status text;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_has_capability(current_user_id, 'can_approve_who_stage') then
    raise exception 'Sin permisos para aprobar etapa Who';
  end if;

  select *
    into candidate_record
    from public.recruitment_case_candidates rcc
   where rcc.id = p_case_candidate_id
   for update;

  if candidate_record.id is null then
    raise exception 'No existe el candidato del caso';
  end if;

  if candidate_record.stage_code <> 'who_pending' then
    raise exception 'El candidato no se encuentra pendiente de aprobación Who';
  end if;

  select *
    into approval_record
    from public.candidate_stage_approvals csa
   where csa.recruitment_case_candidate_id = candidate_record.id
     and csa.stage_code = 'who_pending'
     and csa.status = 'pending'
   order by csa.requested_at desc, csa.id desc
   limit 1
   for update;

  if approval_record.id is null then
    raise exception 'No existe una aprobación Who pendiente para este candidato';
  end if;

  update public.candidate_stage_approvals csa
     set status = 'approved',
         approved_by = current_user_id,
         approved_at = timezone('utc', now()),
         comment = coalesce(normalized_comment, csa.comment),
         updated_at = timezone('utc', now())
   where csa.id = approval_record.id;

  update public.recruitment_case_candidates rcc
     set stage_code = 'who_approved',
         stage_entered_at = timezone('utc', now()),
         updated_at = timezone('utc', now())
   where rcc.id = candidate_record.id;

  insert into public.recruitment_case_candidate_stage_history (
    recruitment_case_candidate_id,
    from_stage,
    to_stage,
    changed_by,
    reason_code,
    comment
  )
  values (
    candidate_record.id,
    'who_pending',
    'who_approved',
    current_user_id,
    'who_approved',
    normalized_comment
  );

  insert into public.recruitment_case_audit_log (
    recruitment_case_id,
    recruitment_case_candidate_id,
    actor_user_id,
    action_type,
    old_values,
    new_values,
    metadata
  )
  values (
    candidate_record.recruitment_case_id,
    candidate_record.id,
    current_user_id,
    'candidate_stage_approval_approved',
    jsonb_build_object(
      'approval_id', approval_record.id,
      'status', 'pending',
      'stage_code', 'who_pending'
    ),
    jsonb_build_object(
      'approval_id', approval_record.id,
      'status', 'approved',
      'stage_code', 'who_pending',
      'approved_at', timezone('utc', now())
    ),
    jsonb_build_object('comment', normalized_comment)
  );

  next_case_status := public.sync_recruitment_case_status(candidate_record.recruitment_case_id, current_user_id);

  return query
  select candidate_record.recruitment_case_id, 'who_approved'::text, next_case_status;
end;
$function$;

create or replace function public.get_recruitment_case_detail(
  p_case_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  case_payload jsonb;
  assignments_payload jsonb := '[]'::jsonb;
  candidates_payload jsonb := '[]'::jsonb;
  audit_payload jsonb := '[]'::jsonb;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_can_view_recruitment_case(current_user_id, p_case_id) then
    raise exception 'Sin permisos para ver este caso';
  end if;

  select jsonb_build_object(
    'id', rc.id,
    'case_code', rc.case_code,
    'status', rc.status,
    'requested_vacancies', rc.requested_vacancies,
    'filled_vacancies', rc.filled_vacancies,
    'title', rc.title,
    'contract_name', rc.contract_name,
    'job_position_name', rc.job_position_name,
    'cost_center_code', rc.cost_center_code,
    'cost_center_name', rc.cost_center_name,
    'requested_entry_date', rc.requested_entry_date,
    'target_close_date', rc.target_close_date,
    'opened_at', rc.opened_at,
    'close_reason', rc.close_reason,
    'hiring_request', jsonb_build_object(
      'id', hr.id,
      'folio', hr.folio,
      'requester_name', hr.requester_name,
      'requester_email', hr.requester_email,
      'start_date', hr.start_date,
      'end_date', hr.end_date,
      'shift_name', hr.shift_name,
      'salary_offer', hr.salary_offer,
      'campamento', hr.campamento,
      'pasajes', hr.pasajes,
      'other_benefits', hr.other_benefits,
      'approval_summary', case
        when latest_approval.id is null then null
        else jsonb_build_object(
          'step_name', latest_approval.step_name,
          'status', latest_approval.status,
          'decision_comment', latest_approval.decision_comment,
          'decided_at', latest_approval.decided_at,
          'decided_by_name', latest_approval.decided_by_name
        )
      end
    )
  )
  into case_payload
  from public.recruitment_cases rc
  join public.hiring_requests hr
    on hr.id = rc.hiring_request_id
  left join lateral (
    select
      hra.id,
      hra.step_name,
      hra.status,
      hra.decision_comment,
      hra.decided_at,
      decision_profile.full_name as decided_by_name
    from public.hiring_request_approvals hra
    left join public.profiles decision_profile
      on decision_profile.id = hra.decision_by
    where hra.hiring_request_id = hr.id
      and hra.status in ('approved', 'rejected')
    order by coalesce(hra.decided_at, hra.updated_at, hra.created_at) desc, hra.id desc
    limit 1
  ) latest_approval on true
  where rc.id = p_case_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', rca.id,
        'user_id', rca.user_id,
        'assignment_role', rca.assignment_role,
        'is_primary', rca.is_primary,
        'assigned_at', rca.assigned_at,
        'full_name', p.full_name,
        'email', p.email
      )
      order by rca.is_primary desc, rca.id asc
    ),
    '[]'::jsonb
  )
  into assignments_payload
  from public.recruitment_case_assignments rca
  join public.profiles p
    on p.id = rca.user_id
  where rca.recruitment_case_id = p_case_id;

  select coalesce(
    jsonb_agg(candidate_row.payload order by candidate_row.sort_created_at asc),
    '[]'::jsonb
  )
  into candidates_payload
  from (
    select
      jsonb_build_object(
        'id', rcc.id,
        'candidate_profile_id', cp.id,
        'national_id', cp.national_id,
        'full_name', cp.full_name,
        'email', cp.email,
        'phone', cp.phone,
        'driver_license_number', cp.driver_license_number,
        'driver_license_class', cp.driver_license_class,
        'driver_license_expiry', cp.driver_license_expiry,
        'interview_notes', rcc.interview_notes,
        'stage_code', rcc.stage_code,
        'stage_entered_at', rcc.stage_entered_at,
        'suitability_status', rcc.suitability_status,
        'is_selected', rcc.is_selected,
        'hired_at', rcc.hired_at,
        'created_at', rcc.created_at,
        'who_approval', (
          select jsonb_build_object(
            'id', csa.id,
            'status', csa.status,
            'requested_by', csa.requested_by,
            'requested_by_name', requested_profile.full_name,
            'requested_at', csa.requested_at,
            'approved_by', csa.approved_by,
            'approved_by_name', approved_profile.full_name,
            'approved_at', csa.approved_at,
            'comment', csa.comment
          )
          from public.candidate_stage_approvals csa
          left join public.profiles requested_profile
            on requested_profile.id = csa.requested_by
          left join public.profiles approved_profile
            on approved_profile.id = csa.approved_by
          where csa.recruitment_case_candidate_id = rcc.id
            and csa.stage_code = 'who_pending'
          order by coalesce(csa.approved_at, csa.requested_at) desc, csa.id desc
          limit 1
        ),
        'stage_history', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'id', sh.id,
              'from_stage', sh.from_stage,
              'to_stage', sh.to_stage,
              'changed_by', sh.changed_by,
              'reason_code', sh.reason_code,
              'comment', sh.comment,
              'created_at', sh.created_at
            )
            order by sh.created_at desc
          )
          from public.recruitment_case_candidate_stage_history sh
          where sh.recruitment_case_candidate_id = rcc.id
        ), '[]'::jsonb)
      ) as payload,
      rcc.created_at as sort_created_at
    from public.recruitment_case_candidates rcc
    join public.candidate_profiles cp
      on cp.id = rcc.candidate_profile_id
    where rcc.recruitment_case_id = p_case_id
  ) as candidate_row;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', al.id,
        'action_type', al.action_type,
        'actor_user_id', al.actor_user_id,
        'actor_name', actor_profile.full_name,
        'old_values', al.old_values,
        'new_values', al.new_values,
        'metadata', al.metadata,
        'created_at', al.created_at
      )
      order by al.created_at desc
    ),
    '[]'::jsonb
  )
  into audit_payload
  from public.recruitment_case_audit_log al
  left join public.profiles actor_profile
    on actor_profile.id = al.actor_user_id
  where al.recruitment_case_id = p_case_id
  limit 40;

  return jsonb_build_object(
    'case', case_payload,
    'assignments', assignments_payload,
    'candidates', candidates_payload,
    'audit', audit_payload
  );
end;
$function$;

grant execute on function public.get_recruitment_case_detail(uuid) to authenticated;
grant execute on function public.advance_recruitment_candidate_stage(uuid, text, text) to authenticated;
grant execute on function public.approve_candidate_stage_who(uuid, text) to authenticated;

notify pgrst, 'reload schema';

commit;
