-- EEES-DB-005: approved
-- owner: Recursos Humanos / Gobierno de remuneraciones
-- rollback: forward-only; desactivar include_income_tax y restaurar el contrato RPC mediante una migración posterior.

begin;

alter table public.hr_rent_structures
  add column if not exists include_income_tax boolean not null default false;

create table if not exists public.hr_rent_utm_values (
  period_month date primary key check (period_month = date_trunc('month', period_month)::date),
  value_clp numeric(14,2) not null check (value_clp > 0),
  source_url text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.hr_rent_utm_values (period_month, value_clp, source_url)
values
  (date '2026-01-01', 69751, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-02-01', 69611, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-03-01', 69889, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-04-01', 69889, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-05-01', 70588, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-06-01', 71506, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-07-01', 71649, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-08-01', 71649, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-09-01', 71721, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm'),
  (date '2026-10-01', 72151, 'https://www.sii.cl/valores_y_fechas/utm/utm2026.htm')
on conflict (period_month) do update
set value_clp = excluded.value_clp,
    source_url = excluded.source_url,
    updated_at = timezone('utc', now());

create table if not exists public.hr_rent_iusc_brackets (
  id bigint generated by default as identity primary key,
  effective_from date not null,
  effective_to date,
  lower_bound_utm numeric(10,2) not null check (lower_bound_utm >= 0),
  upper_bound_utm numeric(10,2),
  factor numeric(8,6) not null check (factor between 0 and 1),
  rebate_utm numeric(10,2) not null check (rebate_utm >= 0),
  source_url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hr_rent_iusc_brackets_dates check (effective_to is null or effective_to >= effective_from),
  constraint hr_rent_iusc_brackets_range check (upper_bound_utm is null or upper_bound_utm > lower_bound_utm),
  unique (effective_from, lower_bound_utm)
);

insert into public.hr_rent_iusc_brackets
  (effective_from, lower_bound_utm, upper_bound_utm, factor, rebate_utm, source_url)
values
  (date '2026-01-01', 0, 13.5, 0, 0, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm'),
  (date '2026-01-01', 13.5, 30, 0.04, 0.54, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm'),
  (date '2026-01-01', 30, 50, 0.08, 1.74, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm'),
  (date '2026-01-01', 50, 70, 0.135, 4.49, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm'),
  (date '2026-01-01', 70, 90, 0.23, 11.14, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm'),
  (date '2026-01-01', 90, 120, 0.304, 17.80, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm'),
  (date '2026-01-01', 120, 310, 0.35, 23.32, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm'),
  (date '2026-01-01', 310, null, 0.40, 38.82, 'https://www.sii.cl/valores_y_fechas/impuesto_2da_categoria/impuesto2026.htm')
on conflict (effective_from, lower_bound_utm) do update
set upper_bound_utm = excluded.upper_bound_utm,
    factor = excluded.factor,
    rebate_utm = excluded.rebate_utm,
    source_url = excluded.source_url,
    is_active = true,
    updated_at = timezone('utc', now());

create index if not exists idx_hr_rent_iusc_brackets_lookup
  on public.hr_rent_iusc_brackets (effective_from desc, lower_bound_utm desc)
  where is_active;

alter table public.hr_rent_utm_values enable row level security;
alter table public.hr_rent_iusc_brackets enable row level security;

drop policy if exists hr_rent_utm_values_no_direct_access on public.hr_rent_utm_values;
create policy hr_rent_utm_values_no_direct_access on public.hr_rent_utm_values
for all to authenticated using (false) with check (false);

drop policy if exists hr_rent_iusc_brackets_no_direct_access on public.hr_rent_iusc_brackets;
create policy hr_rent_iusc_brackets_no_direct_access on public.hr_rent_iusc_brackets
for all to authenticated using (false) with check (false);

revoke all on public.hr_rent_utm_values from public, anon, authenticated;
revoke all on public.hr_rent_iusc_brackets from public, anon, authenticated;

alter function public.get_hr_rent_structure_control(bigint, bigint)
  rename to get_hr_rent_structure_control_without_iusc;

revoke all on function public.get_hr_rent_structure_control_without_iusc(bigint, bigint) from public, anon, authenticated;

create or replace function public.get_hr_rent_structure_control(
  p_contract_id bigint default null,
  p_job_position_id bigint default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare
  payload jsonb;
  structure_payload jsonb;
  include_tax boolean := false;
  social_security_discounts numeric;
  taxable_base numeric;
  utm_value numeric;
  utm_period date;
  bracket_factor numeric;
  bracket_rebate_utm numeric;
  bracket_lower_utm numeric;
  bracket_upper_utm numeric;
  income_tax numeric := 0;
  tax_available boolean := true;
  tax_line jsonb;
begin
  payload := public.get_hr_rent_structure_control_without_iusc(p_contract_id, p_job_position_id);
  structure_payload := payload -> 'structure';

  if coalesce(structure_payload ->> 'id', '') = '' then
    return payload;
  end if;

  select structure_row.include_income_tax
  into include_tax
  from public.hr_rent_structures structure_row
  where structure_row.id = (structure_payload ->> 'id')::uuid;

  social_security_discounts := nullif(structure_payload #>> '{totals,legal_discounts}', '')::numeric;
  taxable_base := case
    when social_security_discounts is null then null
    else greatest((structure_payload #>> '{totals,imponible}')::numeric - social_security_discounts, 0)
  end;

  if include_tax then
    select utm.value_clp, utm.period_month
    into utm_value, utm_period
    from public.hr_rent_utm_values utm
    where utm.period_month <= date_trunc('month', current_date)::date
    order by utm.period_month desc
    limit 1;

    if taxable_base is null or utm_value is null then
      tax_available := false;
      income_tax := null;
    elsif taxable_base = 0 then
      income_tax := 0;
    else
      select bracket.factor, bracket.rebate_utm, bracket.lower_bound_utm, bracket.upper_bound_utm
      into bracket_factor, bracket_rebate_utm, bracket_lower_utm, bracket_upper_utm
      from public.hr_rent_iusc_brackets bracket
      where bracket.is_active
        and bracket.effective_from <= current_date
        and (bracket.effective_to is null or bracket.effective_to >= current_date)
        and taxable_base / utm_value > bracket.lower_bound_utm
        and (bracket.upper_bound_utm is null or taxable_base / utm_value <= bracket.upper_bound_utm)
      order by bracket.effective_from desc, bracket.lower_bound_utm desc
      limit 1;

      if bracket_factor is null then
        tax_available := false;
        income_tax := null;
      else
        income_tax := greatest(round(taxable_base * bracket_factor - bracket_rebate_utm * utm_value, 0), 0);
      end if;
    end if;
  end if;

  structure_payload := jsonb_set(
    structure_payload,
    '{legal_scenario,include_income_tax}',
    to_jsonb(include_tax),
    true
  );
  structure_payload := jsonb_set(
    structure_payload,
    '{legal_scenario,iusc_utm_clp}',
    case when include_tax and utm_value is not null then to_jsonb(utm_value) else 'null'::jsonb end,
    true
  );
  structure_payload := jsonb_set(
    structure_payload,
    '{totals,taxable_base}',
    case when taxable_base is null then 'null'::jsonb else to_jsonb(taxable_base) end,
    true
  );
  structure_payload := jsonb_set(
    structure_payload,
    '{totals,income_tax}',
    case when income_tax is null then 'null'::jsonb else to_jsonb(income_tax) end,
    true
  );

  if include_tax then
    structure_payload := jsonb_set(
      structure_payload,
      '{calculation_available}',
      to_jsonb(coalesce((structure_payload ->> 'calculation_available')::boolean, false) and tax_available),
      true
    );

    if tax_available then
      tax_line := jsonb_build_object(
        'id', 'legal_income_tax',
        'concept_code', 'legal_income_tax',
        'concept_name', 'Impuesto Único de Segunda Categoría',
        'concept_type', 'legal_discount',
        'section_code', 'legal_discount',
        'calculation_mode', 'legal_rate',
        'amount', income_tax,
        'detail', case
          when coalesce(bracket_factor, 0) = 0 then 'Exento según tramo SII vigente'
          else concat(
            'Factor ', trim(to_char(bracket_factor * 100, 'FM990D00')), '% · rebaja ',
            trim(to_char(bracket_rebate_utm, 'FM990D00')), ' UTM'
          )
        end,
        'sort_order', 40
      );
      structure_payload := jsonb_set(
        structure_payload,
        '{lines}',
        coalesce(structure_payload -> 'lines', '[]'::jsonb) || jsonb_build_array(tax_line),
        true
      );
      structure_payload := jsonb_set(
        structure_payload,
        '{totals,legal_discounts}',
        to_jsonb(social_security_discounts + income_tax),
        true
      );
      structure_payload := jsonb_set(
        structure_payload,
        '{totals,liquido_estimated}',
        to_jsonb(greatest((structure_payload #>> '{totals,haberes}')::numeric - social_security_discounts - income_tax, 0)),
        true
      );
      structure_payload := jsonb_set(
        structure_payload,
        '{legal_assumptions}',
        coalesce(structure_payload -> 'legal_assumptions', '[]'::jsonb) || jsonb_build_array(
          concat('Impuesto único estimado con UTM ', to_char(utm_period, 'MM/YYYY'), ' de $', trim(to_char(utm_value, 'FM999G999G990')))
        ),
        true
      );
    end if;
  end if;

  return jsonb_set(payload, '{structure}', structure_payload, true);
end;
$function$;

create or replace function public.save_hr_rent_structure_config(
  p_contract_id bigint,
  p_job_position_id bigint,
  p_authorized_headcount integer,
  p_lines jsonb,
  p_afp_code text,
  p_health_mode text,
  p_health_provider_name text,
  p_health_plan_value numeric,
  p_unemployment_contract_type text,
  p_include_income_tax boolean
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  current_user_id uuid := auth.uid();
  target_structure_id uuid;
begin
  target_structure_id := public.save_hr_rent_structure_config(
    p_contract_id,
    p_job_position_id,
    p_authorized_headcount,
    p_lines,
    p_afp_code,
    p_health_mode,
    p_health_provider_name,
    p_health_plan_value,
    p_unemployment_contract_type
  );

  update public.hr_rent_structures structure_row
  set include_income_tax = coalesce(p_include_income_tax, false),
      updated_at = timezone('utc', now())
  where structure_row.id = target_structure_id;

  update public.hr_rent_structure_audit audit_row
  set snapshot = jsonb_set(
    audit_row.snapshot,
    '{legal_scenario,include_income_tax}',
    to_jsonb(coalesce(p_include_income_tax, false)),
    true
  )
  where audit_row.id = (
    select latest_audit.id
    from public.hr_rent_structure_audit latest_audit
    where latest_audit.structure_id = target_structure_id
      and latest_audit.changed_by = current_user_id
    order by latest_audit.created_at desc, latest_audit.id desc
    limit 1
  );

  return target_structure_id;
end;
$function$;

revoke all on function public.get_hr_rent_structure_control(bigint, bigint) from public, anon;
grant execute on function public.get_hr_rent_structure_control(bigint, bigint) to authenticated;
revoke all on function public.save_hr_rent_structure_config(bigint, bigint, integer, jsonb, text, text, text, numeric, text, boolean) from public, anon;
grant execute on function public.save_hr_rent_structure_config(bigint, bigint, integer, jsonb, text, text, text, numeric, text, boolean) to authenticated;

notify pgrst, 'reload schema';

commit;
