begin;

create extension if not exists pg_net;

create table if not exists public.transactional_email_settings (
  singleton boolean primary key default true check (singleton),
  is_enabled boolean not null default false,
  edge_function_url text,
  webhook_secret_value text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.transactional_email_settings (
  singleton,
  is_enabled,
  edge_function_url,
  webhook_secret_value
)
values (
  true,
  false,
  null,
  null
)
on conflict (singleton) do nothing;

drop trigger if exists trg_transactional_email_settings_set_updated_at on public.transactional_email_settings;
create trigger trg_transactional_email_settings_set_updated_at
before update on public.transactional_email_settings
for each row
execute function public.set_updated_at();

create table if not exists public.transactional_email_dispatches (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_type text not null
    check (event_type in ('pending_approval', 'recruitment_handoff')),
  status text not null default 'queued'
    check (status in ('queued', 'failed')),
  request_id bigint,
  payload jsonb not null default '{}'::jsonb,
  last_error text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_transactional_email_dispatches_event_type_created_at
  on public.transactional_email_dispatches (event_type, created_at desc);

create or replace function public.queue_transactional_email_notification(
  p_event_key text,
  p_event_type text,
  p_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  settings_record public.transactional_email_settings%rowtype;
  dispatch_id bigint;
  http_request_id bigint;
  webhook_secret text;
begin
  select *
    into settings_record
    from public.transactional_email_settings
   where singleton = true
   limit 1;

  if not coalesce(settings_record.is_enabled, false) then
    return;
  end if;

  if nullif(trim(coalesce(settings_record.edge_function_url, '')), '') is null then
    return;
  end if;

  webhook_secret := nullif(trim(coalesce(settings_record.webhook_secret_value, '')), '');

  if webhook_secret is null then
    return;
  end if;

  insert into public.transactional_email_dispatches (
    event_key,
    event_type,
    status,
    payload
  )
  values (
    p_event_key,
    p_event_type,
    'queued',
    coalesce(p_payload, '{}'::jsonb)
  )
  on conflict (event_key) do nothing
  returning id into dispatch_id;

  if dispatch_id is null then
    return;
  end if;

  begin
    http_request_id := net.http_post(
      url := settings_record.edge_function_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-internal-webhook-secret', webhook_secret
      ),
      body := coalesce(p_payload, '{}'::jsonb),
      timeout_milliseconds := 10000
    );

    update public.transactional_email_dispatches
       set request_id = http_request_id
     where id = dispatch_id;
  exception
    when others then
      update public.transactional_email_dispatches
         set status = 'failed',
             last_error = sqlerrm
       where id = dispatch_id;
  end;
end;
$function$;

create or replace function public.enqueue_hiring_pending_approval_email(
  p_approval_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  approval_record record;
  event_key text;
begin
  select
    hra.id,
    hra.step_code,
    hra.step_name,
    hra.approver_user_id,
    hra.approver_name,
    hra.approver_email,
    hra.created_at,
    hr.id as hiring_request_id,
    hr.folio,
    hr.requester_name,
    hr.requester_email,
    hr.contract_name,
    hr.contract_number,
    hr.job_position_name,
    hr.cost_center_code,
    hr.cost_center_name,
    hr.requested_entry_date,
    hr.start_date,
    hr.vacancies
  into approval_record
  from public.hiring_request_approvals hra
  join public.hiring_requests hr
    on hr.id = hra.hiring_request_id
  where hra.id = p_approval_id
    and hra.status = 'pending'
    and hra.step_code in ('area_manager', 'contracts_control')
  limit 1;

  if approval_record.id is null then
    return;
  end if;

  if nullif(trim(coalesce(approval_record.approver_email, '')), '') is null then
    return;
  end if;

  event_key := format('hiring-approval-pending:%s', approval_record.id);

  perform public.queue_transactional_email_notification(
    event_key,
    'pending_approval',
    jsonb_build_object(
      'kind', 'pending_approval',
      'event_key', event_key,
      'to', jsonb_build_array(
        jsonb_build_object(
          'email', approval_record.approver_email,
          'name', coalesce(nullif(trim(approval_record.approver_name), ''), approval_record.approver_email)
        )
      ),
      'approval', jsonb_build_object(
        'id', approval_record.id,
        'step_code', approval_record.step_code,
        'step_name', approval_record.step_name,
        'created_at', approval_record.created_at
      ),
      'request', jsonb_build_object(
        'id', approval_record.hiring_request_id,
        'folio', approval_record.folio,
        'requester_name', approval_record.requester_name,
        'requester_email', approval_record.requester_email,
        'contract_name', approval_record.contract_name,
        'contract_number', approval_record.contract_number,
        'job_position_name', approval_record.job_position_name,
        'cost_center_code', approval_record.cost_center_code,
        'cost_center_name', approval_record.cost_center_name,
        'requested_entry_date', approval_record.requested_entry_date,
        'start_date', approval_record.start_date,
        'vacancies', approval_record.vacancies
      ),
      'route', '/control-contrataciones'
    )
  );
end;
$function$;

create or replace function public.enqueue_recruitment_handoff_email(
  p_recruitment_case_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  case_record record;
  recipients jsonb := '[]'::jsonb;
  event_key text;
begin
  select
    rc.id,
    rc.case_code,
    rc.opened_at,
    rc.requested_vacancies,
    rc.contract_name,
    rc.job_position_name,
    rc.cost_center_code,
    rc.cost_center_name,
    hr.id as hiring_request_id,
    hr.folio,
    hr.requester_name,
    hr.requester_email,
    hr.requested_entry_date,
    hr.start_date
  into case_record
  from public.recruitment_cases rc
  join public.hiring_requests hr
    on hr.id = rc.hiring_request_id
  where rc.id = p_recruitment_case_id
  limit 1;

  if case_record.id is null then
    return;
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'email', recruitment_recipient.email,
        'name', recruitment_recipient.name
      )
      order by recruitment_recipient.name, recruitment_recipient.email
    ),
    '[]'::jsonb
  )
  into recipients
  from (
    select distinct
      lower(trim(p.email)) as email,
      coalesce(nullif(trim(p.full_name), ''), trim(p.email)) as name
    from public.profiles p
    join public.user_roles ur
      on ur.user_id = p.id
     and ur.role_code = 'reclutamiento'
    join public.app_roles ar
      on ar.code = ur.role_code
     and ar.is_active = true
    where p.status = 'active'
      and nullif(trim(coalesce(p.email, '')), '') is not null
  ) as recruitment_recipient;

  if recipients = '[]'::jsonb then
    return;
  end if;

  event_key := format('recruitment-handoff:%s', case_record.id);

  perform public.queue_transactional_email_notification(
    event_key,
    'recruitment_handoff',
    jsonb_build_object(
      'kind', 'recruitment_handoff',
      'event_key', event_key,
      'to', recipients,
      'case', jsonb_build_object(
        'id', case_record.id,
        'case_code', case_record.case_code,
        'opened_at', case_record.opened_at,
        'requested_vacancies', case_record.requested_vacancies
      ),
      'request', jsonb_build_object(
        'id', case_record.hiring_request_id,
        'folio', case_record.folio,
        'requester_name', case_record.requester_name,
        'requester_email', case_record.requester_email,
        'contract_name', case_record.contract_name,
        'job_position_name', case_record.job_position_name,
        'cost_center_code', case_record.cost_center_code,
        'cost_center_name', case_record.cost_center_name,
        'requested_entry_date', case_record.requested_entry_date,
        'start_date', case_record.start_date
      ),
      'route', '/control-contrataciones'
    )
  );
end;
$function$;

create or replace function public.trg_hiring_request_pending_email_dispatch()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  if new.status = 'pending'
     and new.step_code in ('area_manager', 'contracts_control') then
    perform public.enqueue_hiring_pending_approval_email(new.id);
  end if;

  return new;
end;
$function$;

create or replace function public.trg_recruitment_case_handoff_email_dispatch()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  perform public.enqueue_recruitment_handoff_email(new.id);
  return new;
end;
$function$;

drop trigger if exists trg_hiring_request_pending_email_dispatch on public.hiring_request_approvals;
create trigger trg_hiring_request_pending_email_dispatch
after insert on public.hiring_request_approvals
for each row
execute function public.trg_hiring_request_pending_email_dispatch();

drop trigger if exists trg_recruitment_case_handoff_email_dispatch on public.recruitment_cases;
create trigger trg_recruitment_case_handoff_email_dispatch
after insert on public.recruitment_cases
for each row
execute function public.trg_recruitment_case_handoff_email_dispatch();

revoke all on public.transactional_email_settings from public, anon, authenticated;
revoke all on public.transactional_email_dispatches from public, anon, authenticated;
revoke all on function public.queue_transactional_email_notification(text, text, jsonb) from public, anon, authenticated;
revoke all on function public.enqueue_hiring_pending_approval_email(bigint) from public, anon, authenticated;
revoke all on function public.enqueue_recruitment_handoff_email(uuid) from public, anon, authenticated;
revoke all on function public.trg_hiring_request_pending_email_dispatch() from public, anon, authenticated;
revoke all on function public.trg_recruitment_case_handoff_email_dispatch() from public, anon, authenticated;

notify pgrst, 'reload schema';

commit;
