-- EEES-DB-005: approved
-- owner: Recruitment / BUK integration
-- rollback: forward-only; preserve historical access rows and correct with a later sync.

begin;

create table if not exists public.buk_job_position_contract_access (
  id bigint generated by default as identity primary key,
  job_position_id bigint not null references public.job_positions(id) on delete cascade,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  buk_role_id bigint not null,
  buk_area_id bigint not null,
  buk_area_name text not null,
  is_active boolean not null default true,
  synced_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint buk_job_position_contract_access_key unique (job_position_id, contract_id, buk_area_id)
);

create index if not exists idx_buk_job_position_contract_access_contract
  on public.buk_job_position_contract_access (contract_id, is_active, job_position_id);

create index if not exists idx_buk_job_position_contract_access_role
  on public.buk_job_position_contract_access (buk_role_id, is_active);

alter table public.buk_job_position_contract_access enable row level security;

drop policy if exists "buk_job_position_contract_access_select_hiring" on public.buk_job_position_contract_access;
create policy "buk_job_position_contract_access_select_hiring"
on public.buk_job_position_contract_access
for select to authenticated
using (
  public.user_is_admin((select auth.uid()))
  or public.user_can_access_module((select auth.uid()), 'solicitud_contrataciones')
  or public.user_can_access_module((select auth.uid()), 'reclutamiento')
);

revoke all on public.buk_job_position_contract_access from public, anon, authenticated;
grant select on public.buk_job_position_contract_access to authenticated;

drop trigger if exists trg_buk_job_position_contract_access_set_updated_at
  on public.buk_job_position_contract_access;
create trigger trg_buk_job_position_contract_access_set_updated_at
before update on public.buk_job_position_contract_access
for each row execute function public.set_updated_at();

create or replace function public.enforce_hiring_request_buk_job_position()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  if new.contract_id is null or new.job_position_id is null then
    raise exception 'La solicitud requiere contrato y cargo';
  end if;

  if not exists (
    select 1
    from public.buk_job_position_contract_access access_row
    join public.job_positions position_row
      on position_row.id = access_row.job_position_id
     and position_row.is_active = true
    join public.contracts contract_row
      on contract_row.id = access_row.contract_id
     and contract_row.is_active = true
    where access_row.job_position_id = new.job_position_id
      and access_row.contract_id = new.contract_id
      and access_row.is_active = true
  ) then
    raise exception 'El cargo seleccionado no esta habilitado en BUK para el contrato de destino';
  end if;

  return new;
end;
$function$;

revoke all on function public.enforce_hiring_request_buk_job_position() from public, anon, authenticated;

drop trigger if exists trg_hiring_requests_buk_job_position on public.hiring_requests;
create trigger trg_hiring_requests_buk_job_position
before insert on public.hiring_requests
for each row execute function public.enforce_hiring_request_buk_job_position();

notify pgrst, 'reload schema';

commit;
