create or replace function public.normalize_buk_area_name(p_value text)
returns text
language sql
immutable
as $function$
  select nullif(
    regexp_replace(
      upper(
        trim(
          translate(
            regexp_replace(coalesce(p_value, ''), '\s*\([^)]*\)\s*$', '', 'g'),
            'ÁÉÍÓÚÜÑáéíóúüñ',
            'AEIOUUNaeiouun'
          )
        )
      ),
      '\s+',
      ' ',
      'g'
    ),
    ''
  );
$function$;

create table if not exists public.buk_contract_mappings (
  id bigint generated by default as identity primary key,
  contract_number text not null,
  contract_name text not null,
  cost_unit text not null,
  cost_unit_name text not null,
  cost_center_code text not null,
  buk_area_name text not null,
  buk_area_name_normalized text generated always as (public.normalize_buk_area_name(buk_area_name)) stored,
  cost_center_name text not null,
  manager_name text null,
  contract_admin_name text null,
  is_one_to_one boolean not null default true,
  is_operational boolean not null default true,
  contract_id bigint null references public.contracts(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint buk_contract_mappings_buk_area_name_normalized_key unique (buk_area_name_normalized)
);

create index if not exists idx_buk_contract_mappings_contract_number
  on public.buk_contract_mappings (contract_number);

create index if not exists idx_buk_contract_mappings_contract_id
  on public.buk_contract_mappings (contract_id);

create index if not exists idx_buk_contract_mappings_operational_flags
  on public.buk_contract_mappings (is_operational, is_one_to_one);

alter table public.buk_contract_mappings enable row level security;

drop policy if exists "buk_contract_mappings_select_operational_modules" on public.buk_contract_mappings;
create policy "buk_contract_mappings_select_operational_modules"
on public.buk_contract_mappings
for select
to authenticated
using (
  public.user_is_admin((select auth.uid()))
  or public.user_can_access_module((select auth.uid()), 'solicitud_contrataciones')
  or public.user_can_manage_hr_incentives((select auth.uid()))
);

grant select on public.buk_contract_mappings to authenticated;

drop trigger if exists trg_buk_contract_mappings_set_updated_at on public.buk_contract_mappings;
create trigger trg_buk_contract_mappings_set_updated_at
before update on public.buk_contract_mappings
for each row
execute function public.set_updated_at();

create temp table tmp_buk_contract_mapping_seed (
  contract_number text not null,
  contract_name text not null,
  cost_unit text not null,
  cost_unit_name text not null,
  cost_center_code text not null,
  buk_area_name text not null,
  cost_center_name text not null,
  manager_name text null,
  contract_admin_name text null,
  is_one_to_one boolean not null,
  is_operational boolean not null
) on commit drop;

insert into tmp_buk_contract_mapping_seed (
  contract_number,
  contract_name,
  cost_unit,
  cost_unit_name,
  cost_center_code,
  buk_area_name,
  cost_center_name,
  manager_name,
  contract_admin_name,
  is_one_to_one,
  is_operational
)
values
  ('0000000102:0001', 'ABASTECIMIENTO', '100', 'ADMINISTRACION', '10104', 'ABASTECIMIENTO JM', 'GERENCIA FINANZAS', 'Raul Lopez Guerra', 'Jose Luis Sierra', true, true),
  ('7801797801:0001', 'ACCIONA OSSA PIZZAROTTI CAMBIO TURNO', '109', 'SERV ESPECIALES', '10113', 'ACCIONA OSSA PIZZAROTTI CAMBIO DE TURNO', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('5906986002:0001', 'ACCIONA TALABRE', '115', 'SERV CAMBIO DE TURNO', '10116', 'ACCIONA TALABRE', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('0000000101:0001', 'ADMINISTRACION', '100', 'ADMINISTRACION', '10100', 'ADMINISTRACION', 'GERENCIA GENERAL', 'Guillermo Zañartu Apara', 'Juan Carlos Navea', true, true),
  ('0000000159:0001', 'INDIRECTOS ZONA II', '159', 'INDIRECTOS ZONA II', '10114', 'ADMINISTRACION CALAMA', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Maximiliano Contreras Rey', false, false),
  ('8832580001:0001', 'FUNDICION ALTONORTE', '125', 'SERV ALTONORTE', '10116', 'ALTO NORTE', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Javier Plaza Cerda', true, true),
  ('7851187001:0001', 'ANDIMAR', '109', 'SERV ESPECIALES', '10113', 'ANDIMAR', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('7611769635:0001', 'ARAMARK - CAMPUS CODELCO', '107', 'SERV ARAMARK', '10114', 'ARAMARK - CAMPUS CODELCO', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7611769634:0001', 'ARAMARK - EL ABRA', '107', 'SERV ARAMARK', '10114', 'ARAMARK - EL ABRA', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7611769633:0001', 'ARAMARK - PRET', '107', 'SERV ARAMARK', '10114', 'ARAMARK - PRET', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7611769609:0001', 'ARAMARK CAMPAMENTO ZONA NORTE', '115', 'SERV CAMBIO DE TURNO', '10116', 'ARAMARK CAMPAMENTO ZONA NORTE', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7611769626:0001', 'ARAMARK CAMPAMENTO ZONA NORTE INTERNO', '107', 'SERV ARAMARK', '10114', 'ARAMARK CAMPAMENTO ZONA NORTE INTERNO', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7611769632:0001', 'ARAMARK DSAL', '115', 'SERV CAMBIO DE TURNO', '10116', 'ARAMARK DSAL', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7611769614:0001', 'ARAMARK ESCONDIDA', '115', 'SERV CAMBIO DE TURNO', '10116', 'ARAMARK ESCONDIDA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7611769625:0001', 'ARAMARK GABY', '115', 'SERV CAMBIO DE TURNO', '10116', 'ARAMARK GABY', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7611769627:0001', 'ARAMARK GABY INTERNO', '107', 'SERV ARAMARK', '10114', 'ARAMARK GABY INTERNO', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7611769628:0001', 'ARAMARK MINISTRO HALES INTERNO', '107', 'SERV ARAMARK', '10114', 'ARAMARK MINISTRO HALES INTERNO', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7611769612:0001', 'ARAMARK QUEBRADA BLANCA', '115', 'SERV CAMBIO DE TURNO', '10116', 'ARAMARK QUEBRADA BLANCA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7611769602:0001', 'ARAMARK SIERRA GORDA', '115', 'SERV CAMBIO DE TURNO', '10116', 'ARAMARK SIERRA GORDA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7611769630:0001', 'ARAMARK SIERRA GORDA INTERNO', '107', 'SERV ARAMARK', '10114', 'ARAMARK SIERRA GORDA INTERNO', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('761176912:0001', 'ARAMARK VP ANDINA', '109', 'SERV ESPECIALES', '10113', 'ARAMARK VP ANDINA', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('0000000162:0001', 'ARRIENDO DE BUSES', '162', 'ARRIENDO DE BUSES', '10100', 'ARRIENDO DE BUSES', 'GERENCIA GENERAL', 'Guillermo Zañartu Apara', 'Alan Brain Biggemann', true, true),
  ('7642593601:0001', 'ASIB - SIERRA GORDA', '115', 'SERV CAMBIO DE TURNO', '10116', 'ASIB - SIERRA GORDA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7811932003:0001', 'AURA - DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'AURA - DAND', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Isac Arratia Carcamo', true, true),
  ('7605030115:0001', 'BERLIAM - DRT CHANCADO SECUNDARIO', '121', 'SERV FERROVIAL', '10114', 'BERLIAM - DRT CHANCADO SECUNDARIO', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7605030110:0001', 'BERLIAM DRT CHANCADO', '121', 'SERV FERROVIAL', '10114', 'BERLIAM DRT CHANCADO', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7605030113:0001', 'BERLIAM ZALDIVAR', '121', 'SERV FERROVIAL', '10116', 'BERLIAM ZALDIVAR', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Javier Plaza Cerda', true, true),
  ('0000000103:0001', 'BODEGA', '100', 'ADMINISTRACION', '10104', 'BODEGA JM', 'GERENCIA FINANZAS', 'Raul Lopez Guerra', 'Jose Luis Sierra', false, false),
  ('6170400008:0001', 'CODELCO ANDINA 2022', '154', 'SERV CODELCO ANDINA', '10113', 'CODELCO ANDINA 2022', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Isac Arratia Carcamo', true, true),
  ('6170400010:0001', 'CODELCO DRT', '163', 'CODELCO DRT', '10114', 'CODELCO DRT', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Carlos Villagran Suarez', true, true),
  ('6170400009:0001', 'CODELCO VP ANDINA 2022', '155', 'SERV CODELCO ANDINA VP', '10113', 'CODELCO VP ANDINA 2022', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Marcelo Villarroel Gutierrez', true, true),
  ('6170400007:0001', 'CODELCO VP CHUQUI PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'CODELCO VP CHUQUI', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Ricardo Mella Osorio', true, true),
  ('0000000104:0001', 'COMERCIAL', '100', 'ADMINISTRACION', '10102', 'COMERCIAL JM', 'GERENCIA COMERCIAL', 'Alan Brain Biggemann', 'Alan Brain Biggemann', true, true),
  ('9687083002:0001', 'COMTECSA - PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'COMTECSA - PMCHS', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Ricardo Mella Osorio', true, true),
  ('7752259301:0001', 'SANTA ISADORA SQM', '115', 'SERV CAMBIO DE TURNO', '10116', 'CONSTRUCTORA SANTA ISADORA - SQM', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('0000000106:0001', 'CONTABILIDAD', '100', 'ADMINISTRACION', '10104', 'CONTABILIDAD JM', 'GERENCIA FINANZAS', 'Raul Lopez Guerra', 'Rodrigo Puentes Araya', true, true),
  ('0000000107:0001', 'CONTROL FLOTA', '100', 'ADMINISTRACION', '10115', 'CONTROL FLOTA JM', 'CONTROL FLOTA', 'Juan Carlos Navea', 'Juan Carlos Navea', true, true),
  ('9957547004:0001', 'DESCARTABLES', '100', 'ADMINISTRACION', '10115', 'DESCARTABLES', 'CONTROL FLOTA', 'Juan Carlos Navea', 'Rodrigo Galdames', true, true),
  ('9999999998:0001', 'DISPONIBLES EN REPARACION', '108', 'MANTENCION LOS ANDES', '10106', 'DISPONIBLES EN REPARACION', 'GERENCIA MANTENIMIENTO', 'Rodrigo Galdames', 'Rodrigo Galdames', true, true),
  ('9957547008:0001', 'DISPONIBLES PARA ASIGNAR', '100', 'ADMINISTRACION', '10102', 'DISPONIBLES PARA ASIGNAR', 'GERENCIA COMERCIAL', 'Alan Brain Biggemann', 'Alan Brain Biggemann', true, true),
  ('7672704001:0001', 'DMC CENTINELA', '165', 'SERV MINERA CENTINELA', '10116', 'DMC CENTINELA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7952723001:0001', 'EMIN - MEL', '166', 'CONTRATISTAS ANTOFAGASTA', '10116', 'EMIN - MEL', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Javier Plaza Cerda', true, true),
  ('7604187102:0001', 'ENAEX ANDINA 2024', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'ENAEX ANDINA', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Isac Arratia Carcamo', true, true),
  ('0000000105:0001', 'FACTURACION Y COBRANZAS', '100', 'ADMINISTRACION', '10104', 'FACTURACION Y COBRANZA JM', 'GERENCIA FINANZAS', 'Raul Lopez Guerra', 'Carolina Lira Garrido', true, true),
  ('9148900001:0001', 'FINNING ARMADO DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'FINNING ARMADO DAND', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Isac Arratia Carcamo', true, true),
  ('9148900002:0001', 'FINNING MARC DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'FINNING MARC DAND', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Isac Arratia Carcamo', true, true),
  ('7776182302:0001', 'FLIX LA SERENA', '164', 'SERV FLIX', '10113', 'FLIX LA SERENA', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('7776182304:0001', 'FLIX QUINTERO', '164', 'SERV FLIX', '10113', 'FLIX QUINTERO', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('7776182308:0001', 'FLIX SAN ANTONIO', '164', 'SERV FLIX', '10113', 'FLIX SAN ANTONIO', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('7776182303:0001', 'FLIX SANTIAGO', '164', 'SERV FLIX', '10113', 'FLIX SANTIAGO', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('7776182306:0001', 'FLIX VALPARAÍSO', '164', 'SERV FLIX', '10113', 'FLIX VALPARAISO', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('7776182301:0001', 'FLIX VIÑA DEL MAR', '164', 'SERV FLIX', '10113', 'FLIX VIÑA DEL MAR', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('8555590001:0001', 'FLUOR - EL ABRA', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'FLUOR - EL ABRA', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7676154701:0001', 'FLUOR SALFA CENTINELA', '169', 'FLUOR SALFA CENTINELA', '10116', 'FLUOR-SALFA CENTINELA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Jose Irribarren Sepulveda', true, true),
  ('7973088001:0001', 'INCOLUR VP ANDINA', '109', 'SERV ESPECIALES', '10113', 'INCOLUR VP ANDINA', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('0000000158:0001', 'INDIRECTOS ZONA I', '158', 'INDIRECTOS ZONA I', '10113', 'INDIRECTOS ZONA I', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Cristian Jimenez Jimenez', true, true),
  ('0000000167:0001', 'INDIRECTOS ZONA III', '167', 'INDIRECTOS ZONA III', '10116', 'INDIRECTOS ZONA III', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Luciano Fischer Ballerini', true, true),
  ('7831857001:0001', 'JEJ INGENIERIA VP ANDINA', '109', 'SERV ESPECIALES', '10113', 'JEJ INGENIERIA VP ANDINA', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('7850277001:0001', 'JM SERV ESPECIALES', '109', 'SERV ESPECIALES', '10113', 'JM SERVICIOS ESPECIALES', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Jorge Parra Jimenez', true, true),
  ('9957547009:0001', 'MANTENCION ANTOFAGASTA', '160', 'MANTENCION ANTOFAGASTA', '10106', 'MANTENCION ANTOFAGASTA JM', 'GERENCIA MANTENIMIENTO', 'Rodrigo Galdames', 'Rodrigo Galdames', true, true),
  ('9957547001:0001', 'MANTENCION CALAMA', '122', 'MANTENCION CALAMA', '10106', 'MANTENCION CALAMA JM', 'GERENCIA MANTENIMIENTO', 'Rodrigo Galdames', 'Rodrigo Galdames', false, false),
  ('9957547010:0001', 'MANTENCION IQUIQUE', '161', 'MANTENCION IQUIQUE', '10106', 'MANTENCION IQUIQUE JM', 'GERENCIA MANTENIMIENTO', 'Rodrigo Galdames', 'Rodrigo Galdames', true, true),
  ('9957547002:0001', 'MANTENCION LOS ANDES', '108', 'MANTENCION LOS ANDES', '10106', 'MANTENCION JM', 'GERENCIA MANTENIMIENTO', 'Rodrigo Galdames', 'Rodrigo Galdames', true, true),
  ('9665191013:0001', 'NEWREST - FRANKE', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST - FRANKE', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9665191012:0001', 'NEWREST - QB PUERTO TECK', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST - QB PUERTO TECK', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9665191011:0001', 'NEWREST - ALBEMARLE', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST ALBEMARLE', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9665191007:0001', 'NEWREST ANTUCOYA', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST ANTUCOYA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9665191006:0001', 'NEWREST CASERONES', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST CACERONES', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', false, false),
  ('9665191008:0001', 'NEWREST CENTINELA', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST CENTINELA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9665191003:0001', 'NEWREST COLLAHUASI', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST COLLAHUASI', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9665191005:0001', 'NEWREST CONCENTRADORA CENTINELA', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST CONCENTRADORA CENTINELA', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9665191010:0001', 'NEWREST - DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'NEWREST DAND', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Isac Arratia Carcamo', true, true),
  ('9665191009:0001', 'NEWREST MUELLE', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST MUELLE', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Javier Plaza Cerda', true, true),
  ('9665191004:0001', 'NEWREST ZALDIVAR', '115', 'SERV CAMBIO DE TURNO', '10116', 'NEWREST ZALDIVAR', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7842341001:0001', 'NOATUM - EL ABRA', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'NOATUM - EL ABRA', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('0000000111:0001', 'PREVENCION DE RIESGOS', '100', 'ADMINISTRACION', '10110', 'PREVENCION DE RIESGOS JM', 'GERENCIA PREVENCION DE RIESGOS', 'Manuel Parra Soto', 'Manuel Parra Soto', true, true),
  ('8486500001:0001', 'RYQ PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'R y Q PMCHS', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Ricardo Mella Osorio', true, true),
  ('0000000109:0001', 'RECURSOS HUMANOS', '100', 'ADMINISTRACION', '10111', 'RECURSOS HUMANOS', 'GERENCIA RECURSOS HUMANOS', 'Andres Madrid Maureira', 'Andres Madrid Maureira', false, false),
  ('6170400006:0001', 'CODELCO DMH', '128', 'SERV CODELCO DMH', '10114', 'SERVICIO CODELCO DMH', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Jose Orellana Paez', true, true),
  ('7608159002:0001', 'SIERRA GORDA OPERACIONES', '110', 'SERV SIERRA GORDA', '10116', 'SIERRA GORDA - OPERACION', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Angel Guerra Basso', true, true),
  ('9462300004:0001', 'SODEXO - CERRO PABELLÓN', '115', 'SERV CAMBIO DE TURNO', '10116', 'SODEXO - CERRO PABELLON', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('9462300001:0001', 'SODEXO SQM', '115', 'SERV CAMBIO DE TURNO', '10116', 'SODEXO SQM', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', true, true),
  ('7805700001:0001', 'SOTRASER - DMH', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'SOTRASER-DMH', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7654304601:0001', 'SYNCORE - TALABRE', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'SYNCORE - TALABRE', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('0000000112:0001', 'TECNOLOGIA E INFORMACION', '100', 'ADMINISTRACION', '10104', 'TECNOLOGIA E INFORMACIÓN JM', 'GERENCIA FINANZAS', 'Raul Lopez Guerra', 'Maria Jesus Lagos Minardi', true, true),
  ('7627009901:0001', 'TEPSAC DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'TEPSAC DAND', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Isac Arratia Carcamo', true, true),
  ('0000000108:0001', 'TESORERIA', '100', 'ADMINISTRACION', '10104', 'TESORERIA JM', 'GERENCIA FINANZAS', 'Raul Lopez Guerra', 'Marcos Jara Arenas', true, true),
  ('7850277002:0001', 'INTERURBANO VALPARAISO', '150', 'SERV PASAJEROS', '10113', 'VALPARAISO', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Victor Guerrero Gutierrez', true, true),
  ('9999999996:0001', 'VENDIDO REPARACIONES PENDIENTES', '100', 'ADMINISTRACION', '10112', 'VENDIDO REPARACIONES PENDIENTES', 'SOCIOS', 'Jose Miardi Cueto', 'Jose Miardi Cueto', true, true),
  ('9999999999:0001', 'VENTA', '100', 'ADMINISTRACION', '10112', 'VENTA', 'SOCIOS', 'Jose Miardi Cueto', 'Jose Miardi Cueto', true, true),
  ('9695370002:0001', 'XTREME MINING PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'XTREME MINING PMCHS', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Ricardo Mella Osorio', true, true),
  ('0000000168:0001', 'ZONA II CONTRATISTAS', '168', 'ZONA II CONTRATISTAS', '10114', 'ZONA II CONTRATISTAS', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('7606991001:0001', 'SERCOING - DRT', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'SERCOING - DRT', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('6170400011:0001', 'CODELCO - DSAL', '170', 'CODELCO - DSAL', '10113', 'CODELCO - DSAL', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Marcelo Villarroel Gutierrez', true, true),
  ('7611769636:0001', 'ARAMARK - DCH', '107', 'SERV ARAMARK', '10114', 'ARAMARK - DCH', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Oscar Poblete Celedon', true, true),
  ('0000000109:0004', 'RECURSOS HUMANOS', '400', 'ADMINISTRACION', '40111', 'RECURSOS HUMANOS CNN', 'GERENCIA RECURSOS HUMANOS', 'Andres Madrid Maureira', 'Andres Madrid Maureira', true, true),
  ('0000000109:0001', 'RECURSOS HUMANOS', '100', 'ADMINISTRACION', '10111', 'RECURSOS HUMANOS JM', 'GERENCIA RECURSOS HUMANOS', 'Andres Madrid Maureira', 'Andres Madrid Maureira', false, false),
  ('0000000109:0006', 'RECURSOS HUMANOS', '600', 'ADMINISTRACION', '60111', 'RECURSOS HUMANOS PLAZA VIEJA', 'GERENCIA RECURSOS HUMANOS', 'Andres Madrid Maureira', 'Andres Madrid Maureira', true, true),
  ('0000000109:0001', 'RECURSOS HUMANOS', '100', 'ADMINISTRACION', '10111', 'RECURSOS HUMANOS ZONA NORTE', 'GERENCIA RECURSOS HUMANOS', 'Andres Madrid Maureira', 'Andres Madrid Maureira', false, false),
  ('9957547001:0001', 'MANTENCION CALAMA', '122', 'MANTENCION CALAMA', '10111', 'MANTENCION CALAMA', 'GERENCIA MANTENIMIENTO', 'Rodrigo Galdames', 'Rodrigo Galdames', false, false),
  ('9957547001:0004', 'MANTENCION CALAMA', '422', 'MANTENCION CALAMA', '40106', 'MANTENCION CALAMA CNN', 'GERENCIA MANTENIMIENTO', 'Rodrigo Galdames', 'Rodrigo Galdames', true, true),
  ('0000000159:0001', 'INDIRECTOS ZONA II', '159', 'INDIRECTOS ZONA II', '10114', 'INDIRECTOS ZONA II', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Maximiliano Contreras Rey', false, false),
  ('9665191006:0001', 'NEWREST CASERONES', '115', 'SERV CAMBIO DE TURNO', '10116', 'Newrest - Caserones', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', 'Luciano Fischer Ballerini', 'Andres Barraza Mera', false, false),
  ('0000000103:0001', 'BODEGA', '100', 'ADMINISTRACION', '10104', 'BODEGA ZONA NORTE', 'GERENCIA FINANZAS', 'Raul Lopez Guerra', 'Jose Luis Sierra', false, false),
  ('0000000159:0004', 'INDIRECTOS ZONA II', '459', 'INDIRECTOS ZONA II', '40114', 'INDIRECTO ZONA II CNN', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Maximiliano Contreras Rey', true, true),
  ('0000000159:0002', 'INDIRECTOS ZONA II', '259', 'INDIRECTOS ZONA II', '20114', 'INDIRECTO ZONA II SIMSA', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', 'Maximiliano Contreras Rey', 'Maximiliano Contreras Rey', true, true),
  ('0000000158:0005', 'INDIRECTOS ZONA I', '558', 'INDIRECTOS ZONA I', '50113', 'INDIRECTOS ZONA I CONSORCIO ANDINO', 'GERENCIA OPERACIONES ZONA I (CENTRO)', 'Cristian Jimenez Jimenez', 'Cristian Jimenez Jimenez', true, true);

update public.contracts c
set
  contract_name = s.contract_name,
  cost_unit = s.cost_unit,
  cost_unit_name = s.cost_unit_name,
  cost_center_code = s.cost_center_code,
  cost_center_name = s.cost_center_name,
  updated_at = timezone('utc', now())
from tmp_buk_contract_mapping_seed s
where s.is_operational = true
  and s.is_one_to_one = true
  and c.contract_number = s.contract_number
  and (
    c.contract_name is distinct from s.contract_name
    or c.cost_unit is distinct from s.cost_unit
    or c.cost_unit_name is distinct from s.cost_unit_name
    or c.cost_center_code is distinct from s.cost_center_code
    or c.cost_center_name is distinct from s.cost_center_name
  );

with max_code as (
  select coalesce(max((substring(code from 'CONT-(\d+)$'))::integer), 0) as value
  from public.contracts
),
missing_contracts as (
  select distinct
    s.contract_number,
    s.contract_name,
    s.cost_unit,
    s.cost_unit_name,
    s.cost_center_code,
    s.cost_center_name
  from tmp_buk_contract_mapping_seed s
  left join public.contracts c
    on c.contract_number = s.contract_number
  where s.is_operational = true
    and s.is_one_to_one = true
    and c.id is null
),
numbered_missing_contracts as (
  select
    mc.*,
    row_number() over (order by mc.contract_number) as row_number
  from missing_contracts mc
)
insert into public.contracts (
  code,
  contract_number,
  contract_name,
  cost_unit,
  cost_unit_name,
  cost_center_code,
  cost_center_name,
  is_active
)
select
  'CONT-' || lpad((max_code.value + nmc.row_number)::text, 3, '0'),
  nmc.contract_number,
  nmc.contract_name,
  nmc.cost_unit,
  nmc.cost_unit_name,
  nmc.cost_center_code,
  nmc.cost_center_name,
  true
from numbered_missing_contracts nmc
cross join max_code;

insert into public.buk_contract_mappings (
  contract_number,
  contract_name,
  cost_unit,
  cost_unit_name,
  cost_center_code,
  buk_area_name,
  cost_center_name,
  manager_name,
  contract_admin_name,
  is_one_to_one,
  is_operational
)
select
  s.contract_number,
  s.contract_name,
  s.cost_unit,
  s.cost_unit_name,
  s.cost_center_code,
  s.buk_area_name,
  s.cost_center_name,
  s.manager_name,
  s.contract_admin_name,
  s.is_one_to_one,
  s.is_operational
from tmp_buk_contract_mapping_seed s
on conflict (buk_area_name_normalized) do update
set
  contract_number = excluded.contract_number,
  contract_name = excluded.contract_name,
  cost_unit = excluded.cost_unit,
  cost_unit_name = excluded.cost_unit_name,
  cost_center_code = excluded.cost_center_code,
  cost_center_name = excluded.cost_center_name,
  manager_name = excluded.manager_name,
  contract_admin_name = excluded.contract_admin_name,
  is_one_to_one = excluded.is_one_to_one,
  is_operational = excluded.is_operational,
  updated_at = timezone('utc', now());

update public.buk_contract_mappings bcm
set
  contract_id = c.id,
  updated_at = timezone('utc', now())
from public.contracts c
where c.contract_number = bcm.contract_number
  and bcm.contract_id is distinct from c.id;

create or replace function public.submit_hiring_request(
  p_contract_id bigint,
  p_job_position_id bigint,
  p_vacancies integer,
  p_requested_entry_date date,
  p_start_date date,
  p_end_date date,
  p_campamento boolean,
  p_pasajes boolean,
  p_other_benefits text,
  p_salary_offer numeric,
  p_shift_id bigint,
  p_requester_signed boolean
)
returns table (request_id uuid, folio text)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  requester_profile public.profiles%rowtype;
  contract_record public.contracts%rowtype;
  contract_mapping_record public.buk_contract_mappings%rowtype;
  job_position_record public.job_positions%rowtype;
  shift_record public.shifts%rowtype;
  area_manager_record public.cost_center_approvers%rowtype;
  area_manager_profile public.profiles%rowtype;
  contracts_control_record public.workflow_approvers%rowtype;
  request_snapshot jsonb;
  resolved_contract_name text;
  created_request_id uuid;
  next_folio text;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_can_access_module(current_user_id, 'solicitud_contrataciones') then
    raise exception 'Sin permisos para crear solicitudes';
  end if;

  if not coalesce(p_requester_signed, false) then
    raise exception 'La solicitud debe enviarse con firma del solicitante';
  end if;

  if p_vacancies is null or p_vacancies <= 0 then
    raise exception 'La cantidad de vacantes debe ser mayor a 0';
  end if;

  if p_salary_offer is null or p_salary_offer < 0 then
    raise exception 'La renta liquida ofrecida es invalida';
  end if;

  if p_requested_entry_date is null or p_start_date is null or p_end_date is null then
    raise exception 'Faltan fechas obligatorias en la solicitud';
  end if;

  if p_end_date < p_start_date then
    raise exception 'La fecha de termino no puede ser anterior a la fecha de inicio';
  end if;

  select *
    into requester_profile
    from public.profiles
   where id = current_user_id
   for share;

  if requester_profile.id is null then
    raise exception 'No existe perfil para el usuario autenticado';
  end if;

  select *
    into contract_record
    from public.contracts
   where id = p_contract_id
     and is_active = true
   for share;

  if contract_record.id is null then
    raise exception 'Contrato invalido o inactivo';
  end if;

  select *
    into contract_mapping_record
    from public.buk_contract_mappings
   where contract_id = contract_record.id
     and is_operational = true
     and is_one_to_one = true
   order by buk_area_name
   limit 1;

  resolved_contract_name := coalesce(contract_mapping_record.buk_area_name, contract_record.contract_name);

  select *
    into job_position_record
    from public.job_positions
   where id = p_job_position_id
     and is_active = true
   for share;

  if job_position_record.id is null then
    raise exception 'Cargo invalido o inactivo';
  end if;

  select *
    into shift_record
    from public.shifts
   where id = p_shift_id
     and is_active = true
   for share;

  if shift_record.id is null then
    raise exception 'Turno invalido o inactivo';
  end if;

  select *
    into area_manager_record
    from public.cost_center_approvers
   where cost_center_code = contract_record.cost_center_code
     and is_active = true
   for share;

  if area_manager_record.id is null then
    raise exception 'No existe gerente configurado para el centro de costo del contrato';
  end if;

  if area_manager_record.approver_user_id is null then
    raise exception 'El gerente del centro de costo aun no tiene usuario vinculado en la plataforma';
  end if;

  select *
    into area_manager_profile
    from public.profiles
   where id = area_manager_record.approver_user_id
     and status = 'active'
   for share;

  if area_manager_profile.id is null then
    raise exception 'El gerente del centro de costo no tiene una cuenta activa';
  end if;

  select *
    into contracts_control_record
    from public.workflow_approvers
   where step_code = 'contracts_control'
     and is_active = true
   for share;

  if contracts_control_record.step_code is null then
    raise exception 'No existe aprobador configurado para Control de Contratos';
  end if;

  if contracts_control_record.approver_user_id is null then
    raise exception 'Control de Contratos aun no tiene usuario vinculado en la plataforma';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = contracts_control_record.approver_user_id
      and p.status = 'active'
  ) then
    raise exception 'El usuario configurado para Control de Contratos no tiene una cuenta activa';
  end if;

  next_folio := lpad(nextval('public.hiring_folio_seq')::text, 4, '0');

  insert into public.hiring_requests (
    folio,
    requester_id,
    requester_name,
    requester_job_title,
    requester_email,
    requested_entry_date,
    job_position_id,
    job_position_name,
    vacancies,
    contract_id,
    contract_name,
    contract_number,
    cost_unit,
    cost_unit_name,
    cost_center_code,
    cost_center_name,
    start_date,
    end_date,
    campamento,
    pasajes,
    other_benefits,
    salary_offer,
    shift_id,
    shift_name,
    requester_signed,
    status,
    current_step_code,
    submitted_at,
    submitted_by,
    created_at,
    updated_at
  )
  values (
    next_folio,
    current_user_id,
    coalesce(requester_profile.full_name, requester_profile.email),
    requester_profile.job_title,
    requester_profile.email,
    p_requested_entry_date,
    job_position_record.id,
    job_position_record.name,
    p_vacancies,
    contract_record.id,
    resolved_contract_name,
    contract_record.contract_number,
    contract_record.cost_unit,
    contract_record.cost_unit_name,
    contract_record.cost_center_code,
    contract_record.cost_center_name,
    p_start_date,
    p_end_date,
    coalesce(p_campamento, false),
    coalesce(p_pasajes, false),
    nullif(trim(coalesce(p_other_benefits, '')), ''),
    p_salary_offer,
    shift_record.id,
    shift_record.name,
    true,
    'pending_area_manager',
    'area_manager',
    timezone('utc', now()),
    current_user_id,
    timezone('utc', now()),
    timezone('utc', now())
  )
  returning id into created_request_id;

  request_snapshot := jsonb_build_object(
    'folio', next_folio,
    'requester_id', current_user_id,
    'requester_name', coalesce(requester_profile.full_name, requester_profile.email),
    'requester_job_title', requester_profile.job_title,
    'requester_email', requester_profile.email,
    'requested_entry_date', p_requested_entry_date,
    'job_position_id', job_position_record.id,
    'job_position_name', job_position_record.name,
    'vacancies', p_vacancies,
    'contract_id', contract_record.id,
    'contract_name', resolved_contract_name,
    'contract_number', contract_record.contract_number,
    'cost_unit', contract_record.cost_unit,
    'cost_unit_name', contract_record.cost_unit_name,
    'cost_center_code', contract_record.cost_center_code,
    'cost_center_name', contract_record.cost_center_name,
    'start_date', p_start_date,
    'end_date', p_end_date,
    'campamento', coalesce(p_campamento, false),
    'pasajes', coalesce(p_pasajes, false),
    'other_benefits', nullif(trim(coalesce(p_other_benefits, '')), ''),
    'salary_offer', p_salary_offer,
    'shift_id', shift_record.id,
    'shift_name', shift_record.name,
    'requester_signed', true
  );

  insert into public.hiring_request_snapshots (
    hiring_request_id,
    snapshot_type,
    payload,
    created_by
  )
  values (
    created_request_id,
    'submitted',
    request_snapshot,
    current_user_id
  );

  insert into public.hiring_request_approvals (
    hiring_request_id,
    step_code,
    step_name,
    step_order,
    approver_user_id,
    approver_name,
    approver_email,
    status,
    decision_by,
    decision_comment,
    decided_at,
    locked_at,
    created_at,
    updated_at
  )
  values (
    created_request_id,
    'requester_signature',
    'Firma solicitante',
    1,
    current_user_id,
    coalesce(requester_profile.full_name, requester_profile.email),
    requester_profile.email,
    'approved',
    current_user_id,
    null,
    timezone('utc', now()),
    timezone('utc', now()),
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (hiring_request_id, step_code) do nothing;

  insert into public.hiring_request_approvals (
    hiring_request_id,
    step_code,
    step_name,
    step_order,
    approver_user_id,
    approver_name,
    approver_email,
    status,
    created_at,
    updated_at
  )
  values (
    created_request_id,
    'area_manager',
    'Gerente de area',
    2,
    area_manager_record.approver_user_id,
    area_manager_record.approver_name,
    coalesce(area_manager_record.approver_email, area_manager_profile.email),
    'pending',
    timezone('utc', now()),
    timezone('utc', now())
  );

  insert into public.hiring_request_audit_log (
    hiring_request_id,
    actor_user_id,
    action_type,
    new_values,
    metadata
  )
  values (
    created_request_id,
    current_user_id,
    'submitted',
    request_snapshot,
    jsonb_build_object(
      'current_step_code', 'area_manager',
      'status', 'pending_area_manager'
    )
  );

  insert into public.hiring_request_audit_log (
    hiring_request_id,
    approval_id,
    actor_user_id,
    action_type,
    new_values,
    metadata
  )
  select
    created_request_id,
    hra.id,
    current_user_id,
    'approval_created',
    jsonb_build_object(
      'step_code', hra.step_code,
      'step_name', hra.step_name,
      'approver_user_id', hra.approver_user_id,
      'approver_name', hra.approver_name,
      'approver_email', hra.approver_email,
      'status', hra.status
    ),
    jsonb_build_object('created_by_flow', 'submit_hiring_request')
  from public.hiring_request_approvals hra
  where hra.hiring_request_id = created_request_id
    and hra.step_code = 'area_manager';

  return query
  select created_request_id, next_folio;
end;
$function$;

create or replace function public.search_hr_incentive_eligible_workers(
  p_search text default null,
  p_limit integer default 20
)
returns table (
  buk_employee_id text,
  full_name text,
  document_number text,
  job_title text,
  contract_code text,
  area_name text,
  display_label text
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  normalized_search text := lower(trim(coalesce(p_search, '')));
  safe_limit integer := greatest(1, least(coalesce(p_limit, 20), 30));
begin
  if not public.user_can_manage_hr_incentives(current_user_id) then
    raise exception 'Sin permisos para consultar trabajadores elegibles';
  end if;

  return query
  with eligible_titles as (
    select upper(trim(jt.job_title)) as normalized_job_title
    from public.hr_incentive_allowed_job_titles jt
    where jt.is_active = true
  ),
  active_workers as (
    select
      e.buk_employee_id,
      e.full_name,
      coalesce(e.document_number, e.raw_payload ->> 'document_number', e.raw_payload ->> 'rut') as document_number,
      coalesce(
        nullif(trim(e.job_title), ''),
        nullif(trim(e.raw_payload -> 'current_job' -> 'role' ->> 'name'), ''),
        nullif(trim(e.raw_payload -> 'current_job' -> 'custom_attributes' ->> 'Nuevo cargo'), ''),
        nullif(trim(e.raw_payload ->> 'job_title'), '')
      ) as resolved_job_title,
      c.code as contract_code,
      bcm.buk_area_name as area_name
    from public.employees_active_current e
    join eligible_titles et
      on upper(
        trim(
          coalesce(
            nullif(trim(e.job_title), ''),
            nullif(trim(e.raw_payload -> 'current_job' -> 'role' ->> 'name'), ''),
            nullif(trim(e.raw_payload -> 'current_job' -> 'custom_attributes' ->> 'Nuevo cargo'), ''),
            nullif(trim(e.raw_payload ->> 'job_title'), '')
          )
        )
      ) = et.normalized_job_title
    join public.buk_contract_mappings bcm
      on bcm.buk_area_name_normalized = public.normalize_buk_area_name(e.area_name)
     and bcm.is_operational = true
     and bcm.is_one_to_one = true
     and bcm.contract_id is not null
    join public.contracts c
      on c.id = bcm.contract_id
     and c.is_active = true
  )
  select
    aw.buk_employee_id,
    aw.full_name,
    aw.document_number,
    aw.resolved_job_title as job_title,
    aw.contract_code,
    aw.area_name,
    concat_ws(
      ' | ',
      coalesce(aw.document_number, 'Sin RUT'),
      coalesce(aw.resolved_job_title, 'Sin cargo'),
      aw.full_name,
      coalesce(aw.area_name, aw.contract_code, 'Sin contrato')
    ) as display_label
  from active_workers aw
  where
    normalized_search = ''
    or lower(
      concat_ws(
        ' ',
        aw.full_name,
        coalesce(aw.document_number, ''),
        coalesce(aw.resolved_job_title, ''),
        coalesce(aw.contract_code, ''),
        coalesce(aw.area_name, '')
      )
    ) like '%' || normalized_search || '%'
  order by aw.full_name
  limit safe_limit;
end;
$function$;

create or replace function public.get_hr_incentive_worker_context(
  p_buk_employee_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  worker_row record;
  resolved_union_status text;
begin
  if not public.user_can_manage_hr_incentives(current_user_id) then
    raise exception 'Sin permisos para consultar el trabajador';
  end if;

  select
    e.id,
    e.buk_employee_id,
    e.full_name,
    coalesce(e.document_number, e.raw_payload ->> 'document_number', e.raw_payload ->> 'rut') as document_number,
    coalesce(e.document_type, e.raw_payload ->> 'document_type', 'rut') as document_type,
    coalesce(
      nullif(trim(e.job_title), ''),
      nullif(trim(e.raw_payload -> 'current_job' -> 'role' ->> 'name'), ''),
      nullif(trim(e.raw_payload -> 'current_job' -> 'custom_attributes' ->> 'Nuevo cargo'), ''),
      nullif(trim(e.raw_payload ->> 'job_title'), '')
    ) as job_title,
    public.get_hr_incentive_union_name(e.raw_payload) as union_name,
    public.get_hr_incentive_union_status(e.raw_payload) as union_status,
    nullif(trim(e.raw_payload -> 'current_job' -> 'custom_attributes' ->> 'Fecha incorporación al sindicato'), '') as union_joined_at,
    c.code as contract_code,
    bcm.buk_area_name as area_name,
    nullif(trim(e.area_code), '') as area_code,
    bcm.id as mapping_id
  into worker_row
  from public.employees_active_current e
  join public.buk_contract_mappings bcm
    on bcm.buk_area_name_normalized = public.normalize_buk_area_name(e.area_name)
   and bcm.is_operational = true
   and bcm.is_one_to_one = true
   and bcm.contract_id is not null
  join public.contracts c
    on c.id = bcm.contract_id
   and c.is_active = true
  where e.buk_employee_id = trim(coalesce(p_buk_employee_id, ''))
  limit 1;

  if worker_row.id is null then
    raise exception 'Trabajador BUK no encontrado o sin area operativa vinculada';
  end if;

  resolved_union_status := coalesce(worker_row.union_status, 'unknown');

  return jsonb_build_object(
    'worker', jsonb_build_object(
      'buk_employee_id', worker_row.buk_employee_id,
      'full_name', worker_row.full_name,
      'document_number', worker_row.document_number,
      'document_type', worker_row.document_type,
      'job_title', worker_row.job_title,
      'union_name', worker_row.union_name,
      'union_status', resolved_union_status,
      'union_status_label', public.get_hr_incentive_union_status_label(resolved_union_status),
      'union_joined_at', worker_row.union_joined_at,
      'primary_contract_code', worker_row.contract_code,
      'primary_area_name', worker_row.area_name,
      'primary_area_code', worker_row.area_code
    ),
    'available_areas',
    coalesce((
      with worker_identity as (
        select
          coalesce(nullif(trim(worker_row.document_type), ''), 'rut') as document_type,
          coalesce(
            nullif(regexp_replace(coalesce(worker_row.document_number, ''), '\D', '', 'g'), ''),
            worker_row.buk_employee_id
          ) as identity_value
      ),
      ranked_options as (
        select
          bcm.id as mapping_id,
          c.code as contract_code,
          bcm.buk_area_name as area_name,
          nullif(trim(e.area_code), '') as area_code,
          greatest(
            coalesce(e.updated_at, '-infinity'::timestamptz),
            coalesce(e.created_at, '-infinity'::timestamptz)
          ) as activity_at,
          case when bcm.id = worker_row.mapping_id then 0 else 1 end as option_rank,
          row_number() over (
            partition by bcm.id
            order by
              case when e.is_active then 0 else 1 end,
              e.updated_at desc nulls last,
              e.created_at desc nulls last
          ) as row_rank
        from public.employees e
        cross join worker_identity wi
        join public.buk_contract_mappings bcm
          on bcm.buk_area_name_normalized = public.normalize_buk_area_name(e.area_name)
         and bcm.is_operational = true
         and bcm.is_one_to_one = true
         and bcm.contract_id is not null
        join public.contracts c
          on c.id = bcm.contract_id
         and c.is_active = true
        where coalesce(nullif(trim(e.document_type), ''), 'rut') = wi.document_type
          and coalesce(
            nullif(regexp_replace(coalesce(e.document_number, ''), '\D', '', 'g'), ''),
            e.buk_employee_id
          ) = wi.identity_value
      )
      select jsonb_agg(
        jsonb_build_object(
          'contract_code', ro.contract_code,
          'area_name', ro.area_name,
          'area_code', ro.area_code,
          'label', concat_ws(' · ', coalesce(ro.contract_code, 'Sin código'), ro.area_name),
          'is_primary', ro.option_rank = 0
        )
        order by ro.option_rank asc, ro.activity_at desc nulls last, ro.contract_code nulls last, ro.area_name nulls last
      )
      from ranked_options ro
      where ro.row_rank = 1
    ), '[]'::jsonb)
  );
end;
$function$;

notify pgrst, 'reload schema';
