begin;

create sequence if not exists public.hiring_folio_seq start with 1 increment by 1;

create table if not exists public.hiring_approval_configs (
  id bigint generated by default as identity primary key,
  step_code text not null unique
    check (step_code in ('operational_approval', 'contracts_control')),
  step_name text not null,
  step_order integer not null unique,
  approver_user_id uuid not null references public.profiles (id) on delete restrict,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.hiring_request_approvals (
  id bigint generated by default as identity primary key,
  hiring_request_id uuid not null references public.hiring_requests (id) on delete cascade,
  step_code text not null
    check (step_code in ('requester_signature', 'operational_approval', 'contracts_control')),
  step_name text not null,
  step_order integer not null,
  approver_user_id uuid references public.profiles (id) on delete set null,
  approver_name text,
  approver_email text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  decided_at timestamptz,
  comments text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (hiring_request_id, step_code)
);

create index if not exists idx_hiring_approval_configs_user_id
  on public.hiring_approval_configs (approver_user_id);
create index if not exists idx_hiring_request_approvals_request_id
  on public.hiring_request_approvals (hiring_request_id);
create index if not exists idx_hiring_request_approvals_user_id
  on public.hiring_request_approvals (approver_user_id);
create index if not exists idx_hiring_request_approvals_status
  on public.hiring_request_approvals (status);

drop trigger if exists trg_hiring_approval_configs_set_updated_at on public.hiring_approval_configs;
create trigger trg_hiring_approval_configs_set_updated_at
before update on public.hiring_approval_configs
for each row execute function public.set_updated_at();

drop trigger if exists trg_hiring_request_approvals_set_updated_at on public.hiring_request_approvals;
create trigger trg_hiring_request_approvals_set_updated_at
before update on public.hiring_request_approvals
for each row execute function public.set_updated_at();

create or replace function public.refresh_hiring_request_status(target_request_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  has_rejection boolean;
  has_operational_step boolean;
  has_contracts_step boolean;
  has_pending boolean;
  all_required_approved boolean;
begin
  select exists (
    select 1
    from public.hiring_request_approvals
    where hiring_request_id = target_request_id
      and status = 'rejected'
  ) into has_rejection;

  if has_rejection then
    update public.hiring_requests
    set status = 'rechazada',
        updated_at = timezone('utc', now())
    where id = target_request_id;
    return;
  end if;

  select exists (
    select 1
    from public.hiring_request_approvals
    where hiring_request_id = target_request_id
      and step_code = 'operational_approval'
  ) into has_operational_step;

  select exists (
    select 1
    from public.hiring_request_approvals
    where hiring_request_id = target_request_id
      and step_code = 'contracts_control'
  ) into has_contracts_step;

  select exists (
    select 1
    from public.hiring_request_approvals
    where hiring_request_id = target_request_id
      and step_code in ('operational_approval', 'contracts_control')
      and status = 'pending'
  ) into has_pending;

  select coalesce(bool_and(status = 'approved'), false)
    from public.hiring_request_approvals
   where hiring_request_id = target_request_id
     and step_code in ('requester_signature', 'operational_approval', 'contracts_control')
  into all_required_approved;

  if not has_operational_step or not has_contracts_step or has_pending or not all_required_approved then
    update public.hiring_requests
    set status = 'pendiente',
        updated_at = timezone('utc', now())
    where id = target_request_id;
    return;
  end if;

  update public.hiring_requests
  set status = 'aprobada',
      updated_at = timezone('utc', now())
  where id = target_request_id;
end;
$$;

create or replace function public.handle_hiring_request_approval_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.refresh_hiring_request_status(coalesce(new.hiring_request_id, old.hiring_request_id));
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_hiring_request_approvals_refresh_status on public.hiring_request_approvals;
create trigger trg_hiring_request_approvals_refresh_status
after insert or update or delete on public.hiring_request_approvals
for each row execute function public.handle_hiring_request_approval_change();

create or replace function public.create_hiring_request(
  p_requested_entry_date date,
  p_job_position_id bigint,
  p_job_position_name text,
  p_vacancies integer,
  p_contract_id bigint,
  p_contract_name text,
  p_contract_number text,
  p_cost_unit text,
  p_cost_unit_name text,
  p_cost_center_code text,
  p_cost_center_name text,
  p_start_date date,
  p_end_date date,
  p_campamento boolean,
  p_pasajes boolean,
  p_other_benefits text,
  p_salary_offer numeric,
  p_shift_id bigint,
  p_shift_name text,
  p_requester_signed boolean default true
)
returns table (request_id uuid, folio text)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  requester_profile public.profiles%rowtype;
  next_folio text;
  created_request_id uuid;
  config_record record;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_can_access_module(current_user_id, 'solicitud_contrataciones') then
    raise exception 'El usuario no tiene acceso para crear solicitudes de contratación';
  end if;

  select *
    into requester_profile
    from public.profiles
   where id = current_user_id;

  if requester_profile.id is null then
    raise exception 'No existe perfil para el usuario autenticado';
  end if;

  next_folio := lpad(nextval('public.hiring_folio_seq')::text, 4, '0');

  insert into public.hiring_requests (
    folio,
    requester_id,
    requester_name,
    requester_job_title,
    requester_email,
    requested_entry_date,
    job_position_id,
    job_position_name,
    vacancies,
    contract_id,
    contract_name,
    contract_number,
    cost_unit,
    cost_unit_name,
    cost_center_code,
    cost_center_name,
    start_date,
    end_date,
    campamento,
    pasajes,
    other_benefits,
    salary_offer,
    shift_id,
    shift_name,
    requester_signed,
    status
  )
  values (
    next_folio,
    current_user_id,
    coalesce(requester_profile.full_name, requester_profile.email),
    requester_profile.job_title,
    requester_profile.email,
    p_requested_entry_date,
    p_job_position_id,
    p_job_position_name,
    p_vacancies,
    p_contract_id,
    p_contract_name,
    p_contract_number,
    p_cost_unit,
    p_cost_unit_name,
    p_cost_center_code,
    p_cost_center_name,
    p_start_date,
    p_end_date,
    p_campamento,
    p_pasajes,
    p_other_benefits,
    p_salary_offer,
    p_shift_id,
    p_shift_name,
    p_requester_signed,
    'pendiente'
  )
  returning id into created_request_id;

  insert into public.hiring_request_approvals (
    hiring_request_id,
    step_code,
    step_name,
    step_order,
    approver_user_id,
    approver_name,
    approver_email,
    status,
    decided_at
  )
  values (
    created_request_id,
    'requester_signature',
    'Firma solicitante',
    1,
    current_user_id,
    coalesce(requester_profile.full_name, requester_profile.email),
    requester_profile.email,
    case when p_requester_signed then 'approved' else 'pending' end,
    case when p_requester_signed then timezone('utc', now()) else null end
  );

  for config_record in
    select
      hac.step_code,
      hac.step_name,
      hac.step_order,
      p.id as approver_user_id,
      p.full_name,
      p.email
    from public.hiring_approval_configs hac
    join public.profiles p
      on p.id = hac.approver_user_id
    where hac.is_active = true
    order by hac.step_order
  loop
    insert into public.hiring_request_approvals (
      hiring_request_id,
      step_code,
      step_name,
      step_order,
      approver_user_id,
      approver_name,
      approver_email,
      status
    )
    values (
      created_request_id,
      config_record.step_code,
      config_record.step_name,
      config_record.step_order,
      config_record.approver_user_id,
      coalesce(config_record.full_name, config_record.email),
      config_record.email,
      'pending'
    )
    on conflict (hiring_request_id, step_code) do nothing;
  end loop;

  perform public.refresh_hiring_request_status(created_request_id);

  return query
  select created_request_id, next_folio;
end;
$$;

create or replace function public.decide_hiring_request_approval(
  p_approval_id bigint,
  p_decision text,
  p_comments text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  approval_record public.hiring_request_approvals%rowtype;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if p_decision not in ('approved', 'rejected') then
    raise exception 'Decisión inválida';
  end if;

  select *
    into approval_record
    from public.hiring_request_approvals
   where id = p_approval_id;

  if approval_record.id is null then
    raise exception 'No existe la aprobación solicitada';
  end if;

  if approval_record.step_code = 'requester_signature' then
    raise exception 'La firma del solicitante no se puede decidir por esta vía';
  end if;

  if approval_record.approver_user_id <> current_user_id and not public.user_is_admin(current_user_id) then
    raise exception 'El usuario no está autorizado para decidir esta aprobación';
  end if;

  update public.hiring_request_approvals
     set status = p_decision,
         comments = p_comments,
         decided_at = timezone('utc', now()),
         updated_at = timezone('utc', now())
   where id = p_approval_id;

  perform public.refresh_hiring_request_status(approval_record.hiring_request_id);

  return approval_record.hiring_request_id;
end;
$$;

alter table public.hiring_approval_configs enable row level security;
alter table public.hiring_request_approvals enable row level security;

drop policy if exists "hiring_approval_configs_select_operational" on public.hiring_approval_configs;
create policy "hiring_approval_configs_select_operational"
on public.hiring_approval_configs
for select
to authenticated
using (
  public.user_is_admin(auth.uid())
  or public.user_has_role(auth.uid(), 'reclutamiento')
  or public.user_has_role(auth.uid(), 'control_contratos')
);

drop policy if exists "hiring_approval_configs_manage_admin" on public.hiring_approval_configs;
create policy "hiring_approval_configs_manage_admin"
on public.hiring_approval_configs
for all
to authenticated
using (public.user_is_admin(auth.uid()))
with check (public.user_is_admin(auth.uid()));

drop policy if exists "hiring_request_approvals_select_visible" on public.hiring_request_approvals;
create policy "hiring_request_approvals_select_visible"
on public.hiring_request_approvals
for select
to authenticated
using (
  exists (
    select 1
    from public.hiring_requests hr
    where hr.id = hiring_request_id
      and (
        hr.requester_id = auth.uid()
        or public.user_is_admin(auth.uid())
        or public.user_has_role(auth.uid(), 'reclutamiento')
        or public.user_has_role(auth.uid(), 'control_contratos')
        or approver_user_id = auth.uid()
      )
  )
);

grant select on public.hiring_approval_configs to authenticated;
grant select on public.hiring_request_approvals to authenticated;
grant execute on function public.create_hiring_request(
  date,
  bigint,
  text,
  integer,
  bigint,
  text,
  text,
  text,
  text,
  text,
  text,
  date,
  date,
  boolean,
  boolean,
  text,
  numeric,
  bigint,
  text,
  boolean
) to authenticated;
grant execute on function public.decide_hiring_request_approval(bigint, text, text) to authenticated;

insert into public.hiring_approval_configs (step_code, step_name, step_order, approver_user_id, is_active)
select
  'operational_approval',
  'Aprobación operativa',
  2,
  id,
  false
from public.profiles
where email = 'maximiliano.contreras@busesjm.com'
on conflict (step_code) do nothing;

insert into public.hiring_approval_configs (step_code, step_name, step_order, approver_user_id, is_active)
select
  'contracts_control',
  'Control de contratos',
  3,
  id,
  false
from public.profiles
where email = 'maximiliano.contreras@busesjm.com'
on conflict (step_code) do nothing;

commit;
