-- EEES-DB-005: approved
-- owner: Explicit user request to replace Operations from zero; applied to production on 2026-09-30.
-- rollback: Recreate the prior module schema from migration history and restore only from a separately retained pre-change backup; intentionally deleted Operations records are otherwise unrecoverable.
begin;

-- Greenfield replacement: no module-owned legacy rows are copied into Atlas Operations.
create table public.atlas_ops_contract_editors (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  is_active boolean not null default true,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  unique(user_id, contract_id)
);

create table public.atlas_ops_service_templates (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.contracts(id) on delete restrict,
  name text not null,
  provider_name text,
  service_type text not null,
  contractual_name text,
  contractual_category text,
  schedule_label text,
  is_active boolean not null default true,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.atlas_ops_vehicles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  plate text,
  vehicle_type text,
  client_label text,
  brand text,
  model text,
  year text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.atlas_ops_dispatches (
  id uuid primary key default gen_random_uuid(),
  service_template_id bigint references public.atlas_ops_service_templates(id) on delete restrict,
  contract_id bigint not null references public.contracts(id) on delete restrict,
  service_date date not null,
  shift text not null,
  planned_start_at timestamptz,
  planned_end_at timestamptz,
  origin_label text,
  destination_label text,
  instructions text,
  driver_buk_employee_id text,
  driver_name_snapshot text,
  driver_document_snapshot text,
  vehicle_id uuid references public.atlas_ops_vehicles(id) on delete restrict,
  planning_status text not null default 'draft'
    check (planning_status in ('draft', 'planning', 'ready', 'published', 'cancelled')),
  execution_status text not null default 'not_started'
    check (execution_status in ('not_started', 'in_progress', 'completed', 'suspended', 'failed')),
  published_at timestamptz,
  acknowledged_at timestamptz,
  created_by uuid not null references public.profiles(id) on delete restrict,
  updated_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (planned_end_at is null or planned_start_at is null or planned_end_at > planned_start_at)
);

create index atlas_ops_dispatches_board_idx
  on public.atlas_ops_dispatches(service_date, contract_id, planning_status, execution_status);
create index atlas_ops_dispatches_driver_idx
  on public.atlas_ops_dispatches(driver_buk_employee_id, service_date desc);
create index atlas_ops_dispatches_vehicle_idx
  on public.atlas_ops_dispatches(vehicle_id, service_date desc);

create unique index atlas_ops_dispatch_schedule_unique
  on public.atlas_ops_dispatches(service_template_id, contract_id, service_date, shift, planned_start_at);

create table public.atlas_ops_milestone_templates (
  id uuid primary key default gen_random_uuid(),
  contract_id bigint not null references public.contracts(id) on delete cascade,
  service_template_id bigint references public.atlas_ops_service_templates(id) on delete cascade,
  version integer not null check (version > 0),
  code text not null,
  label text not null,
  offset_minutes integer not null,
  warning_before_minutes integer not null default 0 check (warning_before_minutes >= 0),
  required boolean not null default true,
  source text not null default 'coordinator'
    check (source in ('system', 'user', 'coordinator', 'driver', 'gps', 'tracktec', 'integration', 'import', 'mock')),
  geofence_type text check (geofence_type in ('workshop', 'posture', 'site', 'route')),
  is_active boolean not null default true,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(contract_id, service_template_id, version, code)
);

create table public.atlas_ops_dispatch_milestones (
  id uuid primary key default gen_random_uuid(),
  dispatch_id uuid not null references public.atlas_ops_dispatches(id) on delete cascade,
  template_id uuid references public.atlas_ops_milestone_templates(id) on delete set null,
  template_version integer,
  code text not null,
  label text not null,
  expected_at timestamptz not null,
  warning_at timestamptz,
  critical_at timestamptz not null,
  source_event_id text,
  delay_minutes integer generated always as (
    case when actual_at is null then null else floor(extract(epoch from (actual_at - expected_at)) / 60)::integer end
  ) stored,
  required boolean not null default true,
  source text not null,
  status text not null default 'pending' check (status in ('pending', 'completed', 'skipped')),
  actual_at timestamptz,
  created_at timestamptz not null default now(),
  unique(dispatch_id, code)
);

create index atlas_ops_dispatch_milestones_due_idx
  on public.atlas_ops_dispatch_milestones(critical_at, dispatch_id);

create table public.atlas_ops_dispatch_events (
  id uuid primary key default gen_random_uuid(),
  dispatch_id uuid not null references public.atlas_ops_dispatches(id) on delete cascade,
  milestone_id uuid references public.atlas_ops_dispatch_milestones(id) on delete set null,
  event_type text not null,
  source text not null
    check (source in ('system', 'user', 'coordinator', 'driver', 'gps', 'tracktec', 'integration', 'import', 'mock')),
  occurred_at timestamptz not null default now(),
  actor_user_id uuid references public.profiles(id) on delete set null,
  correlation_id uuid not null default gen_random_uuid(),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index atlas_ops_dispatch_events_timeline_idx
  on public.atlas_ops_dispatch_events(dispatch_id, occurred_at, id);

create table public.atlas_ops_driver_accounts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  buk_employee_id text not null unique,
  linked_by uuid not null references public.profiles(id) on delete restrict,
  linked_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table public.atlas_ops_telemetry_vehicle_bindings (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('tracktec', 'mock')),
  external_vehicle_id text not null,
  vehicle_id uuid not null references public.atlas_ops_vehicles(id) on delete restrict,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(provider, external_vehicle_id),
  unique(provider, vehicle_id)
);

create table public.atlas_ops_telemetry_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('tracktec', 'mock')),
  external_event_id text not null,
  external_vehicle_id text not null,
  binding_id uuid references public.atlas_ops_telemetry_vehicle_bindings(id) on delete restrict,
  vehicle_id uuid references public.atlas_ops_vehicles(id) on delete restrict,
  observed_at timestamptz not null,
  received_at timestamptz not null default now(),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  speed_kph double precision check (speed_kph between 0 and 350),
  heading_degrees double precision check (heading_degrees between 0 and 360),
  ignition boolean,
  odometer_km double precision check (odometer_km >= 0),
  accuracy_m double precision check (accuracy_m >= 0),
  event_type text,
  raw_reference text,
  payload_digest text not null,
  correlation_id uuid not null default gen_random_uuid(),
  processing_status text not null default 'unmatched'
    check (processing_status in ('unmatched', 'processed', 'rejected')),
  created_at timestamptz not null default now(),
  unique(provider, external_event_id)
);

create index atlas_ops_telemetry_vehicle_latest_idx
  on public.atlas_ops_telemetry_events(vehicle_id, observed_at desc);

create table public.atlas_ops_geofences (
  id uuid primary key default gen_random_uuid(),
  contract_id bigint not null references public.contracts(id) on delete cascade,
  code text not null,
  label text not null,
  geofence_type text not null check (geofence_type in ('workshop', 'posture', 'site', 'route')),
  center_latitude double precision not null check (center_latitude between -90 and 90),
  center_longitude double precision not null check (center_longitude between -180 and 180),
  radius_meters integer not null check (radius_meters between 25 and 100000),
  jitter_buffer_meters integer not null default 35 check (jitter_buffer_meters between 0 and 1000),
  min_transition_seconds integer not null default 30 check (min_transition_seconds between 0 and 3600),
  is_active boolean not null default true,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(contract_id, code)
);

create table public.atlas_ops_geofence_events (
  id uuid primary key default gen_random_uuid(),
  geofence_id uuid not null references public.atlas_ops_geofences(id) on delete restrict,
  telemetry_event_id uuid not null references public.atlas_ops_telemetry_events(id) on delete restrict,
  vehicle_id uuid not null references public.atlas_ops_vehicles(id) on delete restrict,
  transition text not null check (transition in ('enter', 'exit')),
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(geofence_id, telemetry_event_id)
);

create table public.atlas_ops_alerts (
  id uuid primary key default gen_random_uuid(),
  dispatch_id uuid not null references public.atlas_ops_dispatches(id) on delete cascade,
  milestone_id uuid references public.atlas_ops_dispatch_milestones(id) on delete cascade,
  alert_type text not null check (alert_type in ('attention', 'at_risk', 'critical', 'resource_conflict', 'incident')),
  status text not null default 'open' check (status in ('open', 'acknowledged', 'resolved')),
  message text not null,
  opened_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  acknowledged_by uuid references public.profiles(id) on delete set null,
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id) on delete set null,
  resolution_note text,
  unique(dispatch_id, milestone_id, alert_type)
);

create table public.atlas_ops_incidents (
  id uuid primary key default gen_random_uuid(),
  dispatch_id uuid not null references public.atlas_ops_dispatches(id) on delete cascade,
  category text not null,
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  description text not null check (length(trim(description)) between 5 and 2000),
  reported_by uuid not null references public.profiles(id) on delete restrict,
  source text not null check (source in ('driver', 'coordinator', 'integration')),
  status text not null default 'open' check (status in ('open', 'investigating', 'resolved')),
  resolution_note text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id) on delete set null
);

create index atlas_ops_incidents_open_idx on public.atlas_ops_incidents(status, created_at desc);

-- New authorization boundary; contract editors remain explicit and row scoped.
create or replace function public.atlas_ops_is_current_super_admin()
returns boolean language sql stable security definer set search_path = public
as $$
  select auth.uid() is not null and exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.status = 'active' and p.is_super_admin = true
  )
$$;
revoke all on function public.atlas_ops_is_current_super_admin() from public, anon;
grant execute on function public.atlas_ops_is_current_super_admin() to authenticated;

create or replace function public.atlas_ops_can_manage(requested_user_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select requested_user_id is not null
     and auth.uid() is not null
     and auth.uid() = requested_user_id
     and public.atlas_ops_is_current_super_admin()
$$;

create or replace function public.atlas_ops_can_edit_contract(requested_user_id uuid, requested_contract_id bigint)
returns boolean language plpgsql stable security definer set search_path = public
as $function$
begin
  if requested_user_id is null or requested_contract_id is null or auth.uid() is null then return false; end if;
  if auth.uid() <> requested_user_id or not public.atlas_ops_is_current_super_admin() then return false; end if;
  return exists(select 1 from public.contracts c where c.id = requested_contract_id and c.is_active);
end;
$function$;

revoke all on function public.atlas_ops_can_manage(uuid) from public, anon;
revoke all on function public.atlas_ops_can_edit_contract(uuid, bigint) from public, anon;
grant execute on function public.atlas_ops_can_manage(uuid) to authenticated;
grant execute on function public.atlas_ops_can_edit_contract(uuid, bigint) to authenticated;

do $$
declare t text; predicate text;
begin
  foreach t in array array[
    'atlas_ops_contract_editors','atlas_ops_service_templates','atlas_ops_vehicles','atlas_ops_dispatches',
    'atlas_ops_milestone_templates','atlas_ops_dispatch_milestones','atlas_ops_dispatch_events',
    'atlas_ops_driver_accounts','atlas_ops_telemetry_vehicle_bindings','atlas_ops_telemetry_events',
    'atlas_ops_geofences','atlas_ops_geofence_events','atlas_ops_alerts','atlas_ops_incidents'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from public, anon, authenticated', t);
    execute format('grant select on table public.%I to authenticated', t);
    predicate := case t
      when 'atlas_ops_contract_editors' then 'public.atlas_ops_is_current_super_admin()'
      when 'atlas_ops_service_templates' then 'public.atlas_ops_can_edit_contract((select auth.uid()), contract_id)'
      when 'atlas_ops_vehicles' then 'public.atlas_ops_can_manage((select auth.uid()))'
      when 'atlas_ops_dispatches' then 'public.atlas_ops_can_edit_contract((select auth.uid()), contract_id)'
      when 'atlas_ops_milestone_templates' then 'public.atlas_ops_can_edit_contract((select auth.uid()), contract_id)'
      when 'atlas_ops_driver_accounts' then 'public.atlas_ops_is_current_super_admin()'
      when 'atlas_ops_telemetry_vehicle_bindings' then 'public.atlas_ops_is_current_super_admin()'
      when 'atlas_ops_telemetry_events' then 'public.atlas_ops_is_current_super_admin()'
      when 'atlas_ops_geofences' then 'public.atlas_ops_is_current_super_admin()'
      when 'atlas_ops_geofence_events' then 'public.atlas_ops_is_current_super_admin()'
      else format('exists (select 1 from public.atlas_ops_dispatches d where d.id = %I.dispatch_id and public.atlas_ops_can_edit_contract((select auth.uid()), d.contract_id))', t)
    end;
    execute format('create policy %I on public.%I for select to authenticated using (%s)', t || '_select', t, predicate);
  end loop;
end $$;

-- Only security-definer RPCs may mutate Atlas Operations data; grants are scoped to this domain.
grant select on public.atlas_ops_contract_editors, public.atlas_ops_service_templates, public.atlas_ops_vehicles,
  public.atlas_ops_dispatches, public.atlas_ops_milestone_templates, public.atlas_ops_dispatch_milestones,
  public.atlas_ops_dispatch_events, public.atlas_ops_driver_accounts, public.atlas_ops_telemetry_vehicle_bindings,
  public.atlas_ops_telemetry_events, public.atlas_ops_geofences, public.atlas_ops_geofence_events,
  public.atlas_ops_alerts, public.atlas_ops_incidents to authenticated;

-- Remove the old implementation and its data. Shared contracts, BUK, roster, auth and roles stay intact.
drop view if exists public.operations_editable_contracts;
drop policy if exists operations_base_services_select on public.base_services;
drop policy if exists operations_equipment_select on public.equipment;
drop policy if exists operations_service_entries_select on public.service_entries;
drop function if exists public.submit_service_entries_batch(jsonb);
drop function if exists public.prepare_operations_service_entry_batch(jsonb, uuid);
drop function if exists public.resolve_operations_driver_candidates(text, text, text);
drop function if exists public.user_can_edit_operations_contract(uuid, bigint);
revoke all on function public.map_operations_driver_shift_status(text) from public, anon, authenticated;
drop function if exists public.map_operations_driver_shift_status(text);
drop function if exists public.search_operations_drivers(text, date, integer);
drop table public.service_entries;
drop table public.base_services;
drop table public.equipment;
drop table public.operations_contract_editors;
drop function if exists public.user_can_manage_operations(uuid);

-- The temporary access scope requested for production is superadmin-only.
delete from public.role_module_access where module_code = 'operaciones';

-- Remove legacy data grants and replace the old role helper with the new authorization contract.
drop function if exists public.user_can_manage_operations(uuid);
create function public.user_can_manage_operations(requested_user_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select public.atlas_ops_can_manage(requested_user_id) $$;
revoke all on function public.user_can_manage_operations(uuid) from public, anon;
grant execute on function public.user_can_manage_operations(uuid) to authenticated;

create or replace function public.atlas_ops_search_drivers(p_search text, p_service_date date, p_limit integer default 12)
returns table (
  buk_employee_id text, full_name text, document_number text, document_type text, job_title text,
  contract_code text, area_name text, display_label text, roster_base_status text,
  roster_effective_status text, is_working_day boolean, is_rest_day boolean
)
language plpgsql security definer set search_path = public
as $function$
declare
  normalized_search text := lower(trim(coalesce(p_search, '')));
  normalized_digits text := public.build_employee_document_digits(p_search, '{}'::jsonb);
  safe_limit integer := least(greatest(coalesce(p_limit, 12), 1), 30);
begin
  if not public.atlas_ops_is_current_super_admin() then raise exception 'Solo un superadministrador puede buscar conductores.'; end if;
  if length(normalized_search) < 2 and length(normalized_digits) < 4 then return; end if;
  return query
  with matched as (
    select e.buk_employee_id, e.full_name,
      coalesce(nullif(trim(e.document_number), ''), nullif(trim(e.raw_payload->>'document_number'), ''), nullif(trim(e.raw_payload->>'rut'), '')) as resolved_document,
      coalesce(nullif(trim(e.document_type), ''), nullif(trim(e.raw_payload->>'document_type'), ''), 'rut') as resolved_document_type,
      public.resolve_active_employee_job_title(e.raw_payload, e.job_title) as resolved_job_title,
      nullif(trim(e.contract_code), '') as resolved_contract_code,
      nullif(trim(e.area_name), '') as resolved_area_name,
      public.build_active_employee_search_text(e.full_name, e.document_number, e.job_title, e.contract_code, e.area_name, e.raw_payload) as search_text,
      public.build_employee_document_digits(e.document_number, e.raw_payload) as document_digits,
      rs.base_status as roster_base_status,
      rs.effective_status as roster_effective_status,
      rs.is_working_day,
      rs.is_rest_day
    from public.employees e
    cross join lateral public.resolve_hr_roster_day_status(
      e.buk_employee_id, coalesce(p_service_date, current_date)
    ) rs
    where e.is_active = true
  ), eligible as (
    select *, case
      when normalized_search <> '' and search_text like normalized_search || '%' then 0
      when normalized_digits <> '' and document_digits like normalized_digits || '%' then 1
      else 2 end as search_rank
    from matched
    where (normalized_search <> '' and search_text like '%' || normalized_search || '%')
       or (normalized_digits <> '' and document_digits like '%' || normalized_digits || '%')
  )
  select e.buk_employee_id, e.full_name, e.resolved_document, e.resolved_document_type, e.resolved_job_title,
    e.resolved_contract_code, e.resolved_area_name,
    concat_ws(' | ', coalesce(e.resolved_document, 'Sin RUT'), coalesce(e.resolved_job_title, 'Sin cargo'), e.full_name,
      coalesce(e.resolved_area_name, e.resolved_contract_code, 'Sin contrato')),
    e.roster_base_status, e.roster_effective_status, e.is_working_day, e.is_rest_day
  from eligible e
  order by e.search_rank, e.full_name
  limit safe_limit;
end;
$function$;
revoke all on function public.atlas_ops_search_drivers(text, date, integer) from public, anon;
grant execute on function public.atlas_ops_search_drivers(text, date, integer) to authenticated;

create or replace function public.atlas_ops_create_dispatch(p_payload jsonb)
returns uuid language plpgsql security definer set search_path = public
as $function$
declare
  actor uuid := auth.uid();
  contract_key bigint := nullif(p_payload->>'contract_id','')::bigint;
  template_key bigint := nullif(p_payload->>'service_template_id','')::bigint;
  start_at timestamptz := nullif(p_payload->>'planned_start_at','')::timestamptz;
  end_at timestamptz := nullif(p_payload->>'planned_end_at','')::timestamptz;
  driver_key text := nullif(trim(p_payload->>'driver_buk_employee_id'),'');
  vehicle_key uuid := nullif(p_payload->>'vehicle_id','')::uuid;
  dispatch_key uuid;
  driver_row record;
begin
  if actor is null or not public.atlas_ops_can_edit_contract(actor, contract_key) then raise exception 'Sin permiso de edición para el contrato.'; end if;
  if start_at is null or nullif(trim(p_payload->>'shift'),'') is null then raise exception 'Fecha/hora y turno son obligatorios.'; end if;
  if template_key is not null and not exists (
    select 1 from public.atlas_ops_service_templates t where t.id = template_key and t.contract_id = contract_key and t.is_active
  ) then raise exception 'El servicio no está activo en el contrato indicado.'; end if;
  if vehicle_key is not null and not exists (select 1 from public.atlas_ops_vehicles v where v.id = vehicle_key and v.is_active) then
    raise exception 'El vehículo no está activo.';
  end if;
  if driver_key is not null then
    select e.buk_employee_id, e.full_name, e.document_number, e.is_active, e.contract_code
    into driver_row from public.employees e where e.buk_employee_id = driver_key and e.is_active = true;
    if not found then raise exception 'La ficha BUK exacta no está activa.'; end if;
    if driver_row.contract_code is distinct from (select c.code from public.contracts c where c.id = contract_key and c.is_active) then
      raise exception 'La ficha BUK activa no corresponde al contrato seleccionado.';
    end if;
    if not exists (
      select 1 from public.resolve_hr_roster_day_status(driver_key, (start_at at time zone 'America/Santiago')::date) rs
      where coalesce(rs.is_working_day, false) and not coalesce(rs.is_rest_day, false)
    ) then raise exception 'La jornada BUK no habilita este conductor para la fecha del servicio.'; end if;
  end if;

  insert into public.atlas_ops_dispatches(
    service_template_id, contract_id, service_date, shift, planned_start_at, planned_end_at,
    origin_label, destination_label, instructions, driver_buk_employee_id, driver_name_snapshot, driver_document_snapshot,
    vehicle_id, planning_status, created_by, updated_by
  ) values (
    template_key, contract_key, (start_at at time zone 'America/Santiago')::date, trim(p_payload->>'shift'),
    start_at, end_at, nullif(trim(p_payload->>'origin_label'), ''), nullif(trim(p_payload->>'destination_label'), ''),
    nullif(trim(p_payload->>'instructions'), ''), driver_key, case when driver_key is null then null else driver_row.full_name end,
    case when driver_key is null then null else driver_row.document_number end,
    vehicle_key, 'planning', actor, actor
  ) returning id into dispatch_key;

  insert into public.atlas_ops_dispatch_events(dispatch_id, event_type, source, actor_user_id, payload)
  values (dispatch_key, 'dispatch.created', 'coordinator', actor, jsonb_build_object('contract_id', contract_key));

  if template_key is not null then
    insert into public.atlas_ops_dispatch_milestones(
      dispatch_id, template_id, template_version, code, label, expected_at, warning_at, critical_at, required, source
    )
    select dispatch_key, mt.id, mt.version, mt.code, mt.label,
           start_at + make_interval(mins => mt.offset_minutes),
           start_at + make_interval(mins => mt.offset_minutes - mt.warning_before_minutes),
           start_at + make_interval(mins => mt.offset_minutes), mt.required, mt.source
    from public.atlas_ops_milestone_templates mt
    where mt.contract_id = contract_key and mt.is_active and (mt.service_template_id = template_key or mt.service_template_id is null)
    order by mt.service_template_id desc nulls last, mt.version desc
    on conflict (dispatch_id, code) do nothing;
  end if;
  return dispatch_key;
end;
$function$;
revoke all on function public.atlas_ops_create_dispatch(jsonb) from public, anon;
grant execute on function public.atlas_ops_create_dispatch(jsonb) to authenticated;

create or replace function public.atlas_ops_transition_dispatch(p_dispatch_id uuid, p_transition text)
returns void language plpgsql security definer set search_path = public
as $function$
declare d public.atlas_ops_dispatches%rowtype; actor uuid := auth.uid();
begin
  select * into d from public.atlas_ops_dispatches where id = p_dispatch_id for update;
  if not found then raise exception 'Servicio no encontrado.'; end if;
  if actor is null or not public.atlas_ops_can_edit_contract(actor, d.contract_id) then raise exception 'Sin permisos para modificar este servicio.'; end if;
  if p_transition = 'ready' then
    if d.planning_status not in ('draft','planning') or d.service_template_id is null or d.driver_buk_employee_id is null or d.vehicle_id is null or d.planned_start_at is null then
      raise exception 'El servicio requiere plantilla, conductor, vehículo y horario antes de quedar listo.';
    end if;
    if not exists (
      select 1 from public.employees e
      where e.buk_employee_id = d.driver_buk_employee_id and e.is_active
        and e.contract_code = (select c.code from public.contracts c where c.id = d.contract_id and c.is_active)
    ) or not exists (
      select 1 from public.resolve_hr_roster_day_status(d.driver_buk_employee_id, d.service_date) rs
      where coalesce(rs.is_working_day, false) and not coalesce(rs.is_rest_day, false)
    ) then raise exception 'La ficha BUK ya no cumple actividad, contrato y jornada para la fecha del servicio.'; end if;
    if not exists (select 1 from public.atlas_ops_vehicles v where v.id=d.vehicle_id and v.is_active) then raise exception 'El vehículo ya no está activo.'; end if;
    update public.atlas_ops_dispatches set planning_status = 'ready', updated_by = actor where id = d.id;
  elsif p_transition = 'publish' then
    if d.planning_status <> 'ready' then raise exception 'Solo se pueden publicar servicios listos.'; end if;
    if exists (
      select 1 from public.atlas_ops_dispatches other
      where other.id <> d.id and other.service_date = d.service_date
        and other.planning_status in ('ready','published')
        and d.planned_start_at < coalesce(other.planned_end_at, other.planned_start_at + interval '1 day')
        and other.planned_start_at < coalesce(d.planned_end_at, d.planned_start_at + interval '1 day')
        and (other.driver_buk_employee_id = d.driver_buk_employee_id or other.vehicle_id = d.vehicle_id)
    ) then raise exception 'Existe un conflicto horario de conductor o vehículo.'; end if;
    update public.atlas_ops_dispatches set planning_status = 'published', published_at = now(), updated_by = actor where id = d.id;
  elsif p_transition = 'cancel' then
    if d.planning_status = 'cancelled' or d.execution_status in ('completed','failed') then raise exception 'Transición de cancelación no permitida.'; end if;
    update public.atlas_ops_dispatches set planning_status = 'cancelled', updated_by = actor where id = d.id;
  elsif p_transition = 'start' then
    if d.planning_status <> 'published' or d.acknowledged_at is null or d.execution_status <> 'not_started' then raise exception 'El servicio debe estar publicado y confirmado.'; end if;
    update public.atlas_ops_dispatches set execution_status = 'in_progress', updated_by = actor where id = d.id;
  elsif p_transition = 'complete' then
    if d.execution_status <> 'in_progress' then raise exception 'Solo se puede completar un servicio en ejecución.'; end if;
    update public.atlas_ops_dispatches set execution_status = 'completed', updated_by = actor where id = d.id;
  else raise exception 'Transición de servicio desconocida.';
  end if;
  insert into public.atlas_ops_dispatch_events(dispatch_id, event_type, source, actor_user_id, payload)
  values (d.id, 'dispatch.' || p_transition, 'coordinator', actor, '{}'::jsonb);
end;
$function$;
revoke all on function public.atlas_ops_transition_dispatch(uuid, text) from public, anon;
grant execute on function public.atlas_ops_transition_dispatch(uuid, text) to authenticated;

create or replace function public.atlas_ops_bind_driver_account(p_account_user_id uuid, p_buk_employee_id text)
returns void language plpgsql security definer set search_path = public
as $function$
begin
  if not public.atlas_ops_is_current_super_admin() then raise exception 'Solo un superadministrador puede vincular una identidad de conductor.'; end if;
  if not exists (select 1 from public.profiles p where p.id = p_account_user_id and p.status = 'active') then raise exception 'La cuenta Atlas debe estar activa.'; end if;
  if not exists (select 1 from public.employees e where e.buk_employee_id = p_buk_employee_id and e.is_active) then
    raise exception 'La ficha BUK exacta no está activa.';
  end if;
  insert into public.atlas_ops_driver_accounts(user_id, buk_employee_id, linked_by)
  values (p_account_user_id, p_buk_employee_id, auth.uid())
  on conflict (user_id) do update set buk_employee_id = excluded.buk_employee_id, linked_by = excluded.linked_by, linked_at = now(), is_active = true;
end;
$function$;
revoke all on function public.atlas_ops_bind_driver_account(uuid, text) from public, anon;
grant execute on function public.atlas_ops_bind_driver_account(uuid, text) to authenticated;

create or replace function public.atlas_ops_set_contract_editor(p_account_user_id uuid, p_contract_id bigint, p_is_active boolean default true)
returns void language plpgsql security definer set search_path = public
as $function$
begin
  if not public.atlas_ops_is_current_super_admin() then raise exception 'Solo un superadministrador puede asignar contratos operacionales.'; end if;
  if p_account_user_id is null or not exists(select 1 from public.profiles p where p.id=p_account_user_id and p.status='active') then
    raise exception 'La cuenta seleccionada no está activa.';
  end if;
  if not exists(select 1 from public.contracts c where c.id=p_contract_id and c.is_active) then raise exception 'El contrato no está activo.'; end if;
  if p_is_active and not (public.user_has_role(p_account_user_id,'operaciones_l_1') or public.user_has_role(p_account_user_id,'operaciones_l_2')) then
    raise exception 'El usuario debe tener el rol Operaciones L1 o L2.';
  end if;
  insert into public.atlas_ops_contract_editors(user_id,contract_id,is_active,reason,created_by,updated_by)
  values(p_account_user_id,p_contract_id,p_is_active,'Configurado desde Atlas Operations',auth.uid(),auth.uid())
  on conflict(user_id,contract_id) do update set is_active=excluded.is_active,updated_by=auth.uid(),updated_at=now();
end;
$function$;
revoke all on function public.atlas_ops_set_contract_editor(uuid, bigint, boolean) from public, anon;
grant execute on function public.atlas_ops_set_contract_editor(uuid, bigint, boolean) to authenticated;

create or replace function public.atlas_ops_driver_acknowledge(p_dispatch_id uuid)
returns void language plpgsql security definer set search_path = public
as $function$
declare d public.atlas_ops_dispatches%rowtype; buk_id text;
begin
  select a.buk_employee_id into buk_id from public.atlas_ops_driver_accounts a
  where a.user_id = auth.uid() and a.is_active;
  if buk_id is null then raise exception 'La cuenta no tiene una identidad de conductor vinculada.'; end if;
  select * into d from public.atlas_ops_dispatches where id = p_dispatch_id and driver_buk_employee_id = buk_id for update;
  if not found or d.planning_status <> 'published' then raise exception 'Servicio publicado no encontrado para este conductor.'; end if;
  if d.acknowledged_at is null then
    update public.atlas_ops_dispatches set acknowledged_at = now(), updated_by = auth.uid() where id = d.id;
    insert into public.atlas_ops_dispatch_events(dispatch_id, event_type, source, actor_user_id)
    values (d.id, 'driver.acknowledged', 'driver', auth.uid());
  end if;
end;
$function$;
revoke all on function public.atlas_ops_driver_acknowledge(uuid) from public, anon;
grant execute on function public.atlas_ops_driver_acknowledge(uuid) to authenticated;

create or replace function public.atlas_ops_driver_mark_milestone(p_dispatch_id uuid, p_milestone_code text)
returns void language plpgsql security definer set search_path = public
as $function$
declare buk_id text; d public.atlas_ops_dispatches%rowtype; m public.atlas_ops_dispatch_milestones%rowtype;
begin
  select a.buk_employee_id into buk_id from public.atlas_ops_driver_accounts a
  where a.user_id = auth.uid() and a.is_active;
  if buk_id is null then raise exception 'La cuenta no tiene una identidad de conductor vinculada.'; end if;
  select * into d from public.atlas_ops_dispatches where id=p_dispatch_id and driver_buk_employee_id=buk_id for update;
  if not found or d.planning_status <> 'published' or d.execution_status not in ('not_started','in_progress') then raise exception 'Servicio activo no encontrado para este conductor.'; end if;
  select * into m from public.atlas_ops_dispatch_milestones where dispatch_id=d.id and code=upper(trim(p_milestone_code)) for update;
  if not found or m.status <> 'pending' then raise exception 'Hito pendiente no encontrado.'; end if;
  update public.atlas_ops_dispatch_milestones set status='completed', actual_at=now() where id=m.id;
  insert into public.atlas_ops_dispatch_events(dispatch_id,milestone_id,event_type,source,actor_user_id)
  values(d.id,m.id,'milestone.completed','driver',auth.uid());
end;
$function$;
revoke all on function public.atlas_ops_driver_mark_milestone(uuid, text) from public, anon;
grant execute on function public.atlas_ops_driver_mark_milestone(uuid, text) to authenticated;

create or replace function public.atlas_ops_driver_get_dispatches()
returns table(
  id uuid, service_date date, shift text, planned_start_at timestamptz, origin_label text, destination_label text,
  instructions text, acknowledged_at timestamptz, service_name text, vehicle_code text, plate text
) language plpgsql security definer set search_path = public
as $function$
declare buk_id text;
begin
  select a.buk_employee_id into buk_id from public.atlas_ops_driver_accounts a
  where a.user_id = auth.uid() and a.is_active;
  if buk_id is null then raise exception 'La cuenta no tiene una identidad de conductor vinculada.'; end if;
  return query select d.id, d.service_date, d.shift, d.planned_start_at, d.origin_label, d.destination_label,
    d.instructions, d.acknowledged_at, t.name, v.code, v.plate
  from public.atlas_ops_dispatches d
  left join public.atlas_ops_service_templates t on t.id=d.service_template_id
  left join public.atlas_ops_vehicles v on v.id=d.vehicle_id
  where d.driver_buk_employee_id = buk_id
    and d.planning_status = 'published'
    and d.service_date >= current_date - 1
  order by d.planned_start_at;
end;
$function$;
revoke all on function public.atlas_ops_driver_get_dispatches() from public, anon;
grant execute on function public.atlas_ops_driver_get_dispatches() to authenticated;

create or replace function public.atlas_ops_driver_report_incident(
  p_dispatch_id uuid, p_category text, p_severity text, p_description text
)
returns uuid language plpgsql security definer set search_path = public
as $function$
declare buk_id text; d public.atlas_ops_dispatches%rowtype; incident_id uuid;
begin
  select a.buk_employee_id into buk_id from public.atlas_ops_driver_accounts a
  where a.user_id = auth.uid() and a.is_active;
  if buk_id is null then raise exception 'La cuenta no tiene una identidad de conductor vinculada.'; end if;
  select * into d from public.atlas_ops_dispatches where id = p_dispatch_id and driver_buk_employee_id = buk_id for update;
  if not found or d.planning_status <> 'published' or d.execution_status in ('completed','failed','suspended') then
    raise exception 'Servicio activo no encontrado para este conductor.';
  end if;
  insert into public.atlas_ops_incidents(dispatch_id, category, severity, description, reported_by, source)
  values (d.id, nullif(trim(p_category), ''), p_severity, trim(p_description), auth.uid(), 'driver')
  returning id into incident_id;
  if not exists (select 1 from public.atlas_ops_alerts a where a.dispatch_id=d.id and a.alert_type='incident' and a.status='open') then
    insert into public.atlas_ops_alerts(dispatch_id, alert_type, message)
    values (d.id, 'incident', 'Incidencia reportada por el conductor');
  end if;
  insert into public.atlas_ops_dispatch_events(dispatch_id, event_type, source, actor_user_id, payload)
  values (d.id, 'incident.reported', 'driver', auth.uid(), jsonb_build_object('incident_id', incident_id, 'category', p_category, 'severity', p_severity));
  return incident_id;
end;
$function$;
revoke all on function public.atlas_ops_driver_report_incident(uuid, text, text, text) from public, anon;
grant execute on function public.atlas_ops_driver_report_incident(uuid, text, text, text) to authenticated;

create or replace function public.atlas_ops_record_milestone(
  p_dispatch_id uuid, p_milestone_code text, p_source text default 'coordinator', p_occurred_at timestamptz default now()
)
returns void language plpgsql security definer set search_path = public
as $function$
declare d public.atlas_ops_dispatches%rowtype; m public.atlas_ops_dispatch_milestones%rowtype; actor uuid := auth.uid();
begin
  select * into d from public.atlas_ops_dispatches where id = p_dispatch_id for update;
  if not found then raise exception 'Servicio no encontrado.'; end if;
  if actor is null or not public.atlas_ops_can_edit_contract(actor, d.contract_id) then raise exception 'Sin permisos para registrar el hito.'; end if;
  if p_source not in ('coordinator','user','integration') then raise exception 'Origen no permitido para registro manual.'; end if;
  select * into m from public.atlas_ops_dispatch_milestones
    where dispatch_id = d.id and code = p_milestone_code for update;
  if not found or m.status <> 'pending' then raise exception 'Hito pendiente no encontrado.'; end if;
  update public.atlas_ops_dispatch_milestones set status = 'completed', actual_at = p_occurred_at where id = m.id;
  insert into public.atlas_ops_dispatch_events(dispatch_id, milestone_id, event_type, source, occurred_at, actor_user_id)
  values (d.id, m.id, 'milestone.completed', p_source, p_occurred_at, actor);
  update public.atlas_ops_alerts set status = 'resolved', resolved_at = now(), resolved_by = actor, resolution_note = 'Hito completado'
  where milestone_id = m.id and status = 'open';
end;
$function$;
revoke all on function public.atlas_ops_record_milestone(uuid, text, text, timestamptz) from public, anon;
grant execute on function public.atlas_ops_record_milestone(uuid, text, text, timestamptz) to authenticated;

create or replace function public.atlas_ops_save_service_template(p_payload jsonb)
returns bigint language plpgsql security definer set search_path = public
as $function$
declare actor uuid := auth.uid(); contract_key bigint := (p_payload->>'contract_id')::bigint; template_id bigint;
begin
  if actor is null or not public.atlas_ops_can_edit_contract(actor, contract_key) then raise exception 'Sin permiso de edición para el contrato.'; end if;
  insert into public.atlas_ops_service_templates(contract_id, name, provider_name, service_type, contractual_name, contractual_category, schedule_label)
  values (contract_key, trim(p_payload->>'name'), nullif(trim(p_payload->>'provider_name'), ''), trim(p_payload->>'service_type'),
          nullif(trim(p_payload->>'contractual_name'), ''), nullif(trim(p_payload->>'contractual_category'), ''), nullif(trim(p_payload->>'schedule_label'), ''))
  returning id into template_id;
  return template_id;
end;
$function$;
revoke all on function public.atlas_ops_save_service_template(jsonb) from public, anon;
grant execute on function public.atlas_ops_save_service_template(jsonb) to authenticated;

create or replace function public.atlas_ops_save_milestone_template(p_payload jsonb)
returns uuid language plpgsql security definer set search_path = public
as $function$
declare actor uuid := auth.uid(); contract_key bigint := (p_payload->>'contract_id')::bigint; next_version integer; template_id uuid;
begin
  if actor is null or not public.atlas_ops_can_edit_contract(actor, contract_key) then raise exception 'Sin permiso de edición para el contrato.'; end if;
  select coalesce(max(version),0) + 1 into next_version from public.atlas_ops_milestone_templates
    where contract_id = contract_key and code = upper(trim(p_payload->>'code'))
      and service_template_id is not distinct from nullif(p_payload->>'service_template_id','')::bigint;
  insert into public.atlas_ops_milestone_templates(
    contract_id, service_template_id, version, code, label, offset_minutes, warning_before_minutes, required, source, geofence_type, created_by
  ) values (
    contract_key, nullif(p_payload->>'service_template_id','')::bigint, next_version, upper(trim(p_payload->>'code')),
    trim(p_payload->>'label'), (p_payload->>'offset_minutes')::integer,
    coalesce((p_payload->>'warning_before_minutes')::integer,0), coalesce((p_payload->>'required')::boolean,true),
    coalesce(p_payload->>'source','coordinator'), nullif(p_payload->>'geofence_type',''), actor
  ) returning id into template_id;
  update public.atlas_ops_milestone_templates set is_active = false
   where contract_id = contract_key and code = upper(trim(p_payload->>'code'))
     and service_template_id is not distinct from nullif(p_payload->>'service_template_id','')::bigint
     and id <> template_id and is_active;
  return template_id;
end;
$function$;
revoke all on function public.atlas_ops_save_milestone_template(jsonb) from public, anon;
grant execute on function public.atlas_ops_save_milestone_template(jsonb) to authenticated;

create or replace function public.atlas_ops_save_vehicle(p_payload jsonb)
returns uuid language plpgsql security definer set search_path = public
as $function$
declare actor uuid := auth.uid(); vehicle_key uuid := nullif(p_payload->>'id','')::uuid; result_id uuid;
begin
  if actor is null or not public.atlas_ops_is_current_super_admin() then raise exception 'Solo un superadministrador puede mantener el padrón de vehículos.'; end if;
  if vehicle_key is null then
    insert into public.atlas_ops_vehicles(code, plate, vehicle_type, client_label, brand, model, year)
    values (upper(trim(p_payload->>'code')), nullif(trim(p_payload->>'plate'),''), nullif(trim(p_payload->>'vehicle_type'),''),
            nullif(trim(p_payload->>'client_label'),''), nullif(trim(p_payload->>'brand'),''), nullif(trim(p_payload->>'model'),''), nullif(trim(p_payload->>'year'),''))
    returning id into result_id;
  else
    update public.atlas_ops_vehicles set code = upper(trim(p_payload->>'code')), plate = nullif(trim(p_payload->>'plate'),''),
      vehicle_type = nullif(trim(p_payload->>'vehicle_type'),''), client_label = nullif(trim(p_payload->>'client_label'),''),
      brand = nullif(trim(p_payload->>'brand'),''), model = nullif(trim(p_payload->>'model'),''), year = nullif(trim(p_payload->>'year'),''),
      is_active = coalesce((p_payload->>'is_active')::boolean,true), updated_at = now()
    where id = vehicle_key returning id into result_id;
    if result_id is null then raise exception 'Vehículo no encontrado.'; end if;
  end if;
  return result_id;
end;
$function$;
revoke all on function public.atlas_ops_save_vehicle(jsonb) from public, anon;
grant execute on function public.atlas_ops_save_vehicle(jsonb) to authenticated;

create or replace function public.atlas_ops_bind_tracktec_vehicle(p_vehicle_id uuid, p_external_vehicle_id text)
returns uuid language plpgsql security definer set search_path = public
as $function$
declare binding_id uuid;
begin
  if not public.atlas_ops_is_current_super_admin() then raise exception 'Solo un superadministrador puede vincular TrackTec.'; end if;
  if nullif(trim(p_external_vehicle_id),'') is null or not exists (select 1 from public.atlas_ops_vehicles where id = p_vehicle_id and is_active) then
    raise exception 'El vehículo o identificador externo no es válido.';
  end if;
  insert into public.atlas_ops_telemetry_vehicle_bindings(provider, external_vehicle_id, vehicle_id, created_by)
  values ('tracktec', trim(p_external_vehicle_id), p_vehicle_id, auth.uid())
  returning id into binding_id;
  return binding_id;
end;
$function$;
revoke all on function public.atlas_ops_bind_tracktec_vehicle(uuid, text) from public, anon;
grant execute on function public.atlas_ops_bind_tracktec_vehicle(uuid, text) to authenticated;

create or replace function public.atlas_ops_bind_mock_vehicle(p_vehicle_id uuid, p_external_vehicle_id text)
returns uuid language plpgsql security definer set search_path = public
as $function$
declare binding_id uuid;
begin
  if not public.atlas_ops_is_current_super_admin() then raise exception 'Solo un superadministrador puede vincular el simulador.'; end if;
  if nullif(trim(p_external_vehicle_id),'') is null or not exists (select 1 from public.atlas_ops_vehicles where id=p_vehicle_id and is_active) then
    raise exception 'El vehículo o identificador mock no es válido.';
  end if;
  insert into public.atlas_ops_telemetry_vehicle_bindings(provider,external_vehicle_id,vehicle_id,created_by)
  values('mock',trim(p_external_vehicle_id),p_vehicle_id,auth.uid()) returning id into binding_id;
  return binding_id;
end;
$function$;
revoke all on function public.atlas_ops_bind_mock_vehicle(uuid, text) from public, anon;
grant execute on function public.atlas_ops_bind_mock_vehicle(uuid, text) to authenticated;

create or replace function public.atlas_ops_ingest_mock_telemetry(
  p_external_event_id text, p_external_vehicle_id text, p_observed_at timestamptz,
  p_latitude double precision, p_longitude double precision, p_speed_kph double precision default null
)
returns uuid language plpgsql security definer set search_path = public
as $function$
declare actor uuid := auth.uid(); binding public.atlas_ops_telemetry_vehicle_bindings%rowtype; event_id uuid;
begin
  if actor is null or not public.atlas_ops_is_current_super_admin() then raise exception 'El simulador solo está disponible para superadministración.'; end if;
  select * into binding from public.atlas_ops_telemetry_vehicle_bindings
  where provider = 'mock' and external_vehicle_id = p_external_vehicle_id and is_active;
  if not found then raise exception 'Binding de vehículo mock activo no encontrado.'; end if;
  insert into public.atlas_ops_telemetry_events(
    provider, external_event_id, external_vehicle_id, binding_id, vehicle_id, observed_at,
    latitude, longitude, speed_kph, payload_digest, processing_status
  ) values (
    'mock', p_external_event_id, p_external_vehicle_id, binding.id, binding.vehicle_id, p_observed_at,
    p_latitude, p_longitude, p_speed_kph, encode(extensions.digest(convert_to(concat_ws('|',p_external_event_id,p_external_vehicle_id,p_observed_at,p_latitude,p_longitude), 'utf8'), 'sha256'),'hex'), 'processed'
  ) on conflict (provider, external_event_id) do nothing returning id into event_id;
  if event_id is null then select id into event_id from public.atlas_ops_telemetry_events where provider='mock' and external_event_id=p_external_event_id; end if;
  return event_id;
end;
$function$;
revoke all on function public.atlas_ops_ingest_mock_telemetry(text,text,timestamptz,double precision,double precision,double precision) from public, anon;
grant execute on function public.atlas_ops_ingest_mock_telemetry(text,text,timestamptz,double precision,double precision,double precision) to authenticated;

create or replace function public.atlas_ops_refresh_sla_alerts(p_at timestamptz default now())
returns integer language plpgsql security definer set search_path = public
as $function$
declare actor uuid := auth.uid(); affected integer;
begin
  if actor is null or not public.atlas_ops_can_manage(actor) then raise exception 'Sin permiso para actualizar alertas.'; end if;
  insert into public.atlas_ops_alerts(dispatch_id, milestone_id, alert_type, message)
  select d.id, m.id,
         case when p_at >= m.critical_at then 'critical' else 'attention' end,
         case when p_at >= m.critical_at then 'Hito crítico vencido: ' || m.label else 'Hito próximo: ' || m.label end
  from public.atlas_ops_dispatches d
  join public.atlas_ops_dispatch_milestones m on m.dispatch_id = d.id
  where d.planning_status = 'published' and d.execution_status not in ('completed','failed','suspended')
    and m.required and m.status = 'pending' and p_at >= coalesce(m.warning_at, m.critical_at)
    and public.atlas_ops_can_edit_contract(actor, d.contract_id)
  on conflict (dispatch_id, milestone_id, alert_type) do update set message = excluded.message
  where public.atlas_ops_alerts.status = 'open';
  get diagnostics affected = row_count;
  update public.atlas_ops_alerts a set status = 'resolved', resolved_at = p_at,
    resolution_note = 'Hito completado o servicio cerrado automáticamente'
  from public.atlas_ops_dispatch_milestones m, public.atlas_ops_dispatches d
  where a.milestone_id = m.id and m.dispatch_id = d.id and a.status = 'open'
    and (m.status = 'completed' or d.execution_status in ('completed','failed','suspended','cancelled'))
    and public.atlas_ops_can_edit_contract(actor, d.contract_id);
  return affected;
end;
$function$;
revoke all on function public.atlas_ops_refresh_sla_alerts(timestamptz) from public, anon;
grant execute on function public.atlas_ops_refresh_sla_alerts(timestamptz) to authenticated;

create or replace function public.atlas_ops_resolve_alert(p_alert_id uuid, p_note text)
returns void language plpgsql security definer set search_path = public
as $function$
declare actor uuid := auth.uid(); contract_key bigint;
dispatch_key uuid;
begin
  select d.contract_id, d.id into contract_key, dispatch_key from public.atlas_ops_alerts a join public.atlas_ops_dispatches d on d.id = a.dispatch_id where a.id = p_alert_id;
  if actor is null or not public.atlas_ops_can_edit_contract(actor, contract_key) then raise exception 'Sin permiso para resolver esta alerta.'; end if;
  update public.atlas_ops_alerts set status='resolved', resolved_at=now(), resolved_by=actor, resolution_note=nullif(trim(p_note),'')
  where id=p_alert_id and status <> 'resolved';
  if not found then raise exception 'Alerta no encontrada o ya resuelta.'; end if;
  insert into public.atlas_ops_dispatch_events(dispatch_id, event_type, source, actor_user_id, payload)
  values(dispatch_key, 'alert.resolved', 'coordinator', actor, jsonb_build_object('alert_id', p_alert_id, 'note', nullif(trim(p_note),'')));
end;
$function$;
revoke all on function public.atlas_ops_resolve_alert(uuid, text) from public, anon;
grant execute on function public.atlas_ops_resolve_alert(uuid, text) to authenticated;

create or replace function public.atlas_ops_acknowledge_alert(p_alert_id uuid)
returns void language plpgsql security definer set search_path = public
as $function$
declare actor uuid := auth.uid(); contract_key bigint;
dispatch_key uuid;
begin
  select d.contract_id, d.id into contract_key, dispatch_key from public.atlas_ops_alerts a join public.atlas_ops_dispatches d on d.id=a.dispatch_id where a.id=p_alert_id;
  if actor is null or not public.atlas_ops_can_edit_contract(actor,contract_key) then raise exception 'Sin permiso para atender esta alerta.'; end if;
  update public.atlas_ops_alerts set status='acknowledged',acknowledged_at=now(),acknowledged_by=actor
  where id=p_alert_id and status='open';
  if not found then raise exception 'Alerta abierta no encontrada.'; end if;
  insert into public.atlas_ops_dispatch_events(dispatch_id, event_type, source, actor_user_id, payload)
  values(dispatch_key, 'alert.acknowledged', 'coordinator', actor, jsonb_build_object('alert_id', p_alert_id));
end;
$function$;
revoke all on function public.atlas_ops_acknowledge_alert(uuid) from public, anon;
grant execute on function public.atlas_ops_acknowledge_alert(uuid) to authenticated;

create or replace function public.atlas_ops_reject_event_mutation()
returns trigger language plpgsql set search_path = public
as $$ begin raise exception 'Los eventos Atlas Operations son inmutables.'; end $$;
create trigger atlas_ops_dispatch_events_immutable before update or delete on public.atlas_ops_dispatch_events
for each row execute function public.atlas_ops_reject_event_mutation();

create or replace function public.atlas_ops_apply_geofences()
returns trigger language plpgsql security definer set search_path = public
as $function$
declare
  fence record;
  prior record;
  current_m double precision;
  prior_m double precision;
  transition_name text;
  dispatch_key uuid;
  milestone_row record;
begin
  if new.vehicle_id is null then return new; end if;
  for fence in select * from public.atlas_ops_geofences where is_active loop
  select e.latitude, e.longitude into prior from public.atlas_ops_telemetry_events e
    where e.vehicle_id = new.vehicle_id and e.id <> new.id and e.observed_at < new.observed_at
    order by e.observed_at desc limit 1;
    if not found then continue; end if;
    if new.accuracy_m is not null and new.accuracy_m > fence.jitter_buffer_meters * 2 then continue; end if;
    current_m := 6371000 * 2 * asin(sqrt(
      power(sin(radians(new.latitude-fence.center_latitude)/2),2) +
      cos(radians(fence.center_latitude))*cos(radians(new.latitude))*power(sin(radians(new.longitude-fence.center_longitude)/2),2)
    ));
    prior_m := 6371000 * 2 * asin(sqrt(
      power(sin(radians(prior.latitude-fence.center_latitude)/2),2) +
      cos(radians(fence.center_latitude))*cos(radians(prior.latitude))*power(sin(radians(prior.longitude-fence.center_longitude)/2),2)
    ));
    transition_name := null;
    if prior_m >= fence.radius_meters + fence.jitter_buffer_meters and current_m <= fence.radius_meters - fence.jitter_buffer_meters then transition_name := 'enter';
    elsif prior_m <= fence.radius_meters - fence.jitter_buffer_meters and current_m >= fence.radius_meters + fence.jitter_buffer_meters then transition_name := 'exit';
    end if;
    if transition_name is null then continue; end if;
    if exists (
      select 1 from public.atlas_ops_geofence_events ge
      where ge.geofence_id=fence.id and ge.vehicle_id=new.vehicle_id
        and ge.occurred_at > new.observed_at - make_interval(secs => fence.min_transition_seconds)
    ) then continue; end if;
    insert into public.atlas_ops_geofence_events(geofence_id, telemetry_event_id, vehicle_id, transition, occurred_at)
    values (fence.id,new.id,new.vehicle_id,transition_name,new.observed_at) on conflict do nothing;
    select d.id into dispatch_key from public.atlas_ops_dispatches d
    where d.vehicle_id = new.vehicle_id and d.contract_id = fence.contract_id
      and d.planning_status = 'published' and d.service_date = (new.observed_at at time zone 'America/Santiago')::date
    order by d.planned_start_at desc limit 1;
    if dispatch_key is null then continue; end if;
    insert into public.atlas_ops_dispatch_events(dispatch_id,event_type,source,occurred_at,payload)
    values (dispatch_key,'geofence.'||transition_name,new.provider,new.observed_at,
      jsonb_build_object('geofence_id',fence.id,'geofence_code',fence.code,'telemetry_event_id',new.id));
    if fence.geofence_type = 'workshop' and transition_name = 'exit' then
      select * into milestone_row from public.atlas_ops_dispatch_milestones
      where dispatch_id=dispatch_key and code='WORKSHOP_EXIT' and status='pending' limit 1;
      if found then
        update public.atlas_ops_dispatch_milestones set status='completed',actual_at=new.observed_at where id=milestone_row.id;
        insert into public.atlas_ops_dispatch_events(dispatch_id,milestone_id,event_type,source,occurred_at,payload)
        values(dispatch_key,milestone_row.id,'milestone.completed',new.provider,new.observed_at,jsonb_build_object('evidence','geofence','telemetry_event_id',new.id));
      end if;
    end if;
  end loop;
  return new;
end;
$function$;
create trigger atlas_ops_telemetry_geofence after insert on public.atlas_ops_telemetry_events
for each row execute function public.atlas_ops_apply_geofences();

create or replace view public.atlas_ops_control_tower
with (security_invoker = true)
as
select d.id, d.contract_id, c.code as contract_code, d.service_date, d.shift, d.planned_start_at, d.acknowledged_at,
       t.name as service_name, d.driver_name_snapshot, d.vehicle_id, v.code as vehicle_code, v.plate,
       d.planning_status, d.execution_status,
       case when exists (select 1 from public.atlas_ops_alerts a where a.dispatch_id = d.id and a.status in ('open','acknowledged') and a.alert_type = 'critical') then 'critical'
            when exists (select 1 from public.atlas_ops_incidents i where i.dispatch_id=d.id and i.status in ('open','investigating') and i.severity='critical') then 'critical'
            when exists (select 1 from public.atlas_ops_alerts a where a.dispatch_id = d.id and a.status in ('open','acknowledged') and a.alert_type = 'at_risk') then 'at_risk'
            when exists (select 1 from public.atlas_ops_incidents i where i.dispatch_id=d.id and i.status in ('open','investigating') and i.severity='high') then 'at_risk'
            when exists (select 1 from public.atlas_ops_alerts a where a.dispatch_id = d.id and a.status in ('open','acknowledged') and a.alert_type = 'attention') then 'attention'
            when exists (select 1 from public.atlas_ops_dispatch_milestones m where m.dispatch_id=d.id and m.required and m.status='pending' and now()>=m.critical_at) then 'critical'
            when exists (select 1 from public.atlas_ops_dispatch_milestones m where m.dispatch_id=d.id and m.required and m.status='pending' and now()>=coalesce(m.warning_at,m.critical_at)) then 'attention'
            else 'green' end as risk_status
from public.atlas_ops_dispatches d
join public.contracts c on c.id = d.contract_id
left join public.atlas_ops_service_templates t on t.id = d.service_template_id
left join public.atlas_ops_vehicles v on v.id = d.vehicle_id;
revoke all on public.atlas_ops_control_tower from public, anon;
grant select on public.atlas_ops_control_tower to authenticated;

do $$
begin
  begin alter publication supabase_realtime add table public.atlas_ops_dispatches; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.atlas_ops_dispatch_events; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.atlas_ops_alerts; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.atlas_ops_telemetry_events; exception when duplicate_object then null; end;
end $$;

-- Worker lookup and role helper are retained as compatibility adapters: both still resolve only BUK/roster data.
-- Storage, write RPCs, contract-editor view and legacy fleet/service tables are retired above.

notify pgrst, 'reload schema';
commit;
