begin;

create extension if not exists pgcrypto;

create table if not exists public.job_positions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.contracts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  contract_number text not null,
  contract_name text not null,
  cost_unit text not null,
  cost_unit_name text not null,
  cost_center_code text not null,
  cost_center_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (contract_number, contract_name)
);

create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.hiring_requests (
  id uuid primary key default gen_random_uuid(),
  folio text unique,
  requester_id uuid not null references public.profiles (id) on delete restrict,
  requester_name text not null,
  requester_job_title text,
  requester_email text not null,
  requested_entry_date date not null,
  job_position_id bigint references public.job_positions (id) on delete set null,
  job_position_name text not null,
  vacancies integer not null check (vacancies > 0),
  contract_id bigint not null references public.contracts (id) on delete restrict,
  contract_name text not null,
  contract_number text not null,
  cost_unit text not null,
  cost_unit_name text not null,
  cost_center_code text not null,
  cost_center_name text not null,
  start_date date not null,
  end_date date not null,
  campamento boolean not null default false,
  pasajes boolean not null default false,
  other_benefits text,
  salary_offer numeric(12,0) not null check (salary_offer >= 0),
  shift_id bigint references public.shifts (id) on delete set null,
  shift_name text not null,
  requester_signed boolean not null default false,
  status text not null default 'pendiente' check (status in ('pendiente', 'aprobada', 'rechazada', 'cerrada')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_job_positions_name on public.job_positions (name);
create index if not exists idx_contracts_name on public.contracts (contract_name);
create index if not exists idx_shifts_name on public.shifts (name);
create index if not exists idx_hiring_requests_requester_id on public.hiring_requests (requester_id);
create index if not exists idx_hiring_requests_status on public.hiring_requests (status);

drop trigger if exists trg_job_positions_set_updated_at on public.job_positions;
create trigger trg_job_positions_set_updated_at
before update on public.job_positions
for each row execute function public.set_updated_at();

drop trigger if exists trg_contracts_set_updated_at on public.contracts;
create trigger trg_contracts_set_updated_at
before update on public.contracts
for each row execute function public.set_updated_at();

drop trigger if exists trg_shifts_set_updated_at on public.shifts;
create trigger trg_shifts_set_updated_at
before update on public.shifts
for each row execute function public.set_updated_at();

drop trigger if exists trg_hiring_requests_set_updated_at on public.hiring_requests;
create trigger trg_hiring_requests_set_updated_at
before update on public.hiring_requests
for each row execute function public.set_updated_at();

alter table public.job_positions enable row level security;
alter table public.contracts enable row level security;
alter table public.shifts enable row level security;
alter table public.hiring_requests enable row level security;

drop policy if exists "job_positions_select_authenticated" on public.job_positions;
drop policy if exists "contracts_select_authenticated" on public.contracts;
drop policy if exists "shifts_select_authenticated" on public.shifts;
drop policy if exists "job_positions_select_authenticated" on public.job_positions;
create policy "job_positions_select_authenticated" on public.job_positions for select to authenticated using (is_active = true);

drop policy if exists "contracts_select_authenticated" on public.contracts;
create policy "contracts_select_authenticated" on public.contracts for select to authenticated using (is_active = true);

drop policy if exists "shifts_select_authenticated" on public.shifts;
create policy "shifts_select_authenticated" on public.shifts for select to authenticated using (is_active = true);

drop policy if exists "hiring_requests_select_owned_or_operational" on public.hiring_requests;
create policy "hiring_requests_select_owned_or_operational" on public.hiring_requests
for select to authenticated using (
  requester_id = auth.uid()
  or public.user_is_admin(auth.uid())
  or public.user_has_role(auth.uid(), 'reclutamiento')
  or public.user_has_role(auth.uid(), 'control_contratos')
);

drop policy if exists "hiring_requests_insert_requester" on public.hiring_requests;
create policy "hiring_requests_insert_requester" on public.hiring_requests
for insert to authenticated with check (
  requester_id = auth.uid()
  and public.user_can_access_module(auth.uid(), 'solicitud_contrataciones')
);

drop policy if exists "hiring_requests_update_operational" on public.hiring_requests;
create policy "hiring_requests_update_operational" on public.hiring_requests
for update to authenticated using (
  public.user_is_admin(auth.uid())
  or public.user_has_role(auth.uid(), 'reclutamiento')
  or public.user_has_role(auth.uid(), 'control_contratos')
) with check (
  public.user_is_admin(auth.uid())
  or public.user_has_role(auth.uid(), 'reclutamiento')
  or public.user_has_role(auth.uid(), 'control_contratos')
);

grant select on public.job_positions to authenticated;
grant select on public.contracts to authenticated;
grant select on public.shifts to authenticated;
grant select, insert, update on public.hiring_requests to authenticated;

insert into public.job_positions (code, name, is_active) values
  ('CARGO-001', 'ADMINISTRADOR DE CONTRATOS', true),
  ('CARGO-002', 'ADMINISTRATIVO DE VENTAS', true),
  ('CARGO-003', 'ADMINISTRATIVO RRHH', true),
  ('CARGO-004', 'ALUMNO EN PRACTICA', true),
  ('CARGO-005', 'ANALISTA CONTABLE', true),
  ('CARGO-006', 'ANALISTA CONTROL DE COMBUSTIBLE', true),
  ('CARGO-007', 'ANALISTA DE CONTROL DE GESTION', true),
  ('CARGO-008', 'ANALISTA DE FACTURACIÓN Y COBRANZA', true),
  ('CARGO-009', 'ANALISTA DE OPERACIONES', true),
  ('CARGO-010', 'ANALISTA DE REMUNERACIONES', true),
  ('CARGO-011', 'ANALISTA DE RRHH JUNIOR', true),
  ('CARGO-012', 'ANALISTA DE TESORERIA', true),
  ('CARGO-013', 'ANALISTA PROGRAMADOR WEB', true),
  ('CARGO-014', 'ANALISTA SALA DE CONTROL', true),
  ('CARGO-015', 'ASEADOR', true),
  ('CARGO-016', 'ASESOR DE CALIDAD', true),
  ('CARGO-017', 'ASISTENTE', true),
  ('CARGO-018', 'ASISTENTE ADMINISTRATIVO', true),
  ('CARGO-019', 'ASISTENTE BODEGA LOS ANDES', true),
  ('CARGO-020', 'ASISTENTE CONTROL ASISTENCIA', true),
  ('CARGO-021', 'ASISTENTE DE ADQUISICIONES', true),
  ('CARGO-022', 'ASISTENTE DE CONTRALORIA', true),
  ('CARGO-023', 'ASISTENTE DE FACTURACION Y COBRANZA', true),
  ('CARGO-024', 'ASISTENTE DESARROLLO DE PERSONAS', true),
  ('CARGO-025', 'ASISTENTE GERENCIA', true),
  ('CARGO-026', 'AUDITOR INTERNO', true),
  ('CARGO-027', 'AUXILIAR', true),
  ('CARGO-028', 'AYUDANTE MECÁNICOS', true),
  ('CARGO-029', 'BODEGUERO', true),
  ('CARGO-030', 'CHAPISTERO', true),
  ('CARGO-031', 'COMPRADOR LOCAL', true),
  ('CARGO-032', 'CONDUCTOR 4X4 SIGDO KOPPERS VP ANDINA', true),
  ('CARGO-033', 'CONDUCTOR BUS', true),
  ('CARGO-034', 'CONDUCTOR CAMIONETA', true),
  ('CARGO-035', 'CONDUCTOR DE BUS', true),
  ('CARGO-036', 'CONDUCTOR DE FURGON', true),
  ('CARGO-037', 'CONDUCTOR DE TAXIBUS', true),
  ('CARGO-038', 'CONTADOR', true),
  ('CARGO-039', 'CONTROLLER', true),
  ('CARGO-040', 'COORDINADOR DE SERVICIOS', true),
  ('CARGO-041', 'COORDINADOR OPERATIVO DE TRANSPORTE', true),
  ('CARGO-042', 'DIRECCIÓN', true),
  ('CARGO-043', 'ELÉCTRICISTA', true),
  ('CARGO-044', 'ELECTRICO', true),
  ('CARGO-045', 'ENCARGADA DE RRLL', true),
  ('CARGO-046', 'ENCARGADO DE CONTRALORIA', true),
  ('CARGO-047', 'ENCARGADO DE CONTRATOS Y FINIQUITOS', true),
  ('CARGO-048', 'ENCARGADO DE CONTROL DE GESTION', true),
  ('CARGO-049', 'ENCARGADO DE RRHH', true),
  ('CARGO-050', 'ENCARGADO DE SELECCION DE PERSONAL', true),
  ('CARGO-051', 'EXPEDITOR', true),
  ('CARGO-052', 'INGENIERO AMBIENTAL', true),
  ('CARGO-053', 'INGENIERO DE CALIDAD', true),
  ('CARGO-054', 'INGENIERO DE ESTUDIOS', true),
  ('CARGO-055', 'INGENIERO DE SEGURIDAD Y SALUD OCUPACIONAL', true),
  ('CARGO-056', 'INSPECTOR DE RUTA', true),
  ('CARGO-057', 'INSTRUCTOR DE SERVICIOS', true),
  ('CARGO-058', 'JEFE CONTROL DE MANTENCION', true),
  ('CARGO-059', 'JEFE DE BODEGA', true),
  ('CARGO-060', 'JEFE DE FACTURACION Y COBRANZAS', true),
  ('CARGO-061', 'JEFE DE MANTENCIÓN', true),
  ('CARGO-062', 'JEFE DE OF. REGIONAL', true),
  ('CARGO-063', 'JEFE DE OPERACIONES', true),
  ('CARGO-064', 'JEFE DE PREVENCION DE RIESGOS', true),
  ('CARGO-065', 'JEFE DE RRHH', true),
  ('CARGO-066', 'JEFE DE TALLER', true),
  ('CARGO-067', 'JEFE DE TURNO', true),
  ('CARGO-068', 'JEFE DESARROLLO DE PERSONAS', true),
  ('CARGO-069', 'JEFE SALA DE CONTROL', true),
  ('CARGO-070', 'JEFE SERVICIO INTERURBANO-ESPECIAL', true),
  ('CARGO-071', 'LIDER LOGISTICO', true),
  ('CARGO-072', 'MECANICO', true),
  ('CARGO-073', 'MECANICO ELECTRICO', true),
  ('CARGO-074', 'OPERADOR CONTROLADOR', true),
  ('CARGO-075', 'PLANIFICADOR DE COMPRAS', true),
  ('CARGO-076', 'PLANIFICADOR DE TRANSPORTE', true),
  ('CARGO-077', 'PREVENCIONISTA DE RIESGOS', true),
  ('CARGO-078', 'PROGRAMADOR TI', true),
  ('CARGO-079', 'PSICOLOGO ORGANIZACIONAL', true),
  ('CARGO-080', 'SECRETARIA', true),
  ('CARGO-081', 'SECRETARIO TECNICO', true),
  ('CARGO-082', 'SUPERVISOR', true),
  ('CARGO-083', 'SUPERVISOR BODEGA CALAMA', true),
  ('CARGO-084', 'SUPERVISOR BODEGA LOS ANDES', true),
  ('CARGO-085', 'SUPERVISOR CONTABLE', true),
  ('CARGO-086', 'SUPERVISOR DE OPERACIONES', true),
  ('CARGO-087', 'SUPERVISOR DE PATIOS', true),
  ('CARGO-088', 'SUPERVISOR DE REMUNERACIONES', true),
  ('CARGO-089', 'TRABAJADOR SOCIAL', true)
on conflict (code) do update set name = excluded.name, is_active = excluded.is_active;

insert into public.contracts (code, contract_number, contract_name, cost_unit, cost_unit_name, cost_center_code, cost_center_name, is_active) values
  ('CONT-001', '0000000102:0001', 'ABASTECIMIENTO', '100', 'ADMINISTRACION', '10104', 'GERENCIA FINANZAS', true),
  ('CONT-002', '7801797801:0001', 'ACCIONA OSSA PIZZAROTTI CAMBIO TURNO', '109', 'SERV ESPECIALES', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-003', '5906986002:0001', 'ACCIONA TALABRE', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-004', '0000000101:0001', 'ADMINISTRACION', '100', 'ADMINISTRACION', '10100', 'GERENCIA GENERAL', true),
  ('CONT-005', '7851187001:0001', 'ANDIMAR', '109', 'SERV ESPECIALES', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-006', '7611769635:0001', 'ARAMARK - CAMPUS CODELCO', '107', 'SERV ARAMARK', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-007', '7611769634:0001', 'ARAMARK - EL ABRA', '107', 'SERV ARAMARK', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-008', '7611769633:0001', 'ARAMARK - PRET', '107', 'SERV ARAMARK', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-009', '7611769609:0001', 'ARAMARK CAMPAMENTO ZONA NORTE', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-010', '7611769626:0001', 'ARAMARK CAMPAMENTO ZONA NORTE INTERNO', '107', 'SERV ARAMARK', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-011', '7611769632:0001', 'ARAMARK DSAL', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-012', '7611769614:0001', 'ARAMARK ESCONDIDA', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-013', '7611769625:0001', 'ARAMARK GABY', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-014', '7611769627:0001', 'ARAMARK GABY INTERNO', '107', 'SERV ARAMARK', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-015', '7611769628:0001', 'ARAMARK MINISTRO HALES INTERNO', '107', 'SERV ARAMARK', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-016', '7611769612:0001', 'ARAMARK QUEBRADA BLANCA', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-017', '7611769602:0001', 'ARAMARK SIERRA GORDA', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-018', '7611769630:0001', 'ARAMARK SIERRA GORDA INTERNO', '107', 'SERV ARAMARK', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-019', '761176912:0001', 'ARAMARK VP ANDINA', '109', 'SERV ESPECIALES', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-020', '0000000162:0001', 'ARRIENDO DE BUSES', '162', 'ARRIENDO DE BUSES', '10100', 'GERENCIA GENERAL', true),
  ('CONT-021', '7642593601:0001', 'ASIB - SIERRA GORDA', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-022', '7811932003:0001', 'AURA - DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-023', '7605030115:0001', 'BERLIAM - DRT CHANCADO SECUNDARIO', '121', 'SERV FERROVIAL', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-024', '7605030110:0001', 'BERLIAM DRT CHANCADO', '121', 'SERV FERROVIAL', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-025', '7605030113:0001', 'BERLIAM ZALDIVAR', '121', 'SERV FERROVIAL', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-026', '0000000103:0001', 'BODEGA', '100', 'ADMINISTRACION', '10104', 'GERENCIA FINANZAS', true),
  ('CONT-027', '6170400008:0001', 'CODELCO ANDINA 2022', '154', 'SERV CODELCO ANDINA', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-028', '6170400006:0001', 'CODELCO DMH', '128', 'SERV CODELCO DMH', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-029', '6170400010:0001', 'CODELCO DRT', '163', 'CODELCO DRT', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-030', '6170400009:0001', 'CODELCO VP ANDINA 2022', '155', 'SERV CODELCO ANDINA VP', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-031', '6170400007:0001', 'CODELCO VP CHUQUI PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-032', '0000000104:0001', 'COMERCIAL', '100', 'ADMINISTRACION', '10102', 'GERENCIA COMERCIAL', true),
  ('CONT-033', '9687083002:0001', 'COMTECSA - PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-034', '0000000106:0001', 'CONTABILIDAD', '100', 'ADMINISTRACION', '10104', 'GERENCIA FINANZAS', true),
  ('CONT-035', '0000000107:0001', 'CONTROL FLOTA', '100', 'ADMINISTRACION', '10115', 'CONTROL FLOTA', true),
  ('CONT-036', '9957547004:0001', 'DESCARTABLES', '100', 'ADMINISTRACION', '10115', 'CONTROL FLOTA', true),
  ('CONT-037', '9999999998:0001', 'DISPONIBLES EN REPARACION', '108', 'MANTENCION LOS ANDES', '10106', 'GERENCIA MANTENIMIENTO', true),
  ('CONT-038', '9957547008:0001', 'DISPONIBLES PARA ASIGNAR', '100', 'ADMINISTRACION', '10102', 'GERENCIA COMERCIAL', true),
  ('CONT-039', '7672704001:0001', 'DMC CENTINELA', '165', 'SERV MINERA CENTINELA', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-040', '7952723001:0001', 'EMIN - MEL', '166', 'CONTRATISTAS ANTOFAGASTA', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-041', '7604187102:0001', 'ENAEX ANDINA 2024', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-042', '0000000105:0001', 'FACTURACION Y COBRANZAS', '100', 'ADMINISTRACION', '10104', 'GERENCIA FINANZAS', true),
  ('CONT-043', '9148900001:0001', 'FINNING ARMADO DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-044', '9148900002:0001', 'FINNING MARC DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-045', '7776182302:0001', 'FLIX LA SERENA', '164', 'SERV FLIX', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-046', '7776182304:0001', 'FLIX QUINTERO', '164', 'SERV FLIX', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-047', '7776182308:0001', 'FLIX SAN ANTONIO', '164', 'SERV FLIX', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-048', '7776182303:0001', 'FLIX SANTIAGO', '164', 'SERV FLIX', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-049', '7776182306:0001', 'FLIX VALPARAÍSO', '164', 'SERV FLIX', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-050', '7776182301:0001', 'FLIX VIÑA DEL MAR', '164', 'SERV FLIX', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-051', '8555590001:0001', 'FLUOR - EL ABRA', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-052', '7676154701:0001', 'FLUOR SALFA CENTINELA', '169', 'FLUOR SALFA CENTINELA', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-053', '8832580001:0001', 'FUNDICION ALTONORTE', '125', 'SERV ALTONORTE', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-054', '7973088001:0001', 'INCOLUR VP ANDINA', '109', 'SERV ESPECIALES', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-055', '0000000158:0001', 'INDIRECTOS ZONA I', '158', 'INDIRECTOS ZONA I', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-056', '0000000159:0001', 'INDIRECTOS ZONA II', '159', 'INDIRECTOS ZONA II', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-057', '0000000167:0001', 'INDIRECTOS ZONA III', '167', 'INDIRECTOS ZONA III', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-058', '7850277002:0001', 'INTERURBANO VALPARAISO', '150', 'SERV PASAJEROS', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-059', '7831857001:0001', 'JEJ INGENIERIA VP ANDINA', '109', 'SERV ESPECIALES', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-060', '7850277001:0001', 'JM SERV ESPECIALES', '109', 'SERV ESPECIALES', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-061', '9957547009:0001', 'MANTENCION ANTOFAGASTA', '160', 'MANTENCION ANTOFAGASTA', '10106', 'GERENCIA MANTENIMIENTO', true),
  ('CONT-062', '9957547001:0001', 'MANTENCION CALAMA', '122', 'MANTENCION CALAMA', '10106', 'GERENCIA MANTENIMIENTO', true),
  ('CONT-063', '9957547010:0001', 'MANTENCION IQUIQUE', '161', 'MANTENCION IQUIQUE', '10106', 'GERENCIA MANTENIMIENTO', true),
  ('CONT-064', '9957547002:0001', 'MANTENCION LOS ANDES', '108', 'MANTENCION LOS ANDES', '10106', 'GERENCIA MANTENIMIENTO', true),
  ('CONT-065', '9665191011:0001', 'NEWREST - ALBEMARLE', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-066', '9665191010:0001', 'NEWREST - DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-067', '9665191013:0001', 'NEWREST - FRANKE', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-068', '9665191012:0001', 'NEWREST - QB PUERTO TECK', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-069', '9665191007:0001', 'NEWREST ANTUCOYA', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-070', '9665191006:0001', 'NEWREST CASERONES', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-071', '9665191008:0001', 'NEWREST CENTINELA', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-072', '9665191003:0001', 'NEWREST COLLAHUASI', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-073', '9665191005:0001', 'NEWREST CONCENTRADORA CENTINELA', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-074', '9665191009:0001', 'NEWREST MUELLE', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-075', '9665191004:0001', 'NEWREST ZALDIVAR', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-076', '7842341001:0001', 'NOATUM - EL ABRA', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-077', '0000000111:0001', 'PREVENCION DE RIESGOS', '100', 'ADMINISTRACION', '10110', 'GERENCIA PREVENCION DE RIESGOS', true),
  ('CONT-078', '0000000109:0001', 'RECURSOS HUMANOS', '100', 'ADMINISTRACION', '10111', 'GERENCIA RECURSOS HUMANOS', true),
  ('CONT-079', '8486500001:0001', 'RYQ PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-080', '7752259301:0001', 'SANTA ISADORA SQM', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-081', '7608159002:0001', 'SIERRA GORDA OPERACIONES', '110', 'SERV SIERRA GORDA', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-082', '9462300004:0001', 'SODEXO - CERRO PABELLÓN', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-083', '9462300001:0001', 'SODEXO SQM', '115', 'SERV CAMBIO DE TURNO', '10116', 'GERENCIA OPERACIONES ZONA III (NORTE COSTA)', true),
  ('CONT-084', '7805700001:0001', 'SOTRASER - DMH', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-085', '7654304601:0001', 'SYNCORE - TALABRE', '106', 'SERV CONTRATISTAS CALAMA', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-086', '0000000112:0001', 'TECNOLOGIA E INFORMACION', '100', 'ADMINISTRACION', '10104', 'GERENCIA FINANZAS', true),
  ('CONT-087', '7627009901:0001', 'TEPSAC DAND', '102', 'SERV ANDINA CONTRATISTAS', '10113', 'GERENCIA OPERACIONES ZONA I (CENTRO)', true),
  ('CONT-088', '0000000108:0001', 'TESORERIA', '100', 'ADMINISTRACION', '10104', 'GERENCIA FINANZAS', true),
  ('CONT-089', '9999999996:0001', 'VENDIDO REPARACIONES PENDIENTES', '100', 'ADMINISTRACION', '10112', 'SOCIOS', true),
  ('CONT-090', '9999999999:0001', 'VENTA', '100', 'ADMINISTRACION', '10112', 'SOCIOS', true),
  ('CONT-091', '9695370002:0001', 'XTREME MINING PMCHS', '152', 'SERV CODELCO - EECC PMCHS', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true),
  ('CONT-092', '0000000168:0001', 'ZONA II CONTRATISTAS', '168', 'ZONA II CONTRATISTAS', '10114', 'GERENCIA OPERACIONES ZONA II (NORTE INTERIOR)', true)
on conflict (code) do update set contract_number = excluded.contract_number, contract_name = excluded.contract_name, cost_unit = excluded.cost_unit, cost_unit_name = excluded.cost_unit_name, cost_center_code = excluded.cost_center_code, cost_center_name = excluded.cost_center_name, is_active = excluded.is_active;

insert into public.shifts (code, name, is_active) values
  ('TURNO-001', 'ART 22', true),
  ('TURNO-002', '9X3', true),
  ('TURNO-003', '8X6', true),
  ('TURNO-004', '7X7', true),
  ('TURNO-005', '6X3', true),
  ('TURNO-006', '5X2', true),
  ('TURNO-007', '4X4', true),
  ('TURNO-008', '4X3', true),
  ('TURNO-009', '15X13', true),
  ('TURNO-010', '14X14', true),
  ('TURNO-011', '10X5', true),
  ('TURNO-012', '10X10', true)
on conflict (code) do update set name = excluded.name, is_active = excluded.is_active;

commit;
