begin;

create table if not exists public.recruitment_cases (
  id uuid primary key default gen_random_uuid(),
  hiring_request_id uuid not null unique references public.hiring_requests (id) on delete restrict,
  case_code text not null unique,
  status text not null
    check (status in ('open', 'sourcing', 'screening', 'ready_to_hire', 'partially_filled', 'filled', 'closed_unfilled', 'cancelled')),
  requested_vacancies integer not null check (requested_vacancies > 0),
  filled_vacancies integer not null default 0 check (filled_vacancies >= 0),
  title text not null,
  contract_id bigint not null references public.contracts (id) on delete restrict,
  contract_name text not null,
  job_position_id bigint not null references public.job_positions (id) on delete restrict,
  job_position_name text not null,
  cost_center_code text not null,
  cost_center_name text not null,
  requested_entry_date date,
  target_close_date date,
  opened_at timestamptz not null default timezone('utc', now()),
  opened_by uuid not null references public.profiles (id) on delete restrict,
  closed_at timestamptz,
  closed_by uuid references public.profiles (id) on delete set null,
  close_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recruitment_case_assignments (
  id bigint generated by default as identity primary key,
  recruitment_case_id uuid not null references public.recruitment_cases (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete restrict,
  assignment_role text not null
    check (assignment_role in ('owner', 'recruiter', 'document_controller', 'viewer')),
  is_primary boolean not null default false,
  assigned_at timestamptz not null default timezone('utc', now()),
  assigned_by uuid references public.profiles (id) on delete set null,
  unique (recruitment_case_id, user_id, assignment_role)
);

create table if not exists public.candidate_profiles (
  id uuid primary key default gen_random_uuid(),
  national_id text not null unique,
  full_name text not null,
  email text,
  phone text,
  driver_license_number text,
  driver_license_class text,
  driver_license_expiry date,
  current_city text,
  source text,
  status text not null default 'active'
    check (status in ('active', 'inactive', 'blocked')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recruitment_case_candidates (
  id uuid primary key default gen_random_uuid(),
  recruitment_case_id uuid not null references public.recruitment_cases (id) on delete cascade,
  candidate_profile_id uuid not null references public.candidate_profiles (id) on delete restrict,
  stage_code text not null
    check (stage_code in ('lead', 'contacted', 'screening', 'shortlisted', 'documents_pending', 'ready_for_hire', 'hired', 'rejected', 'withdrawn')),
  stage_entered_at timestamptz not null default timezone('utc', now()),
  ranking_score numeric(5,2),
  suitability_status text not null default 'unknown'
    check (suitability_status in ('unknown', 'fit', 'risk', 'blocked')),
  is_selected boolean not null default false,
  rejection_reason text,
  withdrawal_reason text,
  hired_at timestamptz,
  created_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (recruitment_case_id, candidate_profile_id)
);

create table if not exists public.recruitment_case_candidate_stage_history (
  id bigint generated by default as identity primary key,
  recruitment_case_candidate_id uuid not null references public.recruitment_case_candidates (id) on delete cascade,
  from_stage text,
  to_stage text not null,
  changed_by uuid not null references public.profiles (id) on delete restrict,
  reason_code text,
  comment text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recruitment_case_audit_log (
  id bigint generated by default as identity primary key,
  recruitment_case_id uuid not null references public.recruitment_cases (id) on delete cascade,
  recruitment_case_candidate_id uuid references public.recruitment_case_candidates (id) on delete set null,
  actor_user_id uuid not null references public.profiles (id) on delete restrict,
  action_type text not null
    check (action_type in ('case_opened', 'owner_assigned', 'candidate_added', 'candidate_stage_changed', 'candidate_hired', 'case_status_synced')),
  old_values jsonb,
  new_values jsonb,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_recruitment_cases_status_target_close_date
  on public.recruitment_cases (status, target_close_date);
create index if not exists idx_recruitment_cases_cost_center_status
  on public.recruitment_cases (cost_center_code, status);
create index if not exists idx_recruitment_case_assignments_case_id
  on public.recruitment_case_assignments (recruitment_case_id);
create index if not exists idx_recruitment_case_assignments_user_id
  on public.recruitment_case_assignments (user_id);
create index if not exists idx_candidate_profiles_full_name
  on public.candidate_profiles (full_name);
create index if not exists idx_recruitment_case_candidates_case_stage
  on public.recruitment_case_candidates (recruitment_case_id, stage_code);
create index if not exists idx_recruitment_case_candidates_profile_id
  on public.recruitment_case_candidates (candidate_profile_id);
create index if not exists idx_recruitment_case_candidate_stage_history_candidate_id
  on public.recruitment_case_candidate_stage_history (recruitment_case_candidate_id, created_at desc);
create index if not exists idx_recruitment_case_audit_log_case_id
  on public.recruitment_case_audit_log (recruitment_case_id, created_at desc);

drop trigger if exists trg_recruitment_cases_set_updated_at on public.recruitment_cases;
create trigger trg_recruitment_cases_set_updated_at
before update on public.recruitment_cases
for each row execute function public.set_updated_at();

drop trigger if exists trg_candidate_profiles_set_updated_at on public.candidate_profiles;
create trigger trg_candidate_profiles_set_updated_at
before update on public.candidate_profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_recruitment_case_candidates_set_updated_at on public.recruitment_case_candidates;
create trigger trg_recruitment_case_candidates_set_updated_at
before update on public.recruitment_case_candidates
for each row execute function public.set_updated_at();

create or replace function public.user_can_access_recruitment_case(
  target_user_id uuid,
  target_case_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select
    public.user_is_admin(target_user_id)
    or public.user_has_role(target_user_id, 'control_contratos')
    or exists (
      select 1
      from public.recruitment_case_assignments rca
      where rca.recruitment_case_id = target_case_id
        and rca.user_id = target_user_id
    )
    or exists (
      select 1
      from public.recruitment_cases rc
      join public.hiring_requests hr
        on hr.id = rc.hiring_request_id
      where rc.id = target_case_id
        and hr.requester_id = target_user_id
    );
$function$;

create or replace function public.sync_recruitment_case_status(
  p_case_id uuid,
  p_actor_user_id uuid default auth.uid()
)
returns text
language plpgsql
security definer
set search_path = public
as $function$
declare
  case_record public.recruitment_cases%rowtype;
  hired_count integer := 0;
  ready_count integer := 0;
  active_count integer := 0;
  next_status text;
begin
  select *
    into case_record
    from public.recruitment_cases rc
   where rc.id = p_case_id
   for update;

  if case_record.id is null then
    raise exception 'No existe el caso de reclutamiento';
  end if;

  select count(*)
    into hired_count
    from public.recruitment_case_candidates rcc
   where rcc.recruitment_case_id = p_case_id
     and rcc.stage_code = 'hired';

  select count(*)
    into ready_count
    from public.recruitment_case_candidates rcc
   where rcc.recruitment_case_id = p_case_id
     and rcc.stage_code = 'ready_for_hire';

  select count(*)
    into active_count
    from public.recruitment_case_candidates rcc
   where rcc.recruitment_case_id = p_case_id
     and rcc.stage_code not in ('rejected', 'withdrawn');

  next_status :=
    case
      when case_record.close_reason is not null and case_record.closed_at is not null then case_record.status
      when hired_count >= case_record.requested_vacancies then 'filled'
      when hired_count > 0 then 'partially_filled'
      when ready_count > 0 then 'ready_to_hire'
      when active_count > 0 then 'screening'
      else 'open'
    end;

  update public.recruitment_cases rc
     set filled_vacancies = hired_count,
         status = next_status,
         updated_at = timezone('utc', now())
   where rc.id = p_case_id;

  if case_record.status is distinct from next_status then
    insert into public.recruitment_case_audit_log (
      recruitment_case_id,
      actor_user_id,
      action_type,
      old_values,
      new_values,
      metadata
    )
    values (
      p_case_id,
      coalesce(p_actor_user_id, case_record.opened_by),
      'case_status_synced',
      jsonb_build_object(
        'status', case_record.status,
        'filled_vacancies', case_record.filled_vacancies
      ),
      jsonb_build_object(
        'status', next_status,
        'filled_vacancies', hired_count
      ),
      jsonb_build_object(
        'ready_candidates', ready_count,
        'active_candidates', active_count
      )
    );
  end if;

  return next_status;
end;
$function$;

create or replace function public.open_recruitment_case_from_hiring_request(
  p_hiring_request_id uuid,
  p_opened_by uuid default auth.uid()
)
returns uuid
language plpgsql
security definer
set search_path = public
as $function$
declare
  request_record public.hiring_requests%rowtype;
  existing_case_id uuid;
  owner_user_id uuid;
  created_case_id uuid;
begin
  select rc.id
    into existing_case_id
    from public.recruitment_cases rc
   where rc.hiring_request_id = p_hiring_request_id;

  if existing_case_id is not null then
    return existing_case_id;
  end if;

  select *
    into request_record
    from public.hiring_requests hr
   where hr.id = p_hiring_request_id
   for update;

  if request_record.id is null then
    raise exception 'No existe la solicitud origen';
  end if;

  if request_record.status <> 'approved' then
    raise exception 'Solo se pueden abrir casos desde solicitudes aprobadas';
  end if;

  owner_user_id := coalesce(
    p_opened_by,
    request_record.final_decided_by,
    request_record.submitted_by,
    request_record.requester_id
  );

  insert into public.recruitment_cases (
    hiring_request_id,
    case_code,
    status,
    requested_vacancies,
    filled_vacancies,
    title,
    contract_id,
    contract_name,
    job_position_id,
    job_position_name,
    cost_center_code,
    cost_center_name,
    requested_entry_date,
    target_close_date,
    opened_at,
    opened_by
  )
  values (
    request_record.id,
    format('RC-%s', request_record.folio),
    'open',
    request_record.vacancies,
    0,
    format('%s · %s', request_record.job_position_name, request_record.contract_name),
    request_record.contract_id,
    request_record.contract_name,
    request_record.job_position_id,
    request_record.job_position_name,
    request_record.cost_center_code,
    request_record.cost_center_name,
    request_record.requested_entry_date,
    request_record.start_date,
    timezone('utc', now()),
    owner_user_id
  )
  returning id into created_case_id;

  insert into public.recruitment_case_assignments (
    recruitment_case_id,
    user_id,
    assignment_role,
    is_primary,
    assigned_at,
    assigned_by
  )
  values (
    created_case_id,
    owner_user_id,
    'owner',
    true,
    timezone('utc', now()),
    owner_user_id
  )
  on conflict (recruitment_case_id, user_id, assignment_role) do nothing;

  insert into public.recruitment_case_audit_log (
    recruitment_case_id,
    actor_user_id,
    action_type,
    new_values,
    metadata
  )
  values (
    created_case_id,
    owner_user_id,
    'case_opened',
    jsonb_build_object(
      'case_code', format('RC-%s', request_record.folio),
      'status', 'open',
      'requested_vacancies', request_record.vacancies
    ),
    jsonb_build_object(
      'hiring_request_id', request_record.id,
      'folio', request_record.folio
    )
  );

  insert into public.recruitment_case_audit_log (
    recruitment_case_id,
    actor_user_id,
    action_type,
    new_values,
    metadata
  )
  values (
    created_case_id,
    owner_user_id,
    'owner_assigned',
    jsonb_build_object(
      'user_id', owner_user_id,
      'assignment_role', 'owner',
      'is_primary', true
    ),
    jsonb_build_object('source', 'open_recruitment_case_from_hiring_request')
  );

  return created_case_id;
end;
$function$;

create or replace function public.get_recruitment_control_dashboard_v2()
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  summary jsonb := '{}'::jsonb;
  pending_approvals jsonb := '[]'::jsonb;
  active_cases jsonb := '[]'::jsonb;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_can_access_module(current_user_id, 'control_contrataciones') then
    raise exception 'Sin permisos para ver control de contrataciones';
  end if;

  select jsonb_build_object(
    'pending_contracts_control', count(*) filter (where hra.step_code = 'contracts_control' and hra.status = 'pending'),
    'active_cases', count(*) filter (where rc.status not in ('filled', 'closed_unfilled', 'cancelled')),
    'ready_to_hire_cases', count(*) filter (where rc.status = 'ready_to_hire'),
    'filled_cases', count(*) filter (where rc.status = 'filled'),
    'total_cases', count(*)
  )
  into summary
  from public.recruitment_cases rc
  left join public.hiring_request_approvals hra
    on hra.hiring_request_id = rc.hiring_request_id
   and hra.step_code = 'contracts_control'
   and hra.status = 'pending'
  where public.user_can_access_recruitment_case(current_user_id, rc.id);

  select coalesce(
    jsonb_agg(queue_row.payload order by queue_row.sort_created_at asc, queue_row.sort_id asc),
    '[]'::jsonb
  )
  into pending_approvals
  from (
    select
      jsonb_build_object(
        'id', hra.id,
        'step_code', hra.step_code,
        'step_name', hra.step_name,
        'hiring_request_id', hra.hiring_request_id,
        'approver_user_id', hra.approver_user_id,
        'approver_name', hra.approver_name,
        'approver_email', hra.approver_email,
        'created_at', hra.created_at,
        'hiring_requests', jsonb_build_object(
          'folio', hr.folio,
          'status', hr.status,
          'requester_name', hr.requester_name,
          'requester_email', hr.requester_email,
          'contract_name', hr.contract_name,
          'contract_number', hr.contract_number,
          'job_position_name', hr.job_position_name,
          'vacancies', hr.vacancies,
          'requested_entry_date', hr.requested_entry_date,
          'start_date', hr.start_date,
          'end_date', hr.end_date,
          'shift_name', hr.shift_name,
          'salary_offer', hr.salary_offer,
          'campamento', hr.campamento,
          'pasajes', hr.pasajes,
          'other_benefits', hr.other_benefits
        )
      ) as payload,
      hra.created_at as sort_created_at,
      hra.id as sort_id
    from public.hiring_request_approvals hra
    join public.hiring_requests hr
      on hr.id = hra.hiring_request_id
    where hra.step_code = 'contracts_control'
      and hra.status = 'pending'
      and (
        public.user_is_admin(current_user_id)
        or hra.approver_user_id = current_user_id
        or public.user_has_role(current_user_id, 'control_contratos')
      )
    order by hra.created_at asc, hra.id asc
    limit 20
  ) as queue_row;

  select coalesce(
    jsonb_agg(case_row.payload order by case_row.sort_opened_at desc),
    '[]'::jsonb
  )
  into active_cases
  from (
    select
      jsonb_build_object(
        'id', rc.id,
        'case_code', rc.case_code,
        'status', rc.status,
        'requested_vacancies', rc.requested_vacancies,
        'filled_vacancies', rc.filled_vacancies,
        'title', rc.title,
        'contract_name', rc.contract_name,
        'job_position_name', rc.job_position_name,
        'cost_center_code', rc.cost_center_code,
        'cost_center_name', rc.cost_center_name,
        'requested_entry_date', rc.requested_entry_date,
        'target_close_date', rc.target_close_date,
        'opened_at', rc.opened_at,
        'owner_name', owner_profile.full_name,
        'owner_user_id', owner_assignment.user_id,
        'candidate_count', coalesce(candidate_stats.candidate_count, 0),
        'ready_candidates', coalesce(candidate_stats.ready_candidates, 0),
        'hired_candidates', coalesce(candidate_stats.hired_candidates, 0)
      ) as payload,
      rc.opened_at as sort_opened_at
    from public.recruitment_cases rc
    left join lateral (
      select
        rca.user_id,
        rca.assignment_role
      from public.recruitment_case_assignments rca
      where rca.recruitment_case_id = rc.id
        and rca.is_primary = true
      order by rca.id asc
      limit 1
    ) as owner_assignment on true
    left join public.profiles owner_profile
      on owner_profile.id = owner_assignment.user_id
    left join lateral (
      select
        count(*) as candidate_count,
        count(*) filter (where rcc.stage_code = 'ready_for_hire') as ready_candidates,
        count(*) filter (where rcc.stage_code = 'hired') as hired_candidates
      from public.recruitment_case_candidates rcc
      where rcc.recruitment_case_id = rc.id
    ) as candidate_stats on true
    where public.user_can_access_recruitment_case(current_user_id, rc.id)
    order by rc.opened_at desc
    limit 30
  ) as case_row;

  return jsonb_build_object(
    'summary', summary,
    'pending_approvals', pending_approvals,
    'active_cases', active_cases
  );
end;
$function$;

create or replace function public.get_recruitment_case_detail(
  p_case_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  case_payload jsonb;
  assignments_payload jsonb := '[]'::jsonb;
  candidates_payload jsonb := '[]'::jsonb;
  audit_payload jsonb := '[]'::jsonb;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_can_access_recruitment_case(current_user_id, p_case_id) then
    raise exception 'Sin permisos para ver este caso';
  end if;

  select jsonb_build_object(
    'id', rc.id,
    'case_code', rc.case_code,
    'status', rc.status,
    'requested_vacancies', rc.requested_vacancies,
    'filled_vacancies', rc.filled_vacancies,
    'title', rc.title,
    'contract_name', rc.contract_name,
    'job_position_name', rc.job_position_name,
    'cost_center_code', rc.cost_center_code,
    'cost_center_name', rc.cost_center_name,
    'requested_entry_date', rc.requested_entry_date,
    'target_close_date', rc.target_close_date,
    'opened_at', rc.opened_at,
    'close_reason', rc.close_reason,
    'hiring_request', jsonb_build_object(
      'id', hr.id,
      'folio', hr.folio,
      'requester_name', hr.requester_name,
      'requester_email', hr.requester_email,
      'start_date', hr.start_date,
      'end_date', hr.end_date,
      'shift_name', hr.shift_name,
      'salary_offer', hr.salary_offer,
      'campamento', hr.campamento,
      'pasajes', hr.pasajes,
      'other_benefits', hr.other_benefits
    )
  )
  into case_payload
  from public.recruitment_cases rc
  join public.hiring_requests hr
    on hr.id = rc.hiring_request_id
  where rc.id = p_case_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', rca.id,
        'user_id', rca.user_id,
        'assignment_role', rca.assignment_role,
        'is_primary', rca.is_primary,
        'assigned_at', rca.assigned_at,
        'full_name', p.full_name,
        'email', p.email
      )
      order by rca.is_primary desc, rca.id asc
    ),
    '[]'::jsonb
  )
  into assignments_payload
  from public.recruitment_case_assignments rca
  join public.profiles p
    on p.id = rca.user_id
  where rca.recruitment_case_id = p_case_id;

  select coalesce(
    jsonb_agg(candidate_row.payload order by candidate_row.sort_created_at asc),
    '[]'::jsonb
  )
  into candidates_payload
  from (
    select
      jsonb_build_object(
        'id', rcc.id,
        'candidate_profile_id', cp.id,
        'national_id', cp.national_id,
        'full_name', cp.full_name,
        'email', cp.email,
        'phone', cp.phone,
        'driver_license_number', cp.driver_license_number,
        'driver_license_class', cp.driver_license_class,
        'driver_license_expiry', cp.driver_license_expiry,
        'stage_code', rcc.stage_code,
        'stage_entered_at', rcc.stage_entered_at,
        'suitability_status', rcc.suitability_status,
        'is_selected', rcc.is_selected,
        'hired_at', rcc.hired_at,
        'created_at', rcc.created_at,
        'stage_history', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'id', sh.id,
              'from_stage', sh.from_stage,
              'to_stage', sh.to_stage,
              'changed_by', sh.changed_by,
              'reason_code', sh.reason_code,
              'comment', sh.comment,
              'created_at', sh.created_at
            )
            order by sh.created_at desc
          )
          from public.recruitment_case_candidate_stage_history sh
          where sh.recruitment_case_candidate_id = rcc.id
        ), '[]'::jsonb)
      ) as payload,
      rcc.created_at as sort_created_at
    from public.recruitment_case_candidates rcc
    join public.candidate_profiles cp
      on cp.id = rcc.candidate_profile_id
    where rcc.recruitment_case_id = p_case_id
  ) as candidate_row;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', al.id,
        'action_type', al.action_type,
        'actor_user_id', al.actor_user_id,
        'actor_name', actor_profile.full_name,
        'old_values', al.old_values,
        'new_values', al.new_values,
        'metadata', al.metadata,
        'created_at', al.created_at
      )
      order by al.created_at desc
    ),
    '[]'::jsonb
  )
  into audit_payload
  from public.recruitment_case_audit_log al
  left join public.profiles actor_profile
    on actor_profile.id = al.actor_user_id
  where al.recruitment_case_id = p_case_id
  limit 40;

  return jsonb_build_object(
    'case', case_payload,
    'assignments', assignments_payload,
    'candidates', candidates_payload,
    'audit', audit_payload
  );
end;
$function$;

create or replace function public.add_candidate_to_recruitment_case(
  p_case_id uuid,
  p_national_id text,
  p_full_name text,
  p_email text default null,
  p_phone text default null
)
returns table (
  case_candidate_id uuid,
  candidate_profile_id uuid
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  case_record public.recruitment_cases%rowtype;
  profile_id uuid;
  created_case_candidate_id uuid;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if not public.user_can_access_recruitment_case(current_user_id, p_case_id) then
    raise exception 'Sin permisos para actualizar este caso';
  end if;

  select *
    into case_record
    from public.recruitment_cases rc
   where rc.id = p_case_id
   for update;

  if case_record.id is null then
    raise exception 'No existe el caso indicado';
  end if;

  if case_record.status in ('filled', 'closed_unfilled', 'cancelled') then
    raise exception 'El caso ya no acepta candidatos nuevos';
  end if;

  if nullif(trim(coalesce(p_national_id, '')), '') is null then
    raise exception 'El identificador del candidato es obligatorio';
  end if;

  if nullif(trim(coalesce(p_full_name, '')), '') is null then
    raise exception 'El nombre del candidato es obligatorio';
  end if;

  insert into public.candidate_profiles (
    national_id,
    full_name,
    email,
    phone
  )
  values (
    trim(p_national_id),
    trim(p_full_name),
    nullif(trim(coalesce(p_email, '')), ''),
    nullif(trim(coalesce(p_phone, '')), '')
  )
  on conflict (national_id) do update
  set
    full_name = excluded.full_name,
    email = coalesce(excluded.email, public.candidate_profiles.email),
    phone = coalesce(excluded.phone, public.candidate_profiles.phone),
    updated_at = timezone('utc', now())
  returning id into profile_id;

  insert into public.recruitment_case_candidates (
    recruitment_case_id,
    candidate_profile_id,
    stage_code,
    stage_entered_at,
    suitability_status,
    is_selected,
    created_by
  )
  values (
    p_case_id,
    profile_id,
    'lead',
    timezone('utc', now()),
    'unknown',
    false,
    current_user_id
  )
  on conflict (recruitment_case_id, candidate_profile_id) do nothing
  returning id into created_case_candidate_id;

  if created_case_candidate_id is null then
    select rcc.id
      into created_case_candidate_id
      from public.recruitment_case_candidates rcc
     where rcc.recruitment_case_id = p_case_id
       and rcc.candidate_profile_id = profile_id;
  else
    insert into public.recruitment_case_candidate_stage_history (
      recruitment_case_candidate_id,
      from_stage,
      to_stage,
      changed_by,
      reason_code,
      comment
    )
    values (
      created_case_candidate_id,
      null,
      'lead',
      current_user_id,
      'candidate_added',
      null
    );

    insert into public.recruitment_case_audit_log (
      recruitment_case_id,
      recruitment_case_candidate_id,
      actor_user_id,
      action_type,
      new_values,
      metadata
    )
    values (
      p_case_id,
      created_case_candidate_id,
      current_user_id,
      'candidate_added',
      jsonb_build_object(
        'candidate_profile_id', profile_id,
        'full_name', trim(p_full_name),
        'stage_code', 'lead'
      ),
      jsonb_build_object('national_id', trim(p_national_id))
    );
  end if;

  perform public.sync_recruitment_case_status(p_case_id, current_user_id);

  return query
  select created_case_candidate_id, profile_id;
end;
$function$;

create or replace function public.advance_recruitment_candidate_stage(
  p_case_candidate_id uuid,
  p_to_stage text,
  p_comment text default null
)
returns table (
  recruitment_case_id uuid,
  stage_code text,
  case_status text
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  candidate_record public.recruitment_case_candidates%rowtype;
  normalized_comment text := nullif(trim(coalesce(p_comment, '')), '');
  next_case_status text;
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if p_to_stage not in ('lead', 'contacted', 'screening', 'shortlisted', 'documents_pending', 'ready_for_hire', 'hired', 'rejected', 'withdrawn') then
    raise exception 'Etapa invalida';
  end if;

  select *
    into candidate_record
    from public.recruitment_case_candidates rcc
   where rcc.id = p_case_candidate_id
   for update;

  if candidate_record.id is null then
    raise exception 'No existe el candidato del caso';
  end if;

  if not public.user_can_access_recruitment_case(current_user_id, candidate_record.recruitment_case_id) then
    raise exception 'Sin permisos para actualizar este candidato';
  end if;

  if candidate_record.stage_code in ('hired', 'rejected', 'withdrawn') then
    raise exception 'El candidato ya se encuentra en una etapa terminal';
  end if;

  if candidate_record.stage_code = p_to_stage then
    raise exception 'El candidato ya se encuentra en esa etapa';
  end if;

  update public.recruitment_case_candidates rcc
     set stage_code = p_to_stage,
         stage_entered_at = timezone('utc', now()),
         is_selected = case when p_to_stage = 'hired' then true else rcc.is_selected end,
         hired_at = case when p_to_stage = 'hired' then timezone('utc', now()) else rcc.hired_at end,
         rejection_reason = case when p_to_stage = 'rejected' then normalized_comment else rcc.rejection_reason end,
         withdrawal_reason = case when p_to_stage = 'withdrawn' then normalized_comment else rcc.withdrawal_reason end,
         suitability_status = case
           when p_to_stage = 'ready_for_hire' then 'fit'
           when p_to_stage in ('rejected', 'withdrawn') then 'blocked'
           else rcc.suitability_status
         end,
         updated_at = timezone('utc', now())
   where rcc.id = p_case_candidate_id;

  insert into public.recruitment_case_candidate_stage_history (
    recruitment_case_candidate_id,
    from_stage,
    to_stage,
    changed_by,
    reason_code,
    comment
  )
  values (
    p_case_candidate_id,
    candidate_record.stage_code,
    p_to_stage,
    current_user_id,
    'manual_transition',
    normalized_comment
  );

  insert into public.recruitment_case_audit_log (
    recruitment_case_id,
    recruitment_case_candidate_id,
    actor_user_id,
    action_type,
    old_values,
    new_values,
    metadata
  )
  values (
    candidate_record.recruitment_case_id,
    candidate_record.id,
    current_user_id,
    case when p_to_stage = 'hired' then 'candidate_hired' else 'candidate_stage_changed' end,
    jsonb_build_object(
      'stage_code', candidate_record.stage_code,
      'is_selected', candidate_record.is_selected,
      'hired_at', candidate_record.hired_at
    ),
    jsonb_build_object(
      'stage_code', p_to_stage,
      'is_selected', case when p_to_stage = 'hired' then true else candidate_record.is_selected end,
      'hired_at', case when p_to_stage = 'hired' then timezone('utc', now()) else candidate_record.hired_at end
    ),
    jsonb_build_object('comment', normalized_comment)
  );

  next_case_status := public.sync_recruitment_case_status(candidate_record.recruitment_case_id, current_user_id);

  return query
  select candidate_record.recruitment_case_id, p_to_stage, next_case_status;
end;
$function$;

alter table public.recruitment_cases enable row level security;
alter table public.recruitment_case_assignments enable row level security;
alter table public.candidate_profiles enable row level security;
alter table public.recruitment_case_candidates enable row level security;
alter table public.recruitment_case_candidate_stage_history enable row level security;
alter table public.recruitment_case_audit_log enable row level security;

drop policy if exists "recruitment_cases_select_scoped" on public.recruitment_cases;
create policy "recruitment_cases_select_scoped"
on public.recruitment_cases
for select
to authenticated
using (public.user_can_access_recruitment_case(auth.uid(), id));

drop policy if exists "recruitment_case_assignments_select_scoped" on public.recruitment_case_assignments;
create policy "recruitment_case_assignments_select_scoped"
on public.recruitment_case_assignments
for select
to authenticated
using (public.user_can_access_recruitment_case(auth.uid(), recruitment_case_id));

drop policy if exists "candidate_profiles_select_scoped" on public.candidate_profiles;
create policy "candidate_profiles_select_scoped"
on public.candidate_profiles
for select
to authenticated
using (
  public.user_is_admin(auth.uid())
  or public.user_has_role(auth.uid(), 'control_contratos')
  or exists (
    select 1
    from public.recruitment_case_candidates rcc
    join public.recruitment_cases rc
      on rc.id = rcc.recruitment_case_id
    where rcc.candidate_profile_id = candidate_profiles.id
      and public.user_can_access_recruitment_case(auth.uid(), rc.id)
  )
);

drop policy if exists "recruitment_case_candidates_select_scoped" on public.recruitment_case_candidates;
create policy "recruitment_case_candidates_select_scoped"
on public.recruitment_case_candidates
for select
to authenticated
using (public.user_can_access_recruitment_case(auth.uid(), recruitment_case_id));

drop policy if exists "recruitment_case_candidate_stage_history_select_scoped" on public.recruitment_case_candidate_stage_history;
create policy "recruitment_case_candidate_stage_history_select_scoped"
on public.recruitment_case_candidate_stage_history
for select
to authenticated
using (
  exists (
    select 1
    from public.recruitment_case_candidates rcc
    where rcc.id = recruitment_case_candidate_id
      and public.user_can_access_recruitment_case(auth.uid(), rcc.recruitment_case_id)
  )
);

drop policy if exists "recruitment_case_audit_log_select_scoped" on public.recruitment_case_audit_log;
create policy "recruitment_case_audit_log_select_scoped"
on public.recruitment_case_audit_log
for select
to authenticated
using (public.user_can_access_recruitment_case(auth.uid(), recruitment_case_id));

grant select on public.recruitment_cases to authenticated;
grant select on public.recruitment_case_assignments to authenticated;
grant select on public.candidate_profiles to authenticated;
grant select on public.recruitment_case_candidates to authenticated;
grant select on public.recruitment_case_candidate_stage_history to authenticated;
grant select on public.recruitment_case_audit_log to authenticated;

grant execute on function public.open_recruitment_case_from_hiring_request(uuid, uuid) to authenticated;
grant execute on function public.get_recruitment_control_dashboard_v2() to authenticated;
grant execute on function public.get_recruitment_case_detail(uuid) to authenticated;
grant execute on function public.add_candidate_to_recruitment_case(uuid, text, text, text, text) to authenticated;
grant execute on function public.advance_recruitment_candidate_stage(uuid, text, text) to authenticated;

do $$
declare
  target_request_id uuid;
begin
  for target_request_id in
    select hr.id
    from public.hiring_requests hr
    left join public.recruitment_cases rc
      on rc.hiring_request_id = hr.id
    where hr.status = 'approved'
      and rc.id is null
  loop
    perform public.open_recruitment_case_from_hiring_request(target_request_id, null);
  end loop;
end $$;

create or replace function public.decide_hiring_request_approval_v2(
  p_approval_id bigint,
  p_decision text,
  p_comment text default null
)
returns table (
  hiring_request_id uuid,
  request_status text,
  decided_step text
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  approval_record public.hiring_request_approvals%rowtype;
  request_record public.hiring_requests%rowtype;
  contracts_control_record public.workflow_approvers%rowtype;
  next_approval_id bigint;
  normalized_comment text := nullif(trim(coalesce(p_comment, '')), '');
begin
  if current_user_id is null then
    raise exception 'Usuario no autenticado';
  end if;

  if p_decision not in ('approved', 'rejected') then
    raise exception 'Decision invalida';
  end if;

  select *
    into approval_record
    from public.hiring_request_approvals hra
   where hra.id = p_approval_id
   for update;

  if approval_record.id is null then
    raise exception 'No existe la aprobacion solicitada';
  end if;

  if approval_record.status <> 'pending' then
    raise exception 'La aprobacion ya fue resuelta y no puede volver a decidirse';
  end if;

  if approval_record.step_code not in ('area_manager', 'contracts_control') then
    raise exception 'La etapa indicada no admite decision por esta via';
  end if;

  if approval_record.approver_user_id is null or approval_record.approver_user_id <> current_user_id then
    raise exception 'El usuario no esta autorizado para decidir esta aprobacion';
  end if;

  select *
    into request_record
    from public.hiring_requests hr
   where hr.id = approval_record.hiring_request_id
   for update;

  if request_record.id is null then
    raise exception 'No existe la solicitud asociada a la aprobacion';
  end if;

  if request_record.current_step_code is distinct from approval_record.step_code then
    raise exception 'La solicitud no se encuentra en la etapa actual de esta aprobacion';
  end if;

  if approval_record.step_code = 'area_manager'
     and request_record.status <> 'pending_area_manager' then
    raise exception 'La solicitud no esta pendiente de Gerente de Area';
  end if;

  if approval_record.step_code = 'contracts_control'
     and request_record.status <> 'pending_contracts_control' then
    raise exception 'La solicitud no esta pendiente de Control de Contratos';
  end if;

  update public.hiring_request_approvals hra
     set status = p_decision,
         decision_by = current_user_id,
         decision_comment = normalized_comment,
         decided_at = timezone('utc', now()),
         locked_at = timezone('utc', now()),
         updated_at = timezone('utc', now())
   where hra.id = approval_record.id
     and hra.status = 'pending';

  if p_decision = 'rejected' then
    update public.hiring_requests hr
       set status = 'rejected',
           current_step_code = null,
           rejected_at = timezone('utc', now()),
           final_decided_by = current_user_id,
           updated_at = timezone('utc', now())
     where hr.id = request_record.id;

    insert into public.hiring_request_audit_log (
      hiring_request_id,
      approval_id,
      actor_user_id,
      action_type,
      old_values,
      new_values,
      metadata
    )
    values (
      request_record.id,
      approval_record.id,
      current_user_id,
      'rejected',
      jsonb_build_object(
        'request_status', request_record.status,
        'current_step_code', request_record.current_step_code,
        'approval_status', approval_record.status
      ),
      jsonb_build_object(
        'request_status', 'rejected',
        'current_step_code', null,
        'approval_status', 'rejected'
      ),
      jsonb_build_object(
        'step_code', approval_record.step_code,
        'comment', normalized_comment
      )
    );

    return query
    select request_record.id, 'rejected'::text, approval_record.step_code;
    return;
  end if;

  if approval_record.step_code = 'area_manager' then
    select *
      into contracts_control_record
      from public.workflow_approvers wa
     where wa.step_code = 'contracts_control'
       and wa.is_active = true
     for share;

    if contracts_control_record.step_code is null then
      raise exception 'No existe aprobador configurado para Control de Contratos';
    end if;

    if contracts_control_record.approver_user_id is null then
      raise exception 'Control de Contratos aun no tiene usuario vinculado en la plataforma';
    end if;

    if not exists (
      select 1
      from public.profiles p
      where p.id = contracts_control_record.approver_user_id
        and p.status = 'active'
    ) then
      raise exception 'El usuario configurado para Control de Contratos no tiene una cuenta activa';
    end if;

    if exists (
      select 1
      from public.hiring_request_approvals hra_existing
      where hra_existing.hiring_request_id = request_record.id
        and hra_existing.step_code = 'contracts_control'
    ) then
      raise exception 'La aprobacion de Control de Contratos ya existe para esta solicitud';
    end if;

    insert into public.hiring_request_approvals (
      hiring_request_id,
      step_code,
      step_name,
      step_order,
      approver_user_id,
      approver_name,
      approver_email,
      status,
      created_at,
      updated_at
    )
    values (
      request_record.id,
      'contracts_control',
      'Control de contratos',
      3,
      contracts_control_record.approver_user_id,
      contracts_control_record.approver_name,
      contracts_control_record.approver_email,
      'pending',
      timezone('utc', now()),
      timezone('utc', now())
    )
    returning id into next_approval_id;

    update public.hiring_requests hr
       set status = 'pending_contracts_control',
           current_step_code = 'contracts_control',
           updated_at = timezone('utc', now())
     where hr.id = request_record.id;

    insert into public.hiring_request_audit_log (
      hiring_request_id,
      approval_id,
      actor_user_id,
      action_type,
      old_values,
      new_values,
      metadata
    )
    values (
      request_record.id,
      approval_record.id,
      current_user_id,
      'approved',
      jsonb_build_object(
        'request_status', request_record.status,
        'current_step_code', request_record.current_step_code,
        'approval_status', approval_record.status
      ),
      jsonb_build_object(
        'request_status', 'pending_contracts_control',
        'current_step_code', 'contracts_control',
        'approval_status', 'approved'
      ),
      jsonb_build_object(
        'step_code', approval_record.step_code,
        'comment', normalized_comment
      )
    );

    insert into public.hiring_request_audit_log (
      hiring_request_id,
      approval_id,
      actor_user_id,
      action_type,
      new_values,
      metadata
    )
    values (
      request_record.id,
      next_approval_id,
      current_user_id,
      'approval_created',
      jsonb_build_object(
        'step_code', 'contracts_control',
        'step_name', 'Control de contratos',
        'approver_user_id', contracts_control_record.approver_user_id,
        'approver_name', contracts_control_record.approver_name,
        'approver_email', contracts_control_record.approver_email,
        'status', 'pending'
      ),
      jsonb_build_object('created_by_flow', 'decide_hiring_request_approval_v2')
    );

    return query
    select request_record.id, 'pending_contracts_control'::text, approval_record.step_code;
    return;
  end if;

  update public.hiring_requests hr
     set status = 'approved',
         current_step_code = null,
         approved_at = timezone('utc', now()),
         final_decided_by = current_user_id,
         updated_at = timezone('utc', now())
   where hr.id = request_record.id;

  insert into public.hiring_request_audit_log (
    hiring_request_id,
    approval_id,
    actor_user_id,
    action_type,
    old_values,
    new_values,
    metadata
  )
  values (
    request_record.id,
    approval_record.id,
    current_user_id,
    'approved',
    jsonb_build_object(
      'request_status', request_record.status,
      'current_step_code', request_record.current_step_code,
      'approval_status', approval_record.status
    ),
    jsonb_build_object(
      'request_status', 'approved',
      'current_step_code', null,
      'approval_status', 'approved'
    ),
    jsonb_build_object(
      'step_code', approval_record.step_code,
      'comment', normalized_comment
    )
  );

  perform public.open_recruitment_case_from_hiring_request(request_record.id, current_user_id);

  return query
  select request_record.id, 'approved'::text, approval_record.step_code;
end;
$function$;

grant execute on function public.decide_hiring_request_approval_v2(bigint, text, text) to authenticated;

notify pgrst, 'reload schema';

commit;
