begin;

create or replace function public.user_can_manage_operations(target_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select
    target_user_id is not null
    and (
      public.user_is_admin(target_user_id)
      or public.user_can_access_module(target_user_id, 'operaciones')
    );
$function$;

revoke all on function public.user_can_manage_operations(uuid) from public, anon;
grant execute on function public.user_can_manage_operations(uuid) to authenticated;

create or replace function public.map_operations_driver_shift_status(p_effective_status text)
returns text
language sql
immutable
set search_path = public
as $function$
  select case
    when coalesce(nullif(trim(coalesce(p_effective_status, '')), ''), 'unassigned') in ('working', 'extra_shift') then 'en_turno'
    else 'fuera_de_turno'
  end;
$function$;

revoke all on function public.map_operations_driver_shift_status(text) from public, anon;
grant execute on function public.map_operations_driver_shift_status(text) to authenticated;

create table if not exists public.base_services (
  id bigint generated by default as identity primary key,
  external_key bigint not null,
  operational_name text not null,
  company_name text not null,
  service_type text not null,
  contractual_name text not null,
  contractual_category text not null,
  schedule_label text not null,
  contract_id bigint not null references public.contracts (id) on delete restrict,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.base_services
  add column if not exists external_key bigint,
  add column if not exists operational_name text,
  add column if not exists company_name text,
  add column if not exists service_type text,
  add column if not exists contractual_name text,
  add column if not exists contractual_category text,
  add column if not exists schedule_label text,
  add column if not exists contract_id bigint references public.contracts (id) on delete restrict,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists idx_base_services_external_key
  on public.base_services (external_key);

create index if not exists idx_base_services_contract_active
  on public.base_services (contract_id, is_active, external_key);

drop trigger if exists trg_base_services_set_updated_at on public.base_services;
create trigger trg_base_services_set_updated_at
before update on public.base_services
for each row
execute function public.set_updated_at();

create table if not exists public.equipment (
  equipment_code text primary key,
  plate text,
  equipment_type text,
  current_client text,
  brand text,
  model text,
  year text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.equipment
  add column if not exists plate text,
  add column if not exists equipment_type text,
  add column if not exists current_client text,
  add column if not exists brand text,
  add column if not exists model text,
  add column if not exists year text,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create index if not exists idx_equipment_active_code
  on public.equipment (is_active, equipment_code);

drop trigger if exists trg_equipment_set_updated_at on public.equipment;
create trigger trg_equipment_set_updated_at
before update on public.equipment
for each row
execute function public.set_updated_at();

create table if not exists public.service_entries (
  id uuid primary key default gen_random_uuid(),
  service_date date not null,
  shift text not null,
  base_service_id bigint not null references public.base_services (id) on delete restrict,
  contract_id bigint not null references public.contracts (id) on delete restrict,
  contract_code text not null,
  service_operational_name text not null,
  service_contractual_name text,
  service_category text,
  service_company text,
  driver_buk_employee_id text,
  driver_name text,
  driver_document text,
  driver_area text,
  driver_shift_status text,
  driver_shift_source text,
  driver_roster_base_status text,
  driver_roster_effective_status text,
  equipment_code text not null references public.equipment (equipment_code) on delete restrict,
  equipment_plate text,
  equipment_type text,
  equipment_client text,
  created_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.service_entries
  add column if not exists service_date date,
  add column if not exists shift text,
  add column if not exists base_service_id bigint references public.base_services (id) on delete restrict,
  add column if not exists contract_id bigint references public.contracts (id) on delete restrict,
  add column if not exists contract_code text,
  add column if not exists service_operational_name text,
  add column if not exists service_contractual_name text,
  add column if not exists service_category text,
  add column if not exists service_company text,
  add column if not exists driver_buk_employee_id text,
  add column if not exists driver_name text,
  add column if not exists driver_document text,
  add column if not exists driver_area text,
  add column if not exists driver_shift_status text,
  add column if not exists driver_shift_source text,
  add column if not exists driver_roster_base_status text,
  add column if not exists driver_roster_effective_status text,
  add column if not exists equipment_code text references public.equipment (equipment_code) on delete restrict,
  add column if not exists equipment_plate text,
  add column if not exists equipment_type text,
  add column if not exists equipment_client text,
  add column if not exists created_by uuid references public.profiles (id) on delete restrict,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists idx_service_entries_operational_key
  on public.service_entries (service_date, shift, contract_id, base_service_id, created_by);

create index if not exists idx_service_entries_dashboard_scope
  on public.service_entries (service_date desc, contract_code, shift);

create index if not exists idx_service_entries_driver_scope
  on public.service_entries (driver_buk_employee_id, service_date desc);

drop trigger if exists trg_service_entries_set_updated_at on public.service_entries;
create trigger trg_service_entries_set_updated_at
before update on public.service_entries
for each row
execute function public.set_updated_at();

alter table public.base_services enable row level security;
alter table public.equipment enable row level security;
alter table public.service_entries enable row level security;

drop policy if exists "operations_base_services_select" on public.base_services;
create policy "operations_base_services_select"
on public.base_services
for select
to authenticated
using (public.user_can_manage_operations((select auth.uid())));

drop policy if exists "operations_equipment_select" on public.equipment;
create policy "operations_equipment_select"
on public.equipment
for select
to authenticated
using (public.user_can_manage_operations((select auth.uid())));

drop policy if exists "operations_service_entries_select" on public.service_entries;
create policy "operations_service_entries_select"
on public.service_entries
for select
to authenticated
using (public.user_can_manage_operations((select auth.uid())));

grant select on public.base_services to authenticated;
grant select on public.equipment to authenticated;
grant select on public.service_entries to authenticated;

revoke insert, update, delete on public.base_services from authenticated;
revoke insert, update, delete on public.equipment from authenticated;
revoke insert, update, delete on public.service_entries from authenticated;

create or replace function public.search_operations_drivers(
  p_search text default null,
  p_service_date date default current_date,
  p_limit integer default 12
)
returns table (
  buk_employee_id text,
  full_name text,
  document_number text,
  document_type text,
  job_title text,
  contract_code text,
  area_name text,
  display_label text,
  roster_base_status text,
  roster_effective_status text,
  is_working_day boolean,
  is_rest_day boolean
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid := auth.uid();
  normalized_search text := lower(trim(coalesce(p_search, '')));
  normalized_digits text := public.build_employee_document_digits(p_search, '{}'::jsonb);
  safe_limit integer := least(greatest(coalesce(p_limit, 12), 1), 30);
  resolved_service_date date := coalesce(p_service_date, current_date);
begin
  if not public.user_can_manage_operations(current_user_id) then
    raise exception 'Sin permisos para buscar conductores de operaciones';
  end if;

  if length(normalized_search) < 2 and length(normalized_digits) < 4 then
    return;
  end if;

  return query
  with matching_workers as (
    select
      e.buk_employee_id,
      e.full_name,
      e.raw_payload,
      coalesce(
        nullif(trim(coalesce(e.document_number, '')), ''),
        nullif(trim(coalesce(e.raw_payload ->> 'document_number', '')), ''),
        nullif(trim(coalesce(e.raw_payload ->> 'rut', '')), '')
      ) as document_number,
      coalesce(
        nullif(trim(coalesce(e.document_type, '')), ''),
        nullif(trim(coalesce(e.raw_payload ->> 'document_type', '')), ''),
        'rut'
      ) as document_type,
      public.resolve_active_employee_job_title(e.raw_payload, e.job_title) as resolved_job_title,
      nullif(trim(e.contract_code), '') as contract_code,
      nullif(trim(e.area_name), '') as area_name,
      public.build_buk_employee_name_search_key(e.full_name, e.raw_payload) as name_search_key,
      public.build_employee_document_digits(e.document_number, e.raw_payload) as document_digits,
      row_number() over (
        partition by public.build_active_employee_identity_key(
          e.document_type,
          e.document_number,
          e.buk_employee_id,
          e.raw_payload
        )
        order by e.updated_at desc nulls last, e.created_at desc nulls last, e.buk_employee_id desc
      ) as identity_rank
    from public.employees_active_current e
    where
      (
        normalized_search <> ''
        and public.build_active_employee_search_text(
          e.full_name,
          e.document_number,
          e.job_title,
          e.contract_code,
          e.area_name,
          e.raw_payload
        ) like '%' || normalized_search || '%'
      )
      or (
        normalized_digits <> ''
        and public.build_employee_document_digits(e.document_number, e.raw_payload)
          like '%' || normalized_digits || '%'
      )
  )
  select
    mw.buk_employee_id,
    mw.full_name,
    mw.document_number,
    mw.document_type,
    mw.resolved_job_title as job_title,
    mw.contract_code,
    mw.area_name,
    concat_ws(
      ' | ',
      coalesce(mw.document_number, 'Sin RUT'),
      coalesce(mw.resolved_job_title, 'Sin cargo'),
      mw.full_name,
      coalesce(mw.area_name, mw.contract_code, 'Sin contrato')
    ) as display_label,
    rs.base_status as roster_base_status,
    rs.effective_status as roster_effective_status,
    rs.is_working_day,
    rs.is_rest_day
  from matching_workers mw
  cross join lateral public.resolve_hr_roster_day_status(mw.buk_employee_id, resolved_service_date) rs
  where mw.identity_rank = 1
  order by
    case
      when normalized_search <> '' and mw.name_search_key like normalized_search || '%' then 0
      when normalized_search <> '' and lower(mw.full_name) like normalized_search || '%' then 1
      when normalized_digits <> '' and mw.document_digits like normalized_digits || '%' then 2
      else 3
    end,
    mw.full_name asc
  limit safe_limit;
end;
$function$;

revoke all on function public.search_operations_drivers(text, date, integer) from public, anon;
grant execute on function public.search_operations_drivers(text, date, integer) to authenticated;

create or replace function public.submit_service_entries_batch(p_entries jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  current_user_id uuid;
  entry_item jsonb;
  entry_index integer;
  errors jsonb := '[]'::jsonb;
  saved_count integer := 0;
  resolved_contract_id bigint;
  resolved_contract_code text;
  resolved_service_id bigint;
  resolved_service_is_active boolean;
  resolved_service_operational_name text;
  resolved_service_company_name text;
  resolved_service_contractual_name text;
  resolved_service_contractual_category text;
  resolved_equipment_code text;
  resolved_equipment_plate text;
  resolved_equipment_type text;
  resolved_equipment_client text;
  resolved_equipment_is_active boolean;
  resolved_driver_buk_employee_id text;
  resolved_driver_name text;
  resolved_driver_document text;
  resolved_driver_area text;
  resolved_driver_base_status text;
  resolved_driver_effective_status text;
  resolved_driver_shift_status text;
  entry_driver_buk_employee_id text;
  entry_driver_document_digits text;
  entry_driver_search text;
  entry_driver_area_search text;
  existing_entry_id uuid;
  lock_key text;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    raise exception 'Usuario no autenticado.';
  end if;

  if not public.user_can_manage_operations(current_user_id) then
    raise exception 'Sin permisos para registrar servicios operacionales.';
  end if;

  if jsonb_typeof(p_entries) <> 'array' then
    raise exception 'El payload de planificación debe ser un arreglo.';
  end if;

  if jsonb_array_length(p_entries) = 0 then
    return jsonb_build_object('ok', false, 'errors', jsonb_build_array(jsonb_build_object(
      'index', 0,
      'field_errors', jsonb_build_object('payload', 'No hay servicios para guardar.')
    )));
  end if;

  for entry_item, entry_index in
    select value, ordinality::integer
    from jsonb_array_elements(p_entries) with ordinality
  loop
    if jsonb_typeof(entry_item) <> 'object' then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'field_errors', jsonb_build_object('payload', 'Cada servicio debe ser un objeto.')
      );
      continue;
    end if;

    if nullif(trim(entry_item->>'contractCode'), '') is null then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('contractCode', 'Contrato requerido.')
      );
      continue;
    end if;

    if coalesce(entry_item->>'serviceExternalKey', '') !~ '^[0-9]+$' then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('serviceExternalKey', 'Servicio requerido o inválido.')
      );
      continue;
    end if;

    if coalesce(entry_item->>'serviceDate', '') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('serviceDate', 'Fecha de servicio inválida.')
      );
      continue;
    end if;

    if lower(coalesce(entry_item->>'shift', '')) not in ('am', 'pm') then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('shift', 'Turno requerido o inválido.')
      );
      continue;
    end if;

    if nullif(trim(entry_item->>'equipmentCode'), '') is null then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('equipmentCode', 'Equipo requerido.')
      );
      continue;
    end if;

    select
      c.id,
      coalesce(nullif(trim(c.contract_name), ''), c.code)
      into resolved_contract_id, resolved_contract_code
     from public.contracts c
     where (
       c.code = nullif(trim(entry_item->>'contractCode'), '')
       or c.contract_name = nullif(trim(entry_item->>'contractCode'), '')
       or c.contract_name = replace(nullif(trim(entry_item->>'contractCode'), ''), 'SERVICIO ', '')
     )
       and c.is_active = true
     limit 1;

    if resolved_contract_id is null then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('contractCode', 'Contrato no encontrado.')
      );
      continue;
    end if;

    if not exists (
      select 1
        from public.user_contracts uc
       where uc.user_id = current_user_id
         and uc.contract_id = resolved_contract_id
    ) then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('contractCode', 'No tienes acceso a este contrato.')
      );
      continue;
    end if;

    select
      bs.id,
      bs.is_active,
      bs.operational_name,
      bs.company_name,
      bs.contractual_name,
      bs.contractual_category
      into
        resolved_service_id,
        resolved_service_is_active,
        resolved_service_operational_name,
        resolved_service_company_name,
        resolved_service_contractual_name,
        resolved_service_contractual_category
      from public.base_services bs
     where bs.external_key = nullif(entry_item->>'serviceExternalKey', '')::bigint
       and bs.contract_id = resolved_contract_id
     limit 1;

    if resolved_service_id is null or resolved_service_is_active is false then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('serviceExternalKey', 'Servicio no disponible para el contrato seleccionado.')
      );
      continue;
    end if;

    select
      e.equipment_code,
      e.plate,
      e.equipment_type,
      e.current_client,
      e.is_active
      into
        resolved_equipment_code,
        resolved_equipment_plate,
        resolved_equipment_type,
        resolved_equipment_client,
        resolved_equipment_is_active
      from public.equipment e
     where e.equipment_code = nullif(trim(entry_item->>'equipmentCode'), '')
     limit 1;

    if resolved_equipment_code is null or resolved_equipment_is_active is false then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('equipmentCode', 'Selecciona un equipo válido.')
      );
      continue;
    end if;

    entry_driver_buk_employee_id := nullif(trim(coalesce(entry_item->>'driverBukEmployeeId', '')), '');
    entry_driver_document_digits := nullif(public.build_employee_document_digits(entry_item->>'driverDocument', '{}'::jsonb), '');
    entry_driver_search := public.normalize_recruitment_search_text(entry_item->>'driverName');
    entry_driver_area_search := public.normalize_recruitment_search_text(entry_item->>'driverArea');

    select
      candidate.buk_employee_id,
      candidate.full_name,
      candidate.document_number,
      candidate.area_name
      into
        resolved_driver_buk_employee_id,
        resolved_driver_name,
        resolved_driver_document,
        resolved_driver_area
      from (
        select
          e.buk_employee_id,
          e.full_name,
          coalesce(
            nullif(trim(coalesce(e.document_number, '')), ''),
            nullif(trim(coalesce(e.raw_payload ->> 'document_number', '')), ''),
            nullif(trim(coalesce(e.raw_payload ->> 'rut', '')), '')
          ) as document_number,
          nullif(trim(e.area_name), '') as area_name,
          public.build_buk_employee_name_search_key(e.full_name, e.raw_payload) as name_search_key,
          public.build_employee_document_digits(e.document_number, e.raw_payload) as document_digits,
          row_number() over (
            partition by public.build_active_employee_identity_key(
              e.document_type,
              e.document_number,
              e.buk_employee_id,
              e.raw_payload
            )
            order by e.updated_at desc nulls last, e.created_at desc nulls last, e.buk_employee_id desc
          ) as identity_rank,
          case
            when entry_driver_buk_employee_id is not null and e.buk_employee_id = entry_driver_buk_employee_id then 0
            when entry_driver_document_digits is not null
              and public.build_employee_document_digits(e.document_number, e.raw_payload) = entry_driver_document_digits then 1
            when entry_driver_search <> ''
              and public.build_active_employee_search_text(
                e.full_name,
                e.document_number,
                e.job_title,
                e.contract_code,
                e.area_name,
                e.raw_payload
              ) like '%' || entry_driver_search || '%' then 2
            else 9
          end as match_priority,
          case
            when entry_driver_area_search <> ''
              and public.normalize_recruitment_search_text(coalesce(e.area_name, '')) like '%' || entry_driver_area_search || '%' then 0
            else 1
          end as area_priority
        from public.employees_active_current e
        where
          (
            entry_driver_buk_employee_id is not null
            and e.buk_employee_id = entry_driver_buk_employee_id
          )
          or (
            entry_driver_document_digits is not null
            and public.build_employee_document_digits(e.document_number, e.raw_payload) = entry_driver_document_digits
          )
          or (
            entry_driver_search <> ''
            and public.build_active_employee_search_text(
              e.full_name,
              e.document_number,
              e.job_title,
              e.contract_code,
              e.area_name,
              e.raw_payload
            ) like '%' || entry_driver_search || '%'
          )
      ) candidate
     where candidate.identity_rank = 1
       and candidate.match_priority < 9
     order by candidate.match_priority, candidate.area_priority, candidate.full_name asc
     limit 1;

    if resolved_driver_buk_employee_id is null then
      errors := errors || jsonb_build_object(
        'index', entry_index - 1,
        'service_id', entry_item->>'serviceId',
        'field_errors', jsonb_build_object('driverName', 'Selecciona un conductor BUK activo y válido.')
      );
      continue;
    end if;
  end loop;

  if jsonb_array_length(errors) > 0 then
    return jsonb_build_object('ok', false, 'errors', errors);
  end if;

  for entry_item, entry_index in
    select value, ordinality::integer
    from jsonb_array_elements(p_entries) with ordinality
  loop
    select
      c.id,
      coalesce(nullif(trim(c.contract_name), ''), c.code)
      into resolved_contract_id, resolved_contract_code
     from public.contracts c
     where (
       c.code = nullif(trim(entry_item->>'contractCode'), '')
       or c.contract_name = nullif(trim(entry_item->>'contractCode'), '')
       or c.contract_name = replace(nullif(trim(entry_item->>'contractCode'), ''), 'SERVICIO ', '')
     )
       and c.is_active = true
     limit 1;

    select
      bs.id,
      bs.operational_name,
      bs.company_name,
      bs.contractual_name,
      bs.contractual_category
      into
        resolved_service_id,
        resolved_service_operational_name,
        resolved_service_company_name,
        resolved_service_contractual_name,
        resolved_service_contractual_category
      from public.base_services bs
     where bs.external_key = nullif(entry_item->>'serviceExternalKey', '')::bigint
       and bs.contract_id = resolved_contract_id
     limit 1;

    select
      e.equipment_code,
      e.plate,
      e.equipment_type,
      e.current_client
      into
        resolved_equipment_code,
        resolved_equipment_plate,
        resolved_equipment_type,
        resolved_equipment_client
      from public.equipment e
     where e.equipment_code = nullif(trim(entry_item->>'equipmentCode'), '')
     limit 1;

    entry_driver_buk_employee_id := nullif(trim(coalesce(entry_item->>'driverBukEmployeeId', '')), '');
    entry_driver_document_digits := nullif(public.build_employee_document_digits(entry_item->>'driverDocument', '{}'::jsonb), '');
    entry_driver_search := public.normalize_recruitment_search_text(entry_item->>'driverName');
    entry_driver_area_search := public.normalize_recruitment_search_text(entry_item->>'driverArea');

    select
      candidate.buk_employee_id,
      candidate.full_name,
      candidate.document_number,
      candidate.area_name
      into
        resolved_driver_buk_employee_id,
        resolved_driver_name,
        resolved_driver_document,
        resolved_driver_area
      from (
        select
          e.buk_employee_id,
          e.full_name,
          coalesce(
            nullif(trim(coalesce(e.document_number, '')), ''),
            nullif(trim(coalesce(e.raw_payload ->> 'document_number', '')), ''),
            nullif(trim(coalesce(e.raw_payload ->> 'rut', '')), '')
          ) as document_number,
          nullif(trim(e.area_name), '') as area_name,
          row_number() over (
            partition by public.build_active_employee_identity_key(
              e.document_type,
              e.document_number,
              e.buk_employee_id,
              e.raw_payload
            )
            order by e.updated_at desc nulls last, e.created_at desc nulls last, e.buk_employee_id desc
          ) as identity_rank,
          case
            when entry_driver_buk_employee_id is not null and e.buk_employee_id = entry_driver_buk_employee_id then 0
            when entry_driver_document_digits is not null
              and public.build_employee_document_digits(e.document_number, e.raw_payload) = entry_driver_document_digits then 1
            when entry_driver_search <> ''
              and public.build_active_employee_search_text(
                e.full_name,
                e.document_number,
                e.job_title,
                e.contract_code,
                e.area_name,
                e.raw_payload
              ) like '%' || entry_driver_search || '%' then 2
            else 9
          end as match_priority,
          case
            when entry_driver_area_search <> ''
              and public.normalize_recruitment_search_text(coalesce(e.area_name, '')) like '%' || entry_driver_area_search || '%' then 0
            else 1
          end as area_priority
        from public.employees_active_current e
        where
          (
            entry_driver_buk_employee_id is not null
            and e.buk_employee_id = entry_driver_buk_employee_id
          )
          or (
            entry_driver_document_digits is not null
            and public.build_employee_document_digits(e.document_number, e.raw_payload) = entry_driver_document_digits
          )
          or (
            entry_driver_search <> ''
            and public.build_active_employee_search_text(
              e.full_name,
              e.document_number,
              e.job_title,
              e.contract_code,
              e.area_name,
              e.raw_payload
            ) like '%' || entry_driver_search || '%'
          )
      ) candidate
     where candidate.identity_rank = 1
       and candidate.match_priority < 9
     order by candidate.match_priority, candidate.area_priority, candidate.full_name asc
     limit 1;

    select
      rs.base_status,
      rs.effective_status
      into
        resolved_driver_base_status,
        resolved_driver_effective_status
      from public.resolve_hr_roster_day_status(
        resolved_driver_buk_employee_id,
        (entry_item->>'serviceDate')::date
      ) rs;

    resolved_driver_shift_status := public.map_operations_driver_shift_status(resolved_driver_effective_status);

    lock_key := concat_ws(
      ':',
      current_user_id::text,
      entry_item->>'serviceDate',
      lower(entry_item->>'shift'),
      resolved_contract_id::text,
      resolved_service_id::text
    );
    perform pg_advisory_xact_lock(hashtext(lock_key));

    existing_entry_id := null;

    select se.id
      into existing_entry_id
      from public.service_entries se
     where se.service_date = (entry_item->>'serviceDate')::date
       and se.shift = lower(entry_item->>'shift')
       and se.contract_id = resolved_contract_id
       and se.base_service_id = resolved_service_id
       and se.created_by = current_user_id
     order by se.created_at desc
     limit 1
     for update;

    if existing_entry_id is null then
      insert into public.service_entries (
        service_date,
        shift,
        base_service_id,
        contract_id,
        contract_code,
        service_operational_name,
        service_contractual_name,
        service_category,
        service_company,
        driver_buk_employee_id,
        driver_name,
        driver_document,
        driver_area,
        driver_shift_status,
        driver_shift_source,
        driver_roster_base_status,
        driver_roster_effective_status,
        equipment_code,
        equipment_plate,
        equipment_type,
        equipment_client,
        created_by
      )
      values (
        (entry_item->>'serviceDate')::date,
        lower(entry_item->>'shift'),
        resolved_service_id,
        resolved_contract_id,
        resolved_contract_code,
        resolved_service_operational_name,
        resolved_service_contractual_name,
        resolved_service_contractual_category,
        resolved_service_company_name,
        resolved_driver_buk_employee_id,
        resolved_driver_name,
        resolved_driver_document,
        resolved_driver_area,
        resolved_driver_shift_status,
        'roster',
        resolved_driver_base_status,
        resolved_driver_effective_status,
        resolved_equipment_code,
        resolved_equipment_plate,
        resolved_equipment_type,
        resolved_equipment_client,
        current_user_id
      );
    else
      update public.service_entries
         set service_date = (entry_item->>'serviceDate')::date,
             shift = lower(entry_item->>'shift'),
             base_service_id = resolved_service_id,
             contract_id = resolved_contract_id,
             contract_code = resolved_contract_code,
             service_operational_name = resolved_service_operational_name,
             service_contractual_name = resolved_service_contractual_name,
             service_category = resolved_service_contractual_category,
             service_company = resolved_service_company_name,
             driver_buk_employee_id = resolved_driver_buk_employee_id,
             driver_name = resolved_driver_name,
             driver_document = resolved_driver_document,
             driver_area = resolved_driver_area,
             driver_shift_status = resolved_driver_shift_status,
             driver_shift_source = 'roster',
             driver_roster_base_status = resolved_driver_base_status,
             driver_roster_effective_status = resolved_driver_effective_status,
             equipment_code = resolved_equipment_code,
             equipment_plate = resolved_equipment_plate,
             equipment_type = resolved_equipment_type,
             equipment_client = resolved_equipment_client
       where id = existing_entry_id;
    end if;

    saved_count := saved_count + 1;
  end loop;

  return jsonb_build_object('ok', true, 'saved_count', saved_count);
end;
$function$;

revoke all on function public.submit_service_entries_batch(jsonb) from public, anon;
grant execute on function public.submit_service_entries_batch(jsonb) to authenticated;

do $$
declare
  required_contracts integer;
begin
  select count(*)
    into required_contracts
    from public.contracts
   where coalesce(nullif(trim(contract_name), ''), code) in ('CODELCO DRT', 'CODELCO DMH')
     and is_active = true;

  if required_contracts < 2 then
    raise exception 'Operaciones requiere contratos activos CODELCO DRT y CODELCO DMH antes de sembrar servicios base.';
  end if;
end
$$;

with service_seed (
  external_key,
  operational_name,
  company_name,
  service_type,
  contractual_name,
  contractual_category,
  contract_code,
  schedule_label
) as (
  values
  (1, 'Bus Administrativo 1', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (2, 'Bus Administrativo 2', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (3, 'Bus Administrativo 3', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (4, 'Bus Administrativo 4', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (5, 'Bus Administrativo 6', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (6, 'Bus Administrativo 7', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (7, 'Bus Administrativo 8', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (8, 'Bus Administrativo 9', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (9, 'Bus Administrativo 10', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 4x3', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Jueves'),
  (10, 'Bus Operativo Mina 1', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (11, 'Bus Operativo Mina 2', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (12, 'Bus Operativo Mina 3', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (13, 'Bus Operativo Mina 4', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (14, 'Bus Operativo Mina 5', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (15, 'Bus Operativo Mina 6', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (16, 'Bus Operativo Mina 7', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (17, 'Bus Operativo Mina 8', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (18, 'Bus Operativo Mina 9', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (19, 'Bus Operativo Planta 1', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (20, 'Bus Operativo Planta 2', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (21, 'Bus Operativo Planta 3', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (22, 'Bus Mantenimiento Mina', 'Codelco', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (23, 'Bus Minspa 1', 'Minspa', 'BUS', 'Bus Eléctrico 42 asientos - 7x7', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (24, 'Bus Minspa 2', 'Minspa', 'BUS', 'Bus Eléctrico 42 asientos - 7x8', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (25, 'Bus Minspa 3', 'Minspa', 'BUS', 'Bus Eléctrico 42 asientos - 7x9', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (26, 'Bus Minspa 4', 'Minspa', 'BUS', 'Bus Eléctrico 42 asientos - 7x10', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (27, 'Bus Minspa 5', 'Minspa', 'BUS', 'Bus Eléctrico 42 asientos - 7x11', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (28, 'Bus CYD OP 1', 'CYD', 'BUS', 'Bus Eléctrico 42 asientos - 7x11', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (29, 'Bus CYD OP 2', 'CYD', 'BUS', 'Bus Eléctrico 42 asientos - 7x11', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (30, 'Bus Aramark OP 1', 'Aramark', 'BUS', 'Bus Eléctrico 42 asientos - 7x11', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (31, 'Bus Aramark OP 2', 'Aramark', 'BUS', 'Bus Eléctrico 42 asientos - 7x11', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Domingo'),
  (32, 'Bus CYD ADM 1', 'CYD', 'BUS', 'Bus Eléctrico 42 asientos - 5x2', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Viernes'),
  (33, 'Bus Aramark ADM 1', 'Aramark', 'BUS', 'Bus Eléctrico 42 asientos - 5x2', 'Submódulo 1.2', 'CODELCO DRT', 'Lunes a Viernes'),
  (34, 'Taxi Directo JM', 'Codelco', 'TAXIBUS', 'Taxibus Diésel 4x2 18 asientos / Calama - DRT', 'Sub Modulo 1.4', 'CODELCO DRT', 'Lunes a Domingo'),
  (35, 'Taxi Directo JM', 'Codelco', 'TAXIBUS', 'Taxibus Diésel 4x2 18 asientos / Calama - DRT', 'Sub Modulo 1.4', 'CODELCO DRT', 'Lunes a Domingo'),
  (36, 'Taxi Planta Norte', 'Codelco', 'TAXIBUS', 'Taxibus Diésel 4x2 18 asientos / Calama - DRT', 'Sub Modulo 1.4', 'CODELCO DRT', 'Lunes a Domingo'),
  (37, 'Taxi Planta Sur', 'Codelco', 'TAXIBUS', 'Taxibus Diésel 4x2 18 asientos / Calama - DRT', 'Sub Modulo 1.4', 'CODELCO DRT', 'Lunes a Domingo'),
  (38, 'Taxi GRMD', 'Codelco', 'TAXIBUS', 'Taxibus Diésel 4x2 18 asientos / Calama - DRT', 'Sub Modulo 1.4', 'CODELCO DRT', 'Lunes a Domingo'),
  (39, 'Taxi Bus Acercamiento', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (40, 'Taxi Bus Especiales 1', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (41, 'Taxi Bus Especiales 2', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (42, 'Taxi Mina 1', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (43, 'Taxi Mina 2', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (44, 'Taxi Mina 3', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (45, 'Taxi Mina 4', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (46, 'Taxi Mina 5', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (47, 'Taxi Mina 6', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (48, 'Taxi Mina 7', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (49, 'Taxi Mina 8', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (50, 'Taxi Mina 9', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (51, 'Taxi Mina 10', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (52, 'Taxi Mina 11', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (53, 'Taxi Mina 12', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (54, 'Taxi Planta 1', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (55, 'Taxi Planta 2', 'Codelco', 'TAXIBUS', 'Taxibus Diesel 4x2 26 asientos', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (56, 'Acercamiento Planta 1', 'Codelco', 'MINIBUS', 'Carry Diesel 15 asientos ', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (57, 'Acercamiento Planta 2', 'Codelco', 'MINIBUS', 'Carry Diesel 15 asientos ', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (58, 'Acercamiento Mixto', 'Codelco', 'MINIBUS', 'Carry Diesel 15 asientos ', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (59, 'Acercamiento Adm 5', 'Codelco', 'MINIBUS', 'Carry Diesel 15 asientos ', 'Submódulo 1.1', 'CODELCO DRT', 'Lunes a Domingo'),
  (60, 'Administrativo BCD 1', 'Codelco', 'MINIBUS', 'Carry Externo Administrativo BCD 4x3', 'Item 1.3', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (61, 'Administrativo BCD 2', 'Codelco', 'MINIBUS', 'Carry Externo Administrativo BCD 4x3', 'Item 1.3', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (62, 'Administrativo BCD 3', 'Codelco', 'MINIBUS', 'Carry Externo Administrativo BCD 4x3', 'Item 1.3', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (63, 'Administrativo BCD 4', 'Codelco', 'MINIBUS', 'Carry Externo Administrativo BCD 4x3', 'Item 1.3', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (64, 'Administrativo BCD 5', 'Codelco', 'MINIBUS', 'Carry Externo Administrativo BCD 4x3', 'Item 1.3', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (65, 'Administrativo BCD 6', 'Codelco', 'MINIBUS', 'Carry Externo Administrativo BCD 4x3', 'Item 1.3', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (66, 'Administrativo Mina 1', 'Codelco', 'MINIBUS', 'Carry externo administrativo mina', 'Item 1.5', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (67, 'Administrativo Mina 2', 'Codelco', 'MINIBUS', 'Carry externo administrativo mina', 'Item 1.5', 'SERVICIO CODELCO DMH', 'Lunes a Jueves'),
  (68, 'MONCON', 'Codelco', 'MINIBUS', 'Carry externo administrativo planta 6x6 A', 'Item 1.4', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (69, 'Operativo Mina 1', 'Codelco', 'MINIBUS', 'Carry externo mina 6x6 turno A/B', 'Item 1.2', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (70, 'Operativo Mina 2', 'Codelco', 'MINIBUS', 'Carry externo mina 6x6 turno A/B', 'Item 1.2', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (71, 'Operativo Mina 3', 'Codelco', 'MINIBUS', 'Carry externo mina 6x6 turno A/B', 'Item 1.2', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (72, 'Operativo Mina 4', 'Codelco', 'MINIBUS', 'Carry externo mina 6x6 turno A/B', 'Item 1.2', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (73, 'Operativo Mina 5', 'Codelco', 'MINIBUS', 'Carry externo mina 6x6 turno A/B', 'Item 1.2', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (74, 'Operativo Mina 6', 'Codelco', 'MINIBUS', 'Carry externo mina 6x6 turno A/B', 'Item 1.2', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (75, 'Operativo Mina 7', 'Codelco', 'MINIBUS', 'Carry externo mina 6x6 turno A/B', 'Item 1.2', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (76, 'Operativo Mina 8', 'Codelco', 'MINIBUS', 'Carry adicionales al contrato desde el año 2022- externo turno A', 'Item 1.12', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (77, 'Operativo Planta 1', 'Codelco', 'MINIBUS', 'Carry externo planta 6x6 turno A/B', 'Item 1.1', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (78, 'Operativo Planta 2', 'Codelco', 'MINIBUS', 'Carry externo planta 6x6 turno A/B', 'Item 1.1', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (79, 'Operativo Planta 4', 'Codelco', 'MINIBUS', 'Carry externo planta 6x6 turno A/B', 'Item 1.1', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (80, 'Jefe de Turno', 'Codelco', 'MINIBUS', 'Carry all externo jefe turno mina', 'Item 1.6', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (81, 'CIO', 'Codelco', 'MINIBUS', 'Carry externo CIO turno 6x6', 'Item 1.6', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (82, 'San Lorenzo', 'Codelco', 'BUS', 'Bus COVID-19 externo turno 6x6', 'Item 1.11', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (83, 'Interno Planta', 'Codelco', 'MINIBUS', 'Carry Interno Planta rajo 6x6 turno A/B', 'Item 1.9', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (84, 'Interno Mina 1', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (85, 'Interno Mina 2', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (86, 'Interno Mina 3', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (87, 'Interno Mina 4', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (88, 'Interno Mina 5', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (89, 'Interno Mina 6', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (90, 'Interno Mina 7', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (91, 'Interno Mina 8', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo'),
  (92, 'Interno Mina 9', 'Codelco', 'MINIBUS', 'Carry Interno Mina rajo 6x6 turno A/B', 'Item 1.8', 'SERVICIO CODELCO DMH', 'Lunes a Domingo')
)
insert into public.base_services (
  external_key,
  operational_name,
  company_name,
  service_type,
  contractual_name,
  contractual_category,
  contract_id,
  schedule_label,
  is_active
)
select
  ss.external_key,
  ss.operational_name,
  ss.company_name,
  ss.service_type,
  ss.contractual_name,
  ss.contractual_category,
  c.id,
  ss.schedule_label,
  true
from service_seed ss
join public.contracts c
  on (
    c.code = ss.contract_code
    or c.contract_name = ss.contract_code
    or c.contract_name = replace(ss.contract_code, 'SERVICIO ', '')
  )
 and c.is_active = true
on conflict (external_key) do update
set
  operational_name = excluded.operational_name,
  company_name = excluded.company_name,
  service_type = excluded.service_type,
  contractual_name = excluded.contractual_name,
  contractual_category = excluded.contractual_category,
  contract_id = excluded.contract_id,
  schedule_label = excluded.schedule_label,
  is_active = true;

insert into public.equipment (
  equipment_code,
  is_active
)
values
  ('BUS-042', true),
  ('BUS-115', true),
  ('MB-203', true),
  ('TX-018', true),
  ('TX-026', true),
  ('CRY-015', true)
on conflict (equipment_code) do update
set is_active = excluded.is_active;

notify pgrst, 'reload schema';

commit;
